# ARC_ATLAS v4 - Native-Geometry nnU-Net

This notebook uses the same training split as the recent v4 runs: `data/splits/90_10_random/train/manifest.csv` with ATLAS, ARC, and Approx cases.

The nnU-Net folders created here are only a format view required by nnU-Net: images are symlinked from the same split and labels are written as clean `uint8` masks. The source MRIs keep their native full dimensions and affine/spacing. No `TARGET_SHAPE` resize is applied here.

Training is `3d_fullres`. nnU-Net will try to keep full voxel resolution and choose the largest 3D patch that fits GPU memory. A true whole-volume tensor is only feasible if the planner/GPU can fit it; otherwise patch-based training is the memory fallback, while still using full-resolution MRIs.

In [16]:
from pathlib import Path
import json
import os
import sys

PROJECT_ROOT = Path("/home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4").resolve()
os.chdir(PROJECT_ROOT)

SRC = PROJECT_ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

import atlas_nnunet_pipeline as pipe

SOURCE_DATA_DIR = PROJECT_ROOT / "data" / "splits" / "90_10_random" / "train"
MANIFEST = SOURCE_DATA_DIR / "manifest.csv"
NNUNET_VIEW_ROOT = SOURCE_DATA_DIR / "nnunet_view"
CV_ROOT = PROJECT_ROOT / "runs" / "nnunet_cv_predictions_native_split"
PLANS_NAME = "nnUNetPlans_24GB"

layout = pipe.NnUNetLayout(
    project_root=PROJECT_ROOT,
    nnunet_root=NNUNET_VIEW_ROOT,
    dataset_id=701,
    dataset_name="ARC_ATLAS_TrainV4Native",
)

print("Project:", PROJECT_ROOT)
print("Source dataset:", SOURCE_DATA_DIR)
print("Manifest:", MANIFEST)
print("nnU-Net view raw:", layout.raw)
print("nnU-Net view preprocessed:", layout.preprocessed)
print("nnU-Net view results:", layout.results)

Project: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4
Source dataset: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train
Manifest: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train/manifest.csv
nnU-Net view raw: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train/nnunet_view/nnUNet_raw
nnU-Net view preprocessed: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train/nnunet_view/nnUNet_preprocessed
nnU-Net view results: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train/nnunet_view/nnUNet_results

## 1. Runtime Check

In [17]:
pipe.print_preflight(layout)

checks = pipe.preflight(layout)
missing = [k for k, v in checks.items() if str(v).startswith("missing") or (k.startswith("nnUNetv2_") and not v)]
if missing:
    print("\nMissing runtime pieces:", missing)
    print("Install in tf_310 with: pip install -r requirements_nnunet.txt")

python                           /home/rbielski/miniconda3/envs/tf_310/bin/python
nnUNet_raw                       /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train/nnunet_view/nnUNet_raw
nnUNet_preprocessed              /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train/nnunet_view/nnUNet_preprocessed
nnUNet_results                   /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train/nnunet_view/nnUNet_results
nnUNetv2_plan_and_preprocess     /home/rbielski/miniconda3/envs/tf_310/bin/nnUNetv2_plan_and_preprocess
nnUNetv2_train                   /home/rbielski/miniconda3/envs/tf_310/bin/nnUNetv2_train
nnUNetv2_predict                 /home/rbielski/miniconda3/envs/tf_310/bin/nnUNetv2_predict
python:torch                     2.5.1+cu124
python:nnunetv2                  installed
python:nibabel                   5.3.2
python:scipy                     1.13.1
python:sklearn                   1.6.1

## 2. Inspect The Exact Source Split

This is the dataset choice. It should match the v4 split you were using before.

In [18]:
import pandas as pd
import nibabel as nib

source_df = pd.read_csv(MANIFEST)
print("Rows:", len(source_df))
display(source_df.groupby("slug").size().rename("n").to_frame())

shape_rows = []
for _, row in source_df.iterrows():
    img = nib.load(row.t1)
    shape_rows.append({
        "slug": row.slug,
        "shape": "x".join(map(str, img.shape)),
        "spacing": "x".join(f"{float(z):.6g}" for z in img.header.get_zooms()[:3]),
    })
shape_df = pd.DataFrame(shape_rows)
print("Native image shapes / spacing in the source split:")
display(shape_df.groupby(["slug", "shape", "spacing"]).size().rename("n").reset_index().sort_values(["slug", "n"], ascending=[True, False]))

Rows: 866

                                n
slug
ARC-combined-t1-raw-ab0d1794  190
ATLAS-Images-f0d7431e         582
Approx-Numeracy-Processed      94

Native image shapes / spacing in the source split:

                           slug        shape spacing    n
0  ARC-combined-t1-raw-ab0d1794  193x229x193   1x1x1  190
1         ATLAS-Images-f0d7431e  193x229x193   1x1x1  582
2     Approx-Numeracy-Processed  193x229x193   1x1x1   94

## 3. Build nnU-Net View Of The Same Data

This does not change the source dataset. It creates nnU-Net's required `imagesTr`/`labelsTr` layout under the same split directory, symlinking MRIs from `t1/` and writing binary label files from `masks/`.

In [19]:
OVERWRITE_NNUNET_VIEW = False

if not layout.mapping_csv.exists() or OVERWRITE_NNUNET_VIEW:
    summary = pipe.prepare_nnunet_dataset(
        MANIFEST,
        layout,
        copy_mode="symlink",
        overwrite=OVERWRITE_NNUNET_VIEW,
        n_splits=5,
    )
else:
    with (layout.raw_dataset_dir / "conversion_summary.json").open() as f:
        summary = json.load(f)

print(json.dumps(summary, indent=2))

{
  "source_manifest": "/home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train/manifest.csv",
  "dataset_dir": "/home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train/nnunet_view/nnUNet_raw/Dataset701_ARC_ATLAS_TrainV4Native",
  "preprocessed_dir": "/home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train/nnunet_view/nnUNet_preprocessed/Dataset701_ARC_ATLAS_TrainV4Native",
  "results_dir": "/home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train/nnunet_view/nnUNet_results",
  "dataset_id": 701,
  "dataset_name": "Dataset701_ARC_ATLAS_TrainV4Native",
  "num_cases": 866,
  "copy_mode": "symlink",
  "folds": [
    {
      "fold": 0,
      "train": 692,
      "val": 174
    },
    {
      "fold": 1,
      "train": 693,
      "val": 173
    },
    {
      "fold": 2,
      "train": 693,
      "val": 173
    },
    {
      "fold": 3,
      "train": 693,
      "val": 173
    },
    {
      "fold": 4,
      "train": 693,
      "val": 173
    }
  ],
  "lesion_groups": {
    "000001_000099": 26,
    "000100_000999": 176,
    "001000_009999": 234,
    "010000_plus": 430
  },
  "sources": {
    "ARC-combined-t1-raw-ab0d1794": 190,
    "ATLAS-Images-f0d7431e": 582,
    "Approx-Numeracy-Processed": 94
  },
  "created_at": "2026-05-01 15:04:43"
}

In [20]:
mapping = pd.read_csv(layout.mapping_csv)
print("Cases in nnU-Net view:", len(mapping))
display(mapping.groupby(["source_slug", "fold"]).size().unstack(fill_value=0))
display(mapping.groupby(["fold", "lesion_group"]).size().unstack(fill_value=0))
display(mapping[["case_id", "fold", "source_slug", "lesion_voxels", "shape", "spacing", "key"]].head())

Cases in nnU-Net view: 866

fold                            0    1    2    3    4
source_slug
ARC-combined-t1-raw-ab0d1794   37   37   35   40   41
ATLAS-Images-f0d7431e         115  115  124  113  115
Approx-Numeracy-Processed      22   21   14   20   17

lesion_group  000001_000099  000100_000999  001000_009999  010000_plus
fold
0                         6             36             46           86
1                         5             35             47           86
2                         5             35             47           86
3                         5             35             47           86
4                         5             35             47           86

,case_id,fold,source_slug,lesion_voxels,shape,spacing,key
0,case_0001_sub_m2306,3,ARC-combined-t1-raw-ab0d1794,149459,193x229x193,1x1x1,sub-M2306_ses-707_acq-tfl3p2_run-3_T1w_MNI_nor...
1,case_0002_sub_r034s039,3,ATLAS-Images-f0d7431e,51687,193x229x193,1x1x1,sub-r034s039_ses-1_space-MNI152NLin2009aSym_T1...
2,case_0003_sub_062,0,Approx-Numeracy-Processed,45373,193x229x193,1x1x1,sub-062_T1w_MNI_norm.nii.gz
3,case_0004_sub_r011s017,3,ATLAS-Images-f0d7431e,823,193x229x193,1x1x1,sub-r011s017_ses-1_space-MNI152NLin2009aSym_T1...
4,case_0005_sub_m2283,4,ARC-combined-t1-raw-ab0d1794,48959,193x229x193,1x1x1,sub-M2283_ses-246_acq-tfl3p2_run-4_T1w_MNI_nor...

## 4. Plan At Full Resolution First

Run the `--no-preprocess` cells first to inspect patch size before preprocessing. The default plan is conservative. The 24 GB plan targets this machine's RTX 4090 memory and gets closer to the full volume, but nnU-Net still crops nonzero background before planning unless we add a custom no-crop preprocessor.

Raw source shape is `193x229x193`; current nnU-Net crop median is `156x186x148`.

In [21]:
pipe.print_recommended_commands(layout)

# Environment
export nnUNet_raw=/home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train/nnunet_view/nnUNet_raw
export nnUNet_preprocessed=/home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train/nnunet_view/nnUNet_preprocessed
export nnUNet_results=/home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train/nnunet_view/nnUNet_results

# Plan and preprocess
nnUNetv2_plan_and_preprocess -d 701 --verify_dataset_integrity -c 3d_fullres

# Train five full-resolution 3D folds
nnUNetv2_train 701 3d_fullres 0 --npz
nnUNetv2_train 701 3d_fullres 1 --npz
nnUNetv2_train 701 3d_fullres 2 --npz
nnUNetv2_train 701 3d_fullres 3 --npz
nnUNetv2_train 701 3d_fullres 4 --npz

# Leak-free CV inference
/home/rbielski/miniconda3/envs/tf_310/bin/python src/atlas_nnunet_pipeline.py predict-cv --nnunet-root /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train/nnunet_view

# Evaluate CV predictions
/home/rbielski/miniconda3/envs/tf_310/bin/python src/atlas_nnunet_pipeline.py evaluate --nnunet-root /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train/nnunet_view

In [22]:
RUN_FINGERPRINT_AND_PLAN_ONLY = True

if RUN_FINGERPRINT_AND_PLAN_ONLY:
    pipe.plan_and_preprocess(layout, verify=True, no_preprocess=True, num_processes=[4])
else:
    print("Set RUN_FINGERPRINT_AND_PLAN_ONLY=True to verify data and inspect default 3d_fullres patch size without preprocessing.")

/home/rbielski/miniconda3/envs/tf_310/bin/nnUNetv2_plan_and_preprocess -d 701 --verify_dataset_integrity --no_pp -c 3d_fullres -np 4
Fingerprint extraction...
Dataset701_ARC_ATLAS_TrainV4Native
Using <class 'nnunetv2.imageio.simpleitk_reader_writer.SimpleITKIO'> as reader/writer

####################
verify_dataset_integrity Done.
If you didn't see any error messages then your dataset is most likely OK!
####################

Experiment planning...

############################
INFO: You are using the old nnU-Net default planner. We have updated our recommendations. Please consider using those instead! Read more here: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/resenc_presets.md
############################

Dropping 3d_lowres config because the image size difference to 3d_fullres is too small. 3d_fullres: [156. 186. 148.], 3d_lowres: [156, 186, 148]
2D U-Net configuration:
{'data_identifier': 'nnUNetPlans_2d', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 106, 'patch_size': (np.int64(192), np.int64(160)), 'median_image_size_in_voxels': array([186., 148.]), 'spacing': array([1., 1.]), 'normalization_schemes': ['ZScoreNormalization'], 'use_mask_for_norm': [True], 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'architecture': {'network_class_name': 'dynamic_network_architectures.architectures.unet.PlainConvUNet', 'arch_kwargs': {'n_stages': 6, 'features_per_stage': (32, 64, 128, 256, 512, 512), 'conv_op': 'torch.nn.modules.conv.Conv2d', 'kernel_sizes': ((3, 3), (3, 3), (3, 3), (3, 3), (3, 3), (3, 3)), 'strides': ((1, 1), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2)), 'n_conv_per_stage': (2, 2, 2, 2, 2, 2), 'n_conv_per_stage_decoder': (2, 2, 2, 2, 2), 'conv_bias': True, 'norm_op': 'torch.nn.modules.instancenorm.InstanceNorm2d', 'norm_op_kwargs': {'eps': 1e-05, 'affine': True}, 'dropout_op': None, 'dropout_op_kwargs': None, 'nonlin': 'torch.nn.LeakyReLU', 'nonlin_kwargs': {'inplace': True}}, '_kw_requires_import': ('conv_op', 'norm_op', 'dropout_op', 'nonlin')}, 'batch_dice': True}

Using <class 'nnunetv2.imageio.simpleitk_reader_writer.SimpleITKIO'> as reader/writer
3D fullres U-Net configuration:
{'data_identifier': 'nnUNetPlans_3d_fullres', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 2, 'patch_size': (np.int64(128), np.int64(160), np.int64(112)), 'median_image_size_in_voxels': array([156., 186., 148.]), 'spacing': array([1., 1., 1.]), 'normalization_schemes': ['ZScoreNormalization'], 'use_mask_for_norm': [True], 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'architecture': {'network_class_name': 'dynamic_network_architectures.architectures.unet.PlainConvUNet', 'arch_kwargs': {'n_stages': 6, 'features_per_stage': (32, 64, 128, 256, 320, 320), 'conv_op': 'torch.nn.modules.conv.Conv3d', 'kernel_sizes': ((3, 3, 3), (3, 3, 3), (3, 3, 3), (3, 3, 3), (3, 3, 3), (3, 3, 3)), 'strides': ((1, 1, 1), (2, 2, 2), (2, 2, 2), (2, 2, 2), (2, 2, 2), (2, 2, 1)), 'n_conv_per_stage': (2, 2, 2, 2, 2, 2), 'n_conv_per_stage_decoder': (2, 2, 2, 2, 2), 'conv_bias': True, 'norm_op': 'torch.nn.modules.instancenorm.InstanceNorm3d', 'norm_op_kwargs': {'eps': 1e-05, 'affine': True}, 'dropout_op': None, 'dropout_op_kwargs': None, 'nonlin': 'torch.nn.LeakyReLU', 'nonlin_kwargs': {'inplace': True}}, '_kw_requires_import': ('conv_op', 'norm_op', 'dropout_op', 'nonlin')}, 'batch_dice': False}

Plans were saved to /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train/nnunet_view/nnUNet_preprocessed/Dataset701_ARC_ATLAS_TrainV4Native/nnUNetPlans.json

In [23]:
RUN_24GB_PLAN_ONLY = True

if RUN_24GB_PLAN_ONLY:
    pipe.plan_and_preprocess(
        layout,
        verify=False,
        no_preprocess=True,
        configurations=("3d_fullres",),
        num_processes=[4],
        gpu_memory_target=24,
        overwrite_plans_name="nnUNetPlans_24GB",
    )
else:
    print("Set RUN_24GB_PLAN_ONLY=True to create a 24GB planning-only variant before preprocessing.")

/home/rbielski/miniconda3/envs/tf_310/bin/nnUNetv2_plan_and_preprocess -d 701 --no_pp -c 3d_fullres -np 4 -gpu_memory_target 24 -overwrite_plans_name nnUNetPlans_24GB
Fingerprint extraction...
Dataset701_ARC_ATLAS_TrainV4Native
Experiment planning...

############################
INFO: You are using the old nnU-Net default planner. We have updated our recommendations. Please consider using those instead! Read more here: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/resenc_presets.md
############################

Dropping 3d_lowres config because the image size difference to 3d_fullres is too small. 3d_fullres: [156. 186. 148.], 3d_lowres: [156, 186, 148]
2D U-Net configuration:
{'data_identifier': 'nnUNetPlans_24GB_2d', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 318, 'patch_size': (np.int64(192), np.int64(160)), 'median_image_size_in_voxels': array([186., 148.]), 'spacing': array([1., 1.]), 'normalization_schemes': ['ZScoreNormalization'], 'use_mask_for_norm': [True], 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'architecture': {'network_class_name': 'dynamic_network_architectures.architectures.unet.PlainConvUNet', 'arch_kwargs': {'n_stages': 6, 'features_per_stage': (32, 64, 128, 256, 512, 512), 'conv_op': 'torch.nn.modules.conv.Conv2d', 'kernel_sizes': ((3, 3), (3, 3), (3, 3), (3, 3), (3, 3), (3, 3)), 'strides': ((1, 1), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2)), 'n_conv_per_stage': (2, 2, 2, 2, 2, 2), 'n_conv_per_stage_decoder': (2, 2, 2, 2, 2), 'conv_bias': True, 'norm_op': 'torch.nn.modules.instancenorm.InstanceNorm2d', 'norm_op_kwargs': {'eps': 1e-05, 'affine': True}, 'dropout_op': None, 'dropout_op_kwargs': None, 'nonlin': 'torch.nn.LeakyReLU', 'nonlin_kwargs': {'inplace': True}}, '_kw_requires_import': ('conv_op', 'norm_op', 'dropout_op', 'nonlin')}, 'batch_dice': True}

Using <class 'nnunetv2.imageio.simpleitk_reader_writer.SimpleITKIO'> as reader/writer
3D fullres U-Net configuration:
{'data_identifier': 'nnUNetPlans_24GB_3d_fullres', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 3, 'patch_size': (np.int64(160), np.int64(192), np.int64(160)), 'median_image_size_in_voxels': array([156., 186., 148.]), 'spacing': array([1., 1., 1.]), 'normalization_schemes': ['ZScoreNormalization'], 'use_mask_for_norm': [True], 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'architecture': {'network_class_name': 'dynamic_network_architectures.architectures.unet.PlainConvUNet', 'arch_kwargs': {'n_stages': 6, 'features_per_stage': (32, 64, 128, 256, 320, 320), 'conv_op': 'torch.nn.modules.conv.Conv3d', 'kernel_sizes': ((3, 3, 3), (3, 3, 3), (3, 3, 3), (3, 3, 3), (3, 3, 3), (3, 3, 3)), 'strides': ((1, 1, 1), (2, 2, 2), (2, 2, 2), (2, 2, 2), (2, 2, 2), (2, 2, 2)), 'n_conv_per_stage': (2, 2, 2, 2, 2, 2), 'n_conv_per_stage_decoder': (2, 2, 2, 2, 2), 'conv_bias': True, 'norm_op': 'torch.nn.modules.instancenorm.InstanceNorm3d', 'norm_op_kwargs': {'eps': 1e-05, 'affine': True}, 'dropout_op': None, 'dropout_op_kwargs': None, 'nonlin': 'torch.nn.LeakyReLU', 'nonlin_kwargs': {'inplace': True}}, '_kw_requires_import': ('conv_op', 'norm_op', 'dropout_op', 'nonlin')}, 'batch_dice': False}

Plans were saved to /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train/nnunet_view/nnUNet_preprocessed/Dataset701_ARC_ATLAS_TrainV4Native/nnUNetPlans_24GB.json

In [24]:
RUN_PLAN_AND_PREPROCESS = True

if RUN_PLAN_AND_PREPROCESS:
    pipe.plan_and_preprocess(
        layout,
        verify=True,
        configurations=("3d_fullres",),
        num_processes=[4],
        gpu_memory_target=24,
        overwrite_plans_name=PLANS_NAME,
    )
else:
    print("Set RUN_PLAN_AND_PREPROCESS=True after the planner patch size looks acceptable.")

/home/rbielski/miniconda3/envs/tf_310/bin/nnUNetv2_plan_and_preprocess -d 701 --verify_dataset_integrity -c 3d_fullres -np 4 -gpu_memory_target 24 -overwrite_plans_name nnUNetPlans_24GB
Fingerprint extraction...
Dataset701_ARC_ATLAS_TrainV4Native
Using <class 'nnunetv2.imageio.simpleitk_reader_writer.SimpleITKIO'> as reader/writer

####################
verify_dataset_integrity Done.
If you didn't see any error messages then your dataset is most likely OK!
####################

Experiment planning...

############################
INFO: You are using the old nnU-Net default planner. We have updated our recommendations. Please consider using those instead! Read more here: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/resenc_presets.md
############################

Dropping 3d_lowres config because the image size difference to 3d_fullres is too small. 3d_fullres: [156. 186. 148.], 3d_lowres: [156, 186, 148]
2D U-Net configuration:
{'data_identifier': 'nnUNetPlans_24GB_2d', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 318, 'patch_size': (np.int64(192), np.int64(160)), 'median_image_size_in_voxels': array([186., 148.]), 'spacing': array([1., 1.]), 'normalization_schemes': ['ZScoreNormalization'], 'use_mask_for_norm': [True], 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'architecture': {'network_class_name': 'dynamic_network_architectures.architectures.unet.PlainConvUNet', 'arch_kwargs': {'n_stages': 6, 'features_per_stage': (32, 64, 128, 256, 512, 512), 'conv_op': 'torch.nn.modules.conv.Conv2d', 'kernel_sizes': ((3, 3), (3, 3), (3, 3), (3, 3), (3, 3), (3, 3)), 'strides': ((1, 1), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2)), 'n_conv_per_stage': (2, 2, 2, 2, 2, 2), 'n_conv_per_stage_decoder': (2, 2, 2, 2, 2), 'conv_bias': True, 'norm_op': 'torch.nn.modules.instancenorm.InstanceNorm2d', 'norm_op_kwargs': {'eps': 1e-05, 'affine': True}, 'dropout_op': None, 'dropout_op_kwargs': None, 'nonlin': 'torch.nn.LeakyReLU', 'nonlin_kwargs': {'inplace': True}}, '_kw_requires_import': ('conv_op', 'norm_op', 'dropout_op', 'nonlin')}, 'batch_dice': True}

Using <class 'nnunetv2.imageio.simpleitk_reader_writer.SimpleITKIO'> as reader/writer
3D fullres U-Net configuration:
{'data_identifier': 'nnUNetPlans_24GB_3d_fullres', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 3, 'patch_size': (np.int64(160), np.int64(192), np.int64(160)), 'median_image_size_in_voxels': array([156., 186., 148.]), 'spacing': array([1., 1., 1.]), 'normalization_schemes': ['ZScoreNormalization'], 'use_mask_for_norm': [True], 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'architecture': {'network_class_name': 'dynamic_network_architectures.architectures.unet.PlainConvUNet', 'arch_kwargs': {'n_stages': 6, 'features_per_stage': (32, 64, 128, 256, 320, 320), 'conv_op': 'torch.nn.modules.conv.Conv3d', 'kernel_sizes': ((3, 3, 3), (3, 3, 3), (3, 3, 3), (3, 3, 3), (3, 3, 3), (3, 3, 3)), 'strides': ((1, 1, 1), (2, 2, 2), (2, 2, 2), (2, 2, 2), (2, 2, 2), (2, 2, 2)), 'n_conv_per_stage': (2, 2, 2, 2, 2, 2), 'n_conv_per_stage_decoder': (2, 2, 2, 2, 2), 'conv_bias': True, 'norm_op': 'torch.nn.modules.instancenorm.InstanceNorm3d', 'norm_op_kwargs': {'eps': 1e-05, 'affine': True}, 'dropout_op': None, 'dropout_op_kwargs': None, 'nonlin': 'torch.nn.LeakyReLU', 'nonlin_kwargs': {'inplace': True}}, '_kw_requires_import': ('conv_op', 'norm_op', 'dropout_op', 'nonlin')}, 'batch_dice': False}

Plans were saved to /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train/nnunet_view/nnUNet_preprocessed/Dataset701_ARC_ATLAS_TrainV4Native/nnUNetPlans_24GB.json
Preprocessing...
Preprocessing dataset Dataset701_ARC_ATLAS_TrainV4Native
Configuration: 3d_fullres...
{'data_identifier': 'nnUNetPlans_24GB_3d_fullres', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 3, 'patch_size': [160, 192, 160], 'median_image_size_in_voxels': [156.0, 186.0, 148.0], 'spacing': [1.0, 1.0, 1.0], 'normalization_schemes': ['ZScoreNormalization'], 'use_mask_for_norm': [True], 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'architecture': {'network_class_name': 'dynamic_network_architectures.architectures.unet.PlainConvUNet', 'arch_kwargs': {'n_stages': 6, 'features_per_stage': [32, 64, 128, 256, 320, 320], 'conv_op': 'torch.nn.modules.conv.Conv3d', 'kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]], 'strides': [[1, 1, 1], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]], 'n_conv_per_stage': [2, 2, 2, 2, 2, 2], 'n_conv_per_stage_decoder': [2, 2, 2, 2, 2], 'conv_bias': True, 'norm_op': 'torch.nn.modules.instancenorm.InstanceNorm3d', 'norm_op_kwargs': {'eps': 1e-05, 'affine': True}, 'dropout_op': None, 'dropout_op_kwargs': None, 'nonlin': 'torch.nn.LeakyReLU', 'nonlin_kwargs': {'inplace': True}}, '_kw_requires_import': ['conv_op', 'norm_op', 'dropout_op', 'nonlin']}, 'batch_dice': False}

Preprocessing cases: 100%|██████████| 866/866 [06:41<00:00,  2.16it/s]

In [25]:
RUN_FINGERPRINT_AND_PLAN_ONLY = True

if RUN_FINGERPRINT_AND_PLAN_ONLY:
    pipe.plan_and_preprocess(layout, verify=True, no_preprocess=True, num_processes=[4])
else:
    print("Set RUN_FINGERPRINT_AND_PLAN_ONLY=True to verify data and inspect default 3d_fullres patch size without preprocessing.")

/home/rbielski/miniconda3/envs/tf_310/bin/nnUNetv2_plan_and_preprocess -d 701 --verify_dataset_integrity --no_pp -c 3d_fullres -np 4
Fingerprint extraction...
Dataset701_ARC_ATLAS_TrainV4Native
Using <class 'nnunetv2.imageio.simpleitk_reader_writer.SimpleITKIO'> as reader/writer

####################
verify_dataset_integrity Done.
If you didn't see any error messages then your dataset is most likely OK!
####################

Experiment planning...

############################
INFO: You are using the old nnU-Net default planner. We have updated our recommendations. Please consider using those instead! Read more here: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/resenc_presets.md
############################

Dropping 3d_lowres config because the image size difference to 3d_fullres is too small. 3d_fullres: [156. 186. 148.], 3d_lowres: [156, 186, 148]
2D U-Net configuration:
{'data_identifier': 'nnUNetPlans_2d', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 106, 'patch_size': (np.int64(192), np.int64(160)), 'median_image_size_in_voxels': array([186., 148.]), 'spacing': array([1., 1.]), 'normalization_schemes': ['ZScoreNormalization'], 'use_mask_for_norm': [True], 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'architecture': {'network_class_name': 'dynamic_network_architectures.architectures.unet.PlainConvUNet', 'arch_kwargs': {'n_stages': 6, 'features_per_stage': (32, 64, 128, 256, 512, 512), 'conv_op': 'torch.nn.modules.conv.Conv2d', 'kernel_sizes': ((3, 3), (3, 3), (3, 3), (3, 3), (3, 3), (3, 3)), 'strides': ((1, 1), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2)), 'n_conv_per_stage': (2, 2, 2, 2, 2, 2), 'n_conv_per_stage_decoder': (2, 2, 2, 2, 2), 'conv_bias': True, 'norm_op': 'torch.nn.modules.instancenorm.InstanceNorm2d', 'norm_op_kwargs': {'eps': 1e-05, 'affine': True}, 'dropout_op': None, 'dropout_op_kwargs': None, 'nonlin': 'torch.nn.LeakyReLU', 'nonlin_kwargs': {'inplace': True}}, '_kw_requires_import': ('conv_op', 'norm_op', 'dropout_op', 'nonlin')}, 'batch_dice': True}

Using <class 'nnunetv2.imageio.simpleitk_reader_writer.SimpleITKIO'> as reader/writer
3D fullres U-Net configuration:
{'data_identifier': 'nnUNetPlans_3d_fullres', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 2, 'patch_size': (np.int64(128), np.int64(160), np.int64(112)), 'median_image_size_in_voxels': array([156., 186., 148.]), 'spacing': array([1., 1., 1.]), 'normalization_schemes': ['ZScoreNormalization'], 'use_mask_for_norm': [True], 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'architecture': {'network_class_name': 'dynamic_network_architectures.architectures.unet.PlainConvUNet', 'arch_kwargs': {'n_stages': 6, 'features_per_stage': (32, 64, 128, 256, 320, 320), 'conv_op': 'torch.nn.modules.conv.Conv3d', 'kernel_sizes': ((3, 3, 3), (3, 3, 3), (3, 3, 3), (3, 3, 3), (3, 3, 3), (3, 3, 3)), 'strides': ((1, 1, 1), (2, 2, 2), (2, 2, 2), (2, 2, 2), (2, 2, 2), (2, 2, 1)), 'n_conv_per_stage': (2, 2, 2, 2, 2, 2), 'n_conv_per_stage_decoder': (2, 2, 2, 2, 2), 'conv_bias': True, 'norm_op': 'torch.nn.modules.instancenorm.InstanceNorm3d', 'norm_op_kwargs': {'eps': 1e-05, 'affine': True}, 'dropout_op': None, 'dropout_op_kwargs': None, 'nonlin': 'torch.nn.LeakyReLU', 'nonlin_kwargs': {'inplace': True}}, '_kw_requires_import': ('conv_op', 'norm_op', 'dropout_op', 'nonlin')}, 'batch_dice': False}

Plans were saved to /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train/nnunet_view/nnUNet_preprocessed/Dataset701_ARC_ATLAS_TrainV4Native/nnUNetPlans.json

## 5. Train Five Native-Split Folds

In [26]:
RUN_TRAINING = True
TRAIN_FOLDS = [0, 1, 2, 3, 4]

if RUN_TRAINING:
    for fold in TRAIN_FOLDS:
        pipe.train_fold(layout, fold, configuration="3d_fullres", plans=PLANS_NAME, save_npz=True)
else:
    print("Set RUN_TRAINING=True to train the five 3d_fullres folds.")

/home/rbielski/miniconda3/envs/tf_310/bin/nnUNetv2_train 701 3d_fullres 0 -p nnUNetPlans_24GB --npz
Using device: cuda:0

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

2026-05-01 15:32:33.557843: Using torch.compile...
2026-05-01 15:32:34.139784: do_dummy_2d_data_aug: False
2026-05-01 15:32:34.141302: Using splits from existing split file: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train/nnunet_view/nnUNet_preprocessed/Dataset701_ARC_ATLAS_TrainV4Native/splits_final.json
2026-05-01 15:32:34.141662: The split file contains 5 splits.
2026-05-01 15:32:34.141701: Desired fold for training: 0
2026-05-01 15:32:34.141727: This split has 692 training and 174 validation cases.
using pin_memory on device 0
using pin_memory on device 0

This is the configuration used by this training:
Configuration name: 3d_fullres
 {'data_identifier': 'nnUNetPlans_24GB_3d_fullres', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 3, 'patch_size': [160, 192, 160], 'median_image_size_in_voxels': [156.0, 186.0, 148.0], 'spacing': [1.0, 1.0, 1.0], 'normalization_schemes': ['ZScoreNormalization'], 'use_mask_for_norm': [True], 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'architecture': {'network_class_name': 'dynamic_network_architectures.architectures.unet.PlainConvUNet', 'arch_kwargs': {'n_stages': 6, 'features_per_stage': [32, 64, 128, 256, 320, 320], 'conv_op': 'torch.nn.modules.conv.Conv3d', 'kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]], 'strides': [[1, 1, 1], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]], 'n_conv_per_stage': [2, 2, 2, 2, 2, 2], 'n_conv_per_stage_decoder': [2, 2, 2, 2, 2], 'conv_bias': True, 'norm_op': 'torch.nn.modules.instancenorm.InstanceNorm3d', 'norm_op_kwargs': {'eps': 1e-05, 'affine': True}, 'dropout_op': None, 'dropout_op_kwargs': None, 'nonlin': 'torch.nn.LeakyReLU', 'nonlin_kwargs': {'inplace': True}}, '_kw_requires_import': ['conv_op', 'norm_op', 'dropout_op', 'nonlin']}, 'batch_dice': False}

These are the global plan.json settings:
 {'dataset_name': 'Dataset701_ARC_ATLAS_TrainV4Native', 'plans_name': 'nnUNetPlans_24GB', 'original_median_spacing_after_transp': [1.0, 1.0, 1.0], 'original_median_shape_after_transp': [156, 186, 148], 'image_reader_writer': 'SimpleITKIO', 'transpose_forward': [0, 1, 2], 'transpose_backward': [0, 1, 2], 'experiment_planner_used': 'ExperimentPlanner', 'label_manager': 'LabelManager', 'foreground_intensity_properties_per_channel': {'0': {'max': 1.0, 'mean': 0.5944083260038019, 'median': 0.6268383264541626, 'min': 0.0, 'percentile_00_5': 0.0, 'percentile_99_5': 1.0, 'std': 0.22091978786091068}}}

2026-05-01 15:32:36.187607: Unable to plot network architecture: nnUNet_compile is enabled!
2026-05-01 15:32:36.197936:
2026-05-01 15:32:36.198017: Epoch 0
2026-05-01 15:32:36.198454: Current learning rate: 0.01
2026-05-01 15:34:55.935162: train_loss 0.0132
2026-05-01 15:34:55.935297: val_loss -0.1361
2026-05-01 15:34:55.935345: Pseudo dice [np.float32(0.2989)]
2026-05-01 15:34:55.935398: Epoch time: 139.74 s
2026-05-01 15:34:55.935440: Yayy! New best EMA pseudo Dice: 0.2989000082015991
2026-05-01 15:34:56.771466:
2026-05-01 15:34:56.771541: Epoch 1
2026-05-01 15:34:56.771598: Current learning rate: 0.00999
2026-05-01 15:36:29.826136: train_loss -0.1259
2026-05-01 15:36:29.826263: val_loss -0.1967
2026-05-01 15:36:29.826327: Pseudo dice [np.float32(0.408)]
2026-05-01 15:36:29.826393: Epoch time: 93.06 s
2026-05-01 15:36:29.826452: Yayy! New best EMA pseudo Dice: 0.30979999899864197
2026-05-01 15:36:30.947153:
2026-05-01 15:36:30.947280: Epoch 2
2026-05-01 15:36:30.947358: Current learning rate: 0.00998
2026-05-01 15:38:04.143187: train_loss -0.1833
2026-05-01 15:38:04.143340: val_loss -0.2051
2026-05-01 15:38:04.143388: Pseudo dice [np.float32(0.4183)]
2026-05-01 15:38:04.143445: Epoch time: 93.2 s
2026-05-01 15:38:04.143488: Yayy! New best EMA pseudo Dice: 0.3206000030040741
2026-05-01 15:38:05.289767:
2026-05-01 15:38:05.289901: Epoch 3
2026-05-01 15:38:05.289961: Current learning rate: 0.00997
2026-05-01 15:39:38.449039: train_loss -0.1923
2026-05-01 15:39:38.449171: val_loss -0.2568
2026-05-01 15:39:38.449220: Pseudo dice [np.float32(0.4167)]
2026-05-01 15:39:38.449274: Epoch time: 93.16 s
2026-05-01 15:39:38.449318: Yayy! New best EMA pseudo Dice: 0.3301999866962433
2026-05-01 15:39:39.576984:
2026-05-01 15:39:39.577067: Epoch 4
2026-05-01 15:39:39.577121: Current learning rate: 0.00996
2026-05-01 15:41:12.786041: train_loss -0.2144
2026-05-01 15:41:12.786241: val_loss -0.2052
2026-05-01 15:41:12.786303: Pseudo dice [np.float32(0.4169)]
2026-05-01 15:41:12.786366: Epoch time: 93.21 s
2026-05-01 15:41:12.786411: Yayy! New best EMA pseudo Dice: 0.33889999985694885
2026-05-01 15:41:13.921395:
2026-05-01 15:41:13.921536: Epoch 5
2026-05-01 15:41:13.921601: Current learning rate: 0.00995
2026-05-01 15:42:47.028096: train_loss -0.2552
2026-05-01 15:42:47.028237: val_loss -0.218
2026-05-01 15:42:47.028285: Pseudo dice [np.float32(0.4627)]
2026-05-01 15:42:47.028367: Epoch time: 93.11 s
2026-05-01 15:42:47.028458: Yayy! New best EMA pseudo Dice: 0.3513000011444092
2026-05-01 15:42:48.147360:
2026-05-01 15:42:48.147503: Epoch 6
2026-05-01 15:42:48.147563: Current learning rate: 0.00995
2026-05-01 15:44:21.304595: train_loss -0.2084
2026-05-01 15:44:21.304794: val_loss -0.2732
2026-05-01 15:44:21.304888: Pseudo dice [np.float32(0.4769)]
2026-05-01 15:44:21.304956: Epoch time: 93.16 s
2026-05-01 15:44:21.305008: Yayy! New best EMA pseudo Dice: 0.36390000581741333
2026-05-01 15:44:22.427219:
2026-05-01 15:44:22.427451: Epoch 7
2026-05-01 15:44:22.427513: Current learning rate: 0.00994
2026-05-01 15:45:55.597532: train_loss -0.2441
2026-05-01 15:45:55.597717: val_loss -0.2648
2026-05-01 15:45:55.597853: Pseudo dice [np.float32(0.3964)]
2026-05-01 15:45:55.597913: Epoch time: 93.17 s
2026-05-01 15:45:55.597957: Yayy! New best EMA pseudo Dice: 0.3671000003814697
2026-05-01 15:45:56.730507:
2026-05-01 15:45:56.730616: Epoch 8
2026-05-01 15:45:56.730682: Current learning rate: 0.00993
2026-05-01 15:47:29.933109: train_loss -0.2725
2026-05-01 15:47:29.933316: val_loss -0.2417
2026-05-01 15:47:29.933388: Pseudo dice [np.float32(0.4614)]
2026-05-01 15:47:29.933530: Epoch time: 93.2 s
2026-05-01 15:47:29.933630: Yayy! New best EMA pseudo Dice: 0.3765000104904175
2026-05-01 15:47:31.090271:
2026-05-01 15:47:31.090413: Epoch 9
2026-05-01 15:47:31.090503: Current learning rate: 0.00992
2026-05-01 15:49:04.289270: train_loss -0.247
2026-05-01 15:49:04.289418: val_loss -0.3201
2026-05-01 15:49:04.289503: Pseudo dice [np.float32(0.475)]
2026-05-01 15:49:04.289596: Epoch time: 93.2 s
2026-05-01 15:49:04.289642: Yayy! New best EMA pseudo Dice: 0.3864000141620636
2026-05-01 15:49:05.416591:
2026-05-01 15:49:05.416811: Epoch 10
2026-05-01 15:49:05.416894: Current learning rate: 0.00991
2026-05-01 15:50:38.637022: train_loss -0.2809
2026-05-01 15:50:38.637205: val_loss -0.2625
2026-05-01 15:50:38.637266: Pseudo dice [np.float32(0.4699)]
2026-05-01 15:50:38.637330: Epoch time: 93.22 s
2026-05-01 15:50:38.637376: Yayy! New best EMA pseudo Dice: 0.39469999074935913
2026-05-01 15:50:40.236414:
2026-05-01 15:50:40.236680: Epoch 11
2026-05-01 15:50:40.236790: Current learning rate: 0.0099
2026-05-01 15:52:13.470386: train_loss -0.2945
2026-05-01 15:52:13.470627: val_loss -0.3019
2026-05-01 15:52:13.470699: Pseudo dice [np.float32(0.4672)]
2026-05-01 15:52:13.470767: Epoch time: 93.23 s
2026-05-01 15:52:13.470809: Yayy! New best EMA pseudo Dice: 0.4020000100135803
2026-05-01 15:52:14.597789:
2026-05-01 15:52:14.597922: Epoch 12
2026-05-01 15:52:14.597984: Current learning rate: 0.00989
2026-05-01 15:53:47.746428: train_loss -0.2536
2026-05-01 15:53:47.746591: val_loss -0.266
2026-05-01 15:53:47.746653: Pseudo dice [np.float32(0.4684)]
2026-05-01 15:53:47.746720: Epoch time: 93.15 s
2026-05-01 15:53:47.746765: Yayy! New best EMA pseudo Dice: 0.40860000252723694
2026-05-01 15:53:48.877114:
2026-05-01 15:53:48.877237: Epoch 13
2026-05-01 15:53:48.877296: Current learning rate: 0.00988
2026-05-01 15:55:22.088653: train_loss -0.2689
2026-05-01 15:55:22.088846: val_loss -0.3078
2026-05-01 15:55:22.088909: Pseudo dice [np.float32(0.5171)]
2026-05-01 15:55:22.088966: Epoch time: 93.21 s
2026-05-01 15:55:22.089009: Yayy! New best EMA pseudo Dice: 0.4194999933242798
2026-05-01 15:55:23.213009:
2026-05-01 15:55:23.213097: Epoch 14
2026-05-01 15:55:23.213162: Current learning rate: 0.00987
2026-05-01 15:56:56.418300: train_loss -0.2742
2026-05-01 15:56:56.418431: val_loss -0.2665
2026-05-01 15:56:56.418487: Pseudo dice [np.float32(0.4447)]
2026-05-01 15:56:56.418542: Epoch time: 93.21 s
2026-05-01 15:56:56.418587: Yayy! New best EMA pseudo Dice: 0.421999990940094
2026-05-01 15:56:57.555723:
2026-05-01 15:56:57.555955: Epoch 15
2026-05-01 15:56:57.556049: Current learning rate: 0.00986
2026-05-01 15:58:30.737684: train_loss -0.3068
2026-05-01 15:58:30.737831: val_loss -0.2759
2026-05-01 15:58:30.737879: Pseudo dice [np.float32(0.4284)]
2026-05-01 15:58:30.737934: Epoch time: 93.18 s
2026-05-01 15:58:30.737977: Yayy! New best EMA pseudo Dice: 0.42260000109672546
2026-05-01 15:58:31.873468:
2026-05-01 15:58:31.873552: Epoch 16
2026-05-01 15:58:31.873607: Current learning rate: 0.00986
2026-05-01 16:00:05.036613: train_loss -0.2813
2026-05-01 16:00:05.036795: val_loss -0.2851
2026-05-01 16:00:05.036854: Pseudo dice [np.float32(0.4236)]
2026-05-01 16:00:05.036914: Epoch time: 93.16 s
2026-05-01 16:00:05.036960: Yayy! New best EMA pseudo Dice: 0.4226999878883362
2026-05-01 16:00:06.173653:
2026-05-01 16:00:06.173793: Epoch 17
2026-05-01 16:00:06.173854: Current learning rate: 0.00985
2026-05-01 16:01:39.467939: train_loss -0.3068
2026-05-01 16:01:39.468115: val_loss -0.2774
2026-05-01 16:01:39.468186: Pseudo dice [np.float32(0.4753)]
2026-05-01 16:01:39.468248: Epoch time: 93.3 s
2026-05-01 16:01:39.468291: Yayy! New best EMA pseudo Dice: 0.42800000309944153
2026-05-01 16:01:40.611600:
2026-05-01 16:01:40.611726: Epoch 18
2026-05-01 16:01:40.611787: Current learning rate: 0.00984
2026-05-01 16:03:13.810106: train_loss -0.299
2026-05-01 16:03:13.810262: val_loss -0.2729
2026-05-01 16:03:13.810346: Pseudo dice [np.float32(0.4459)]
2026-05-01 16:03:13.810408: Epoch time: 93.2 s
2026-05-01 16:03:13.810492: Yayy! New best EMA pseudo Dice: 0.42980000376701355
2026-05-01 16:03:14.941638:
2026-05-01 16:03:14.941750: Epoch 19
2026-05-01 16:03:14.941812: Current learning rate: 0.00983
2026-05-01 16:04:48.119695: train_loss -0.2924
2026-05-01 16:04:48.119876: val_loss -0.3427
2026-05-01 16:04:48.119930: Pseudo dice [np.float32(0.5405)]
2026-05-01 16:04:48.119987: Epoch time: 93.18 s
2026-05-01 16:04:48.120147: Yayy! New best EMA pseudo Dice: 0.4408000111579895
2026-05-01 16:04:49.262285:
2026-05-01 16:04:49.262422: Epoch 20
2026-05-01 16:04:49.262478: Current learning rate: 0.00982
2026-05-01 16:06:22.457256: train_loss -0.3149
2026-05-01 16:06:22.457425: val_loss -0.3115
2026-05-01 16:06:22.457479: Pseudo dice [np.float32(0.4955)]
2026-05-01 16:06:22.457538: Epoch time: 93.2 s
2026-05-01 16:06:22.457582: Yayy! New best EMA pseudo Dice: 0.4462999999523163
2026-05-01 16:06:23.613815:
2026-05-01 16:06:23.613930: Epoch 21
2026-05-01 16:06:23.613990: Current learning rate: 0.00981
2026-05-01 16:07:56.809599: train_loss -0.3267
2026-05-01 16:07:56.809732: val_loss -0.2702
2026-05-01 16:07:56.809782: Pseudo dice [np.float32(0.4304)]
2026-05-01 16:07:56.809844: Epoch time: 93.2 s
2026-05-01 16:07:57.518419:
2026-05-01 16:07:57.518677: Epoch 22
2026-05-01 16:07:57.518748: Current learning rate: 0.0098
2026-05-01 16:09:30.751737: train_loss -0.3248
2026-05-01 16:09:30.751877: val_loss -0.2703
2026-05-01 16:09:30.751925: Pseudo dice [np.float32(0.3688)]
2026-05-01 16:09:30.751987: Epoch time: 93.23 s
2026-05-01 16:09:31.465620:
2026-05-01 16:09:31.465756: Epoch 23
2026-05-01 16:09:31.465814: Current learning rate: 0.00979
2026-05-01 16:11:04.657177: train_loss -0.2981
2026-05-01 16:11:04.657308: val_loss -0.3018
2026-05-01 16:11:04.657360: Pseudo dice [np.float32(0.4091)]
2026-05-01 16:11:04.657416: Epoch time: 93.19 s
2026-05-01 16:11:05.362435:
2026-05-01 16:11:05.362597: Epoch 24
2026-05-01 16:11:05.362662: Current learning rate: 0.00978
2026-05-01 16:12:38.573208: train_loss -0.3194
2026-05-01 16:12:38.573339: val_loss -0.3294
2026-05-01 16:12:38.573390: Pseudo dice [np.float32(0.4203)]
2026-05-01 16:12:38.573467: Epoch time: 93.21 s
2026-05-01 16:12:39.286363:
2026-05-01 16:12:39.286641: Epoch 25
2026-05-01 16:12:39.286747: Current learning rate: 0.00977
2026-05-01 16:14:12.487063: train_loss -0.3213
2026-05-01 16:14:12.487196: val_loss -0.317
2026-05-01 16:14:12.487257: Pseudo dice [np.float32(0.4475)]
2026-05-01 16:14:12.487323: Epoch time: 93.2 s
2026-05-01 16:14:13.194665:
2026-05-01 16:14:13.194752: Epoch 26
2026-05-01 16:14:13.194827: Current learning rate: 0.00977
2026-05-01 16:15:46.388923: train_loss -0.321
2026-05-01 16:15:46.389073: val_loss -0.2426
2026-05-01 16:15:46.389129: Pseudo dice [np.float32(0.3554)]
2026-05-01 16:15:46.389190: Epoch time: 93.2 s
2026-05-01 16:15:47.105810:
2026-05-01 16:15:47.105973: Epoch 27
2026-05-01 16:15:47.106034: Current learning rate: 0.00976
2026-05-01 16:17:20.389412: train_loss -0.3069
2026-05-01 16:17:20.389564: val_loss -0.3039
2026-05-01 16:17:20.389621: Pseudo dice [np.float32(0.5054)]
2026-05-01 16:17:20.389748: Epoch time: 93.28 s
2026-05-01 16:17:21.101516:
2026-05-01 16:17:21.101594: Epoch 28
2026-05-01 16:17:21.101651: Current learning rate: 0.00975
2026-05-01 16:18:54.324229: train_loss -0.3416
2026-05-01 16:18:54.324367: val_loss -0.3025
2026-05-01 16:18:54.324433: Pseudo dice [np.float32(0.4261)]
2026-05-01 16:18:54.324502: Epoch time: 93.22 s
2026-05-01 16:18:55.621056:
2026-05-01 16:18:55.621225: Epoch 29
2026-05-01 16:18:55.621293: Current learning rate: 0.00974
2026-05-01 16:20:28.876489: train_loss -0.3346
2026-05-01 16:20:28.876638: val_loss -0.3654
2026-05-01 16:20:28.876699: Pseudo dice [np.float32(0.5738)]
2026-05-01 16:20:28.876759: Epoch time: 93.26 s
2026-05-01 16:20:28.876804: Yayy! New best EMA pseudo Dice: 0.44760000705718994
2026-05-01 16:20:30.032414:
2026-05-01 16:20:30.032657: Epoch 30
2026-05-01 16:20:30.032760: Current learning rate: 0.00973
2026-05-01 16:22:03.229394: train_loss -0.336
2026-05-01 16:22:03.229545: val_loss -0.3429
2026-05-01 16:22:03.229597: Pseudo dice [np.float32(0.5082)]
2026-05-01 16:22:03.229654: Epoch time: 93.2 s
2026-05-01 16:22:03.229707: Yayy! New best EMA pseudo Dice: 0.4535999894142151
2026-05-01 16:22:04.378496:
2026-05-01 16:22:04.378742: Epoch 31
2026-05-01 16:22:04.378853: Current learning rate: 0.00972
2026-05-01 16:23:37.728312: train_loss -0.3386
2026-05-01 16:23:37.728478: val_loss -0.271
2026-05-01 16:23:37.728539: Pseudo dice [np.float32(0.4475)]
2026-05-01 16:23:37.728601: Epoch time: 93.35 s
2026-05-01 16:23:38.442407:
2026-05-01 16:23:38.442525: Epoch 32
2026-05-01 16:23:38.442584: Current learning rate: 0.00971
2026-05-01 16:25:11.712301: train_loss -0.3282
2026-05-01 16:25:11.712440: val_loss -0.31
2026-05-01 16:25:11.712488: Pseudo dice [np.float32(0.5388)]
2026-05-01 16:25:11.712541: Epoch time: 93.27 s
2026-05-01 16:25:11.712585: Yayy! New best EMA pseudo Dice: 0.46160000562667847
2026-05-01 16:25:12.865060:
2026-05-01 16:25:12.865216: Epoch 33
2026-05-01 16:25:12.865286: Current learning rate: 0.0097
2026-05-01 16:26:46.086537: train_loss -0.3197
2026-05-01 16:26:46.086705: val_loss -0.3119
2026-05-01 16:26:46.086766: Pseudo dice [np.float32(0.4594)]
2026-05-01 16:26:46.086825: Epoch time: 93.22 s
2026-05-01 16:26:46.813020:
2026-05-01 16:26:46.813172: Epoch 34
2026-05-01 16:26:46.813234: Current learning rate: 0.00969
2026-05-01 16:28:20.045634: train_loss -0.3115
2026-05-01 16:28:20.045793: val_loss -0.2983
2026-05-01 16:28:20.045843: Pseudo dice [np.float32(0.4353)]
2026-05-01 16:28:20.045902: Epoch time: 93.23 s
2026-05-01 16:28:20.777341:
2026-05-01 16:28:20.777427: Epoch 35
2026-05-01 16:28:20.777483: Current learning rate: 0.00968
2026-05-01 16:29:54.105315: train_loss -0.342
2026-05-01 16:29:54.105467: val_loss -0.306
2026-05-01 16:29:54.105518: Pseudo dice [np.float32(0.5062)]
2026-05-01 16:29:54.105575: Epoch time: 93.33 s
2026-05-01 16:29:54.105658: Yayy! New best EMA pseudo Dice: 0.4634999930858612
2026-05-01 16:29:55.254861:
2026-05-01 16:29:55.254977: Epoch 36
2026-05-01 16:29:55.255057: Current learning rate: 0.00968
2026-05-01 16:31:28.544437: train_loss -0.3176
2026-05-01 16:31:28.544574: val_loss -0.2949
2026-05-01 16:31:28.544638: Pseudo dice [np.float32(0.4364)]
2026-05-01 16:31:28.544713: Epoch time: 93.29 s
2026-05-01 16:31:29.268943:
2026-05-01 16:31:29.269056: Epoch 37
2026-05-01 16:31:29.269127: Current learning rate: 0.00967
2026-05-01 16:33:02.501406: train_loss -0.3482
2026-05-01 16:33:02.501614: val_loss -0.3257
2026-05-01 16:33:02.501686: Pseudo dice [np.float32(0.494)]
2026-05-01 16:33:02.501752: Epoch time: 93.23 s
2026-05-01 16:33:02.501796: Yayy! New best EMA pseudo Dice: 0.4641000032424927
2026-05-01 16:33:03.661827:
2026-05-01 16:33:03.662061: Epoch 38
2026-05-01 16:33:03.662140: Current learning rate: 0.00966
2026-05-01 16:34:36.909853: train_loss -0.362
2026-05-01 16:34:36.909998: val_loss -0.3899
2026-05-01 16:34:36.910056: Pseudo dice [np.float32(0.5722)]
2026-05-01 16:34:36.910114: Epoch time: 93.25 s
2026-05-01 16:34:36.910160: Yayy! New best EMA pseudo Dice: 0.4749000072479248
2026-05-01 16:34:38.066487:
2026-05-01 16:34:38.066653: Epoch 39
2026-05-01 16:34:38.066756: Current learning rate: 0.00965
2026-05-01 16:36:11.346420: train_loss -0.3571
2026-05-01 16:36:11.346641: val_loss -0.3347
2026-05-01 16:36:11.346715: Pseudo dice [np.float32(0.558)]
2026-05-01 16:36:11.346779: Epoch time: 93.28 s
2026-05-01 16:36:11.346823: Yayy! New best EMA pseudo Dice: 0.4832000136375427
2026-05-01 16:36:12.501153:
2026-05-01 16:36:12.501281: Epoch 40
2026-05-01 16:36:12.501337: Current learning rate: 0.00964
2026-05-01 16:37:45.834788: train_loss -0.3455
2026-05-01 16:37:45.834908: val_loss -0.275
2026-05-01 16:37:45.834958: Pseudo dice [np.float32(0.462)]
2026-05-01 16:37:45.835012: Epoch time: 93.33 s
2026-05-01 16:37:46.568901:
2026-05-01 16:37:46.569048: Epoch 41
2026-05-01 16:37:46.569109: Current learning rate: 0.00963
2026-05-01 16:39:19.830786: train_loss -0.3384
2026-05-01 16:39:19.830923: val_loss -0.3547
2026-05-01 16:39:19.830972: Pseudo dice [np.float32(0.5207)]
2026-05-01 16:39:19.831028: Epoch time: 93.26 s
2026-05-01 16:39:19.831075: Yayy! New best EMA pseudo Dice: 0.48510000109672546
2026-05-01 16:39:20.970714:
2026-05-01 16:39:20.970942: Epoch 42
2026-05-01 16:39:20.971002: Current learning rate: 0.00962
2026-05-01 16:40:54.217753: train_loss -0.3377
2026-05-01 16:40:54.217885: val_loss -0.3471
2026-05-01 16:40:54.217937: Pseudo dice [np.float32(0.4815)]
2026-05-01 16:40:54.217995: Epoch time: 93.25 s
2026-05-01 16:40:54.930866:
2026-05-01 16:40:54.930983: Epoch 43
2026-05-01 16:40:54.931044: Current learning rate: 0.00961
2026-05-01 16:42:28.297732: train_loss -0.343

## 6. Leak-Free CV Prediction, Postprocess, Evaluate

In [27]:
RUN_CV_PREDICT = True

if RUN_CV_PREDICT:
    pipe.predict_cv_folds(layout, CV_ROOT, configuration="3d_fullres", plans=PLANS_NAME)
else:
    print("Set RUN_CV_PREDICT=True after all requested folds have checkpoints.")

/home/rbielski/miniconda3/envs/tf_310/bin/nnUNetv2_predict -i /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/nnunet_cv_predictions_native_split/fold_0_input -o /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/nnunet_cv_predictions_native_split/fold_0_pred -d 701 -c 3d_fullres -f 0 -p nnUNetPlans_24GB --save_probabilities

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

There are 174 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 174 cases that I would like to predict

Predicting case_0003_sub_062:
perform_everything_on_device: True

100%|██████████| 1/1 [00:01<00:00,  1.26s/it]
  0%|          | 0/1 [00:00<?, ?it/s]

sending off prediction to background worker for resampling and export
done with case_0003_sub_062

Predicting case_0008_sub_r031s032:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0008_sub_r031s032

Predicting case_0009_sub_m2277:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0009_sub_m2277

Predicting case_0019_sub_m2127:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0019_sub_m2127

Predicting case_0022_sub_r009s118:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0022_sub_r009s118

Predicting case_0028_sub_r023s014:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0028_sub_r023s014

Predicting case_0030_sub_r048s032:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0030_sub_r048s032

Predicting case_0031_sub_m2309:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0031_sub_m2309

Predicting case_0033_sub_r004s031:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0033_sub_r004s031

Predicting case_0034_sub_r010s024:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0034_sub_r010s024

Predicting case_0035_sub_r047s017:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0035_sub_r047s017

Predicting case_0045_sub_r040s028:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0045_sub_r040s028

Predicting case_0046_sub_r027s042:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0046_sub_r027s042

Predicting case_0050_sub_003:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0050_sub_003

Predicting case_0054_sub_m2173:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0054_sub_m2173

Predicting case_0061_sub_r018s008:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0061_sub_r018s008

Predicting case_0065_sub_m2143:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0065_sub_m2143

Predicting case_0068_sub_086:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0068_sub_086

Predicting case_0074_sub_r038s082:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0074_sub_r038s082

Predicting case_0075_sub_r011s001:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0075_sub_r011s001

Predicting case_0079_sub_m2270:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0079_sub_m2270

Predicting case_0082_sub_r047s037:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0082_sub_r047s037

Predicting case_0089_sub_r009s108:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0089_sub_r009s108

Predicting case_0090_sub_r009s014:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0090_sub_r009s014

Predicting case_0092_sub_r009s082:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0092_sub_r009s082

Predicting case_0093_sub_r010s027:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0093_sub_r010s027

Predicting case_0094_sub_r002s011:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0094_sub_r002s011

Predicting case_0096_sub_r009s048:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0096_sub_r009s048

Predicting case_0103_sub_r010s003:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0103_sub_r010s003

Predicting case_0104_sub_m2035:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0104_sub_m2035

Predicting case_0108_sub_m2298:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0108_sub_m2298

Predicting case_0112_sub_m2051:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0112_sub_m2051

Predicting case_0115_sub_r009s073:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0115_sub_r009s073

Predicting case_0124_sub_r017s119:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.18it/s]

sending off prediction to background worker for resampling and export
done with case_0124_sub_r017s119

Predicting case_0126_sub_m2297:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0126_sub_m2297

Predicting case_0130_sub_r009s046:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0130_sub_r009s046

Predicting case_0131_sub_r001s027:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0131_sub_r001s027

Predicting case_0143_sub_r009s055:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0143_sub_r009s055

Predicting case_0154_sub_r047s041:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0154_sub_r047s041

Predicting case_0156_sub_m2184:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0156_sub_m2184

Predicting case_0165_sub_r009s117:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0165_sub_r009s117

Predicting case_0166_sub_r011s031:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0166_sub_r011s031

Predicting case_0170_sub_008:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0170_sub_008

Predicting case_0172_sub_r023s002:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0172_sub_r023s002

Predicting case_0181_sub_m2074:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0181_sub_m2074

Predicting case_0184_sub_r004s010:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0184_sub_r004s010

Predicting case_0189_sub_050:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0189_sub_050

Predicting case_0198_sub_r009s085:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0198_sub_r009s085

Predicting case_0202_sub_m2084:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0202_sub_m2084

Predicting case_0206_sub_r038s065:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0206_sub_r038s065

Predicting case_0207_sub_r009s114:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0207_sub_r009s114

Predicting case_0217_sub_r003s006:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0217_sub_r003s006

Predicting case_0228_sub_r014s002:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0228_sub_r014s002

Predicting case_0231_sub_r001s036:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0231_sub_r001s036

Predicting case_0237_sub_067:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0237_sub_067

Predicting case_0239_sub_m2195:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0239_sub_m2195

Predicting case_0247_sub_024:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0247_sub_024

Predicting case_0259_sub_m2185:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0259_sub_m2185

Predicting case_0260_sub_m2096:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0260_sub_m2096

Predicting case_0262_sub_r005s073:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0262_sub_r005s073

Predicting case_0267_sub_m2089:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0267_sub_m2089

Predicting case_0273_sub_r009s025:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0273_sub_r009s025

Predicting case_0284_sub_m2236:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0284_sub_m2236

Predicting case_0291_sub_090:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0291_sub_090

Predicting case_0295_sub_r015s001:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0295_sub_r015s001

Predicting case_0298_sub_r040s020:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0298_sub_r040s020

Predicting case_0302_sub_r001s004:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0302_sub_r001s004

Predicting case_0319_sub_r035s014:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0319_sub_r035s014

Predicting case_0321_sub_r046s006:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0321_sub_r046s006

Predicting case_0324_sub_r038s022:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0324_sub_r038s022

Predicting case_0332_sub_r019s008:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0332_sub_r019s008

Predicting case_0336_sub_r010s014:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0336_sub_r010s014

Predicting case_0339_sub_084:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0339_sub_084

Predicting case_0348_sub_r028s014:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0348_sub_r028s014

Predicting case_0356_sub_r009s124:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0356_sub_r009s124

Predicting case_0359_sub_r003s008:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0359_sub_r003s008

Predicting case_0370_sub_r009s015:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0370_sub_r009s015

Predicting case_0373_sub_m2181:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0373_sub_m2181

Predicting case_0379_sub_r040s011:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0379_sub_r040s011

Predicting case_0389_sub_r038s041:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0389_sub_r038s041

Predicting case_0390_sub_r009s040:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0390_sub_r009s040

Predicting case_0393_sub_m2209:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0393_sub_m2209

Predicting case_0405_sub_r009s061:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0405_sub_r009s061

Predicting case_0411_sub_r009s106:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0411_sub_r009s106

Predicting case_0415_sub_r010s009:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0415_sub_r010s009

Predicting case_0416_sub_034:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0416_sub_034

Predicting case_0421_sub_r038s010:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0421_sub_r038s010

Predicting case_0423_sub_r009s049:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0423_sub_r009s049

Predicting case_0424_sub_r048s022:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0424_sub_r048s022

Predicting case_0426_sub_r005s069:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0426_sub_r005s069

Predicting case_0433_sub_m2232:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0433_sub_m2232

Predicting case_0438_sub_r010s022:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0438_sub_r010s022

Predicting case_0459_sub_m2172:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0459_sub_m2172

Predicting case_0467_sub_r005s046:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0467_sub_r005s046

Predicting case_0471_sub_r004s024:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0471_sub_r004s024

Predicting case_0476_sub_007:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0476_sub_007

Predicting case_0485_sub_m2043:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0485_sub_m2043

Predicting case_0490_sub_m2207:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0490_sub_m2207

Predicting case_0491_sub_064:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0491_sub_064

Predicting case_0497_sub_r050s005:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.16it/s]

sending off prediction to background worker for resampling and export
done with case_0497_sub_r050s005

Predicting case_0498_sub_r024s002:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0498_sub_r024s002

Predicting case_0499_sub_r029s009:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0499_sub_r029s009

Predicting case_0529_sub_r038s023:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0529_sub_r038s023

Predicting case_0543_sub_r001s016:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0543_sub_r001s016

Predicting case_0545_sub_r038s081:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0545_sub_r038s081

Predicting case_0548_sub_r002s002:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0548_sub_r002s002

Predicting case_0549_sub_085:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0549_sub_085

Predicting case_0553_sub_r038s035:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0553_sub_r038s035

Predicting case_0555_sub_r010s023:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0555_sub_r010s023

Predicting case_0564_sub_092:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0564_sub_092

Predicting case_0566_sub_029:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0566_sub_029

Predicting case_0568_sub_m2175:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0568_sub_m2175

Predicting case_0573_sub_r038s024:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0573_sub_r038s024

Predicting case_0578_sub_r040s049:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0578_sub_r040s049

Predicting case_0583_sub_m2152:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0583_sub_m2152

Predicting case_0594_sub_r047s021:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0594_sub_r047s021

Predicting case_0597_sub_r002s003:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0597_sub_r002s003

Predicting case_0603_sub_r050s009:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0603_sub_r050s009

Predicting case_0608_sub_072:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0608_sub_072

Predicting case_0612_sub_r031s023:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0612_sub_r031s023

Predicting case_0613_sub_m2057:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0613_sub_m2057

Predicting case_0614_sub_r009s026:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0614_sub_r009s026

Predicting case_0616_sub_r001s028:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0616_sub_r001s028

Predicting case_0617_sub_r003s001:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0617_sub_r003s001

Predicting case_0636_sub_r028s002:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0636_sub_r028s002

Predicting case_0637_sub_r011s032:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0637_sub_r011s032

Predicting case_0647_sub_r002s006:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0647_sub_r002s006

Predicting case_0650_sub_r005s068:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0650_sub_r005s068

Predicting case_0654_sub_r015s016:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0654_sub_r015s016

Predicting case_0662_sub_r048s004:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0662_sub_r048s004

Predicting case_0663_sub_078:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0663_sub_078

Predicting case_0666_sub_104:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0666_sub_104

Predicting case_0675_sub_r040s074:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0675_sub_r040s074

Predicting case_0683_sub_r038s018:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0683_sub_r038s018

Predicting case_0691_sub_m2045:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0691_sub_m2045

Predicting case_0693_sub_r003s005:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0693_sub_r003s005

Predicting case_0697_sub_r009s077:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0697_sub_r009s077

Predicting case_0699_sub_m2116:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0699_sub_m2116

Predicting case_0703_sub_063:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0703_sub_063

Predicting case_0708_sub_r046s012:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0708_sub_r046s012

Predicting case_0717_sub_r010s005:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0717_sub_r010s005

Predicting case_0718_sub_r031s019:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0718_sub_r031s019

Predicting case_0721_sub_r027s017:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0721_sub_r027s017

Predicting case_0726_sub_r004s004:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0726_sub_r004s004

Predicting case_0727_sub_m2222:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0727_sub_m2222

Predicting case_0743_sub_087:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0743_sub_087

Predicting case_0745_sub_m2107:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0745_sub_m2107

Predicting case_0747_sub_r047s027:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0747_sub_r047s027

Predicting case_0766_sub_r039s003:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0766_sub_r039s003

Predicting case_0767_sub_075:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0767_sub_075

Predicting case_0769_sub_r038s071:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0769_sub_r038s071

Predicting case_0770_sub_r001s012:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0770_sub_r001s012

Predicting case_0771_sub_r009s045:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0771_sub_r009s045

Predicting case_0778_sub_059:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0778_sub_059

Predicting case_0780_sub_m2162:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0780_sub_m2162

Predicting case_0784_sub_r004s029:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0784_sub_r004s029

Predicting case_0785_sub_r047s038:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0785_sub_r047s038

Predicting case_0791_sub_m2304:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0791_sub_m2304

Predicting case_0800_sub_m2135:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0800_sub_m2135

Predicting case_0803_sub_r027s013:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0803_sub_r027s013

Predicting case_0806_sub_m2092:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0806_sub_m2092

Predicting case_0807_sub_r049s012:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0807_sub_r049s012

Predicting case_0809_sub_r034s006:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0809_sub_r034s006

Predicting case_0820_sub_m2240:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0820_sub_m2240

Predicting case_0827_sub_r047s010:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0827_sub_r047s010

Predicting case_0834_sub_r001s023:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0834_sub_r001s023

Predicting case_0835_sub_r009s122:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0835_sub_r009s122

Predicting case_0838_sub_r038s032:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0838_sub_r038s032

Predicting case_0843_sub_r031s037:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0843_sub_r031s037

Predicting case_0849_sub_m2075:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.19it/s]

sending off prediction to background worker for resampling and export
done with case_0849_sub_m2075

Predicting case_0853_sub_r027s047:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0853_sub_r027s047

Predicting case_0860_sub_r001s026:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0860_sub_r001s026

Predicting case_0862_sub_r004s014:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0862_sub_r004s014

Predicting case_0866_sub_r038s016:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0866_sub_r038s016
/home/rbielski/miniconda3/envs/tf_310/bin/nnUNetv2_predict -i /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/nnunet_cv_predictions_native_split/fold_1_input -o /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/nnunet_cv_predictions_native_split/fold_1_pred -d 701 -c 3d_fullres -f 1 -p nnUNetPlans_24GB --save_probabilities

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

There are 173 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 173 cases that I would like to predict

Predicting case_0006_sub_m2227:
perform_everything_on_device: True

100%|██████████| 1/1 [00:01<00:00,  1.26s/it]
  0%|          | 0/1 [00:00<?, ?it/s]

sending off prediction to background worker for resampling and export
done with case_0006_sub_m2227

Predicting case_0010_sub_r034s022:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0010_sub_r034s022

Predicting case_0013_sub_r001s029:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0013_sub_r001s029

Predicting case_0025_sub_r009s072:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0025_sub_r009s072

Predicting case_0029_sub_m2281:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0029_sub_m2281

Predicting case_0038_sub_r011s026:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0038_sub_r011s026

Predicting case_0040_sub_r009s087:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0040_sub_r009s087

Predicting case_0042_sub_r005s076:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0042_sub_r005s076

Predicting case_0047_sub_089:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0047_sub_089

Predicting case_0048_sub_r029s010:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0048_sub_r029s010

Predicting case_0055_sub_m2292:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0055_sub_m2292

Predicting case_0057_sub_r038s078:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0057_sub_r038s078

Predicting case_0069_sub_r040s063:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0069_sub_r040s063

Predicting case_0071_sub_m2066:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0071_sub_m2066

Predicting case_0073_sub_r011s021:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0073_sub_r011s021

Predicting case_0083_sub_m2226:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0083_sub_m2226

Predicting case_0088_sub_m2285:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0088_sub_m2285

Predicting case_0095_sub_077:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0095_sub_077

Predicting case_0100_sub_r009s041:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0100_sub_r009s041

Predicting case_0106_sub_r031s007:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0106_sub_r031s007

Predicting case_0114_sub_r050s015:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0114_sub_r050s015

Predicting case_0119_sub_m2034:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0119_sub_m2034

Predicting case_0120_sub_r031s016:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0120_sub_r031s016

Predicting case_0125_sub_r004s012:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0125_sub_r004s012

Predicting case_0128_sub_r027s048:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0128_sub_r027s048

Predicting case_0135_sub_r009s121:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0135_sub_r009s121

Predicting case_0138_sub_026:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0138_sub_026

Predicting case_0142_sub_016:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0142_sub_016

Predicting case_0144_sub_r040s016:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0144_sub_r040s016

Predicting case_0155_sub_r011s020:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0155_sub_r011s020

Predicting case_0159_sub_m2287:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.35it/s]

sending off prediction to background worker for resampling and export
done with case_0159_sub_m2287

Predicting case_0163_sub_r028s005:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0163_sub_r028s005

Predicting case_0174_sub_r024s008:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0174_sub_r024s008

Predicting case_0191_sub_009:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0191_sub_009

Predicting case_0192_sub_r034s007:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0192_sub_r034s007

Predicting case_0215_sub_r009s065:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0215_sub_r009s065

Predicting case_0225_sub_m2119:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0225_sub_m2119

Predicting case_0226_sub_r014s015:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0226_sub_r014s015

Predicting case_0229_sub_r042s033:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0229_sub_r042s033

Predicting case_0236_sub_m2104:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0236_sub_m2104

Predicting case_0238_sub_r009s029:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0238_sub_r009s029

Predicting case_0242_sub_r038s036:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0242_sub_r038s036

Predicting case_0243_sub_032:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0243_sub_032

Predicting case_0246_sub_r001s010:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0246_sub_r001s010

Predicting case_0252_sub_m2059:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0252_sub_m2059

Predicting case_0253_sub_r011s012:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0253_sub_r011s012

Predicting case_0264_sub_r009s095:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0264_sub_r009s095

Predicting case_0276_sub_019:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0276_sub_019

Predicting case_0277_sub_m2252:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0277_sub_m2252

Predicting case_0278_sub_r009s013:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0278_sub_r009s013

Predicting case_0280_sub_022:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0280_sub_022

Predicting case_0281_sub_r009s113:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0281_sub_r009s113

Predicting case_0282_sub_m2169:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0282_sub_m2169

Predicting case_0296_sub_r052s029:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0296_sub_r052s029

Predicting case_0305_sub_r024s005:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.33it/s]

sending off prediction to background worker for resampling and export
done with case_0305_sub_r024s005

Predicting case_0309_sub_r015s008:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0309_sub_r015s008

Predicting case_0320_sub_r009s022:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0320_sub_r009s022

Predicting case_0323_sub_r009s051:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0323_sub_r009s051

Predicting case_0328_sub_r042s015:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.32it/s]

sending off prediction to background worker for resampling and export
done with case_0328_sub_r042s015

Predicting case_0330_sub_r031s033:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0330_sub_r031s033

Predicting case_0331_sub_m2058:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0331_sub_m2058

Predicting case_0334_sub_r004s028:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0334_sub_r004s028

Predicting case_0337_sub_r003s009:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0337_sub_r003s009

Predicting case_0342_sub_r031s029:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0342_sub_r031s029

Predicting case_0344_sub_r034s010:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0344_sub_r034s010

Predicting case_0357_sub_r038s028:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0357_sub_r038s028

Predicting case_0362_sub_r011s002:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0362_sub_r011s002

Predicting case_0367_sub_r034s037:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0367_sub_r034s037

Predicting case_0375_sub_r009s096:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0375_sub_r009s096

Predicting case_0378_sub_m2278:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0378_sub_m2278

Predicting case_0380_sub_042:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0380_sub_042

Predicting case_0383_sub_m2177:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0383_sub_m2177

Predicting case_0387_sub_r010s013:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0387_sub_r010s013

Predicting case_0391_sub_r009s092:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0391_sub_r009s092

Predicting case_0392_sub_021:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0392_sub_021

Predicting case_0395_sub_r017s104:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0395_sub_r017s104

Predicting case_0399_sub_r034s040:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0399_sub_r034s040

Predicting case_0404_sub_r038s014:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0404_sub_r038s014

Predicting case_0406_sub_m2146:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0406_sub_m2146

Predicting case_0407_sub_m2046:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0407_sub_m2046

Predicting case_0414_sub_r031s017:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0414_sub_r031s017

Predicting case_0417_sub_r034s013:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0417_sub_r034s013

Predicting case_0422_sub_r029s003:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0422_sub_r029s003

Predicting case_0427_sub_m2088:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0427_sub_m2088

Predicting case_0434_sub_r038s007:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0434_sub_r038s007

Predicting case_0435_sub_043:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0435_sub_043

Predicting case_0439_sub_r042s023:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0439_sub_r042s023

Predicting case_0440_sub_r004s001:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0440_sub_r004s001

Predicting case_0445_sub_r004s016:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0445_sub_r004s016

Predicting case_0450_sub_r042s010:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0450_sub_r042s010

Predicting case_0455_sub_r001s013:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0455_sub_r001s013

Predicting case_0456_sub_r004s021:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0456_sub_r004s021

Predicting case_0458_sub_058:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0458_sub_058

Predicting case_0462_sub_m2210:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0462_sub_m2210

Predicting case_0463_sub_m2168:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0463_sub_m2168

Predicting case_0472_sub_r009s062:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0472_sub_r009s062

Predicting case_0473_sub_r052s026:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0473_sub_r052s026

Predicting case_0487_sub_r031s035:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0487_sub_r031s035

Predicting case_0493_sub_r002s004:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0493_sub_r002s004

Predicting case_0495_sub_r001s007:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0495_sub_r001s007

Predicting case_0500_sub_073:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0500_sub_073

Predicting case_0502_sub_m2086:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0502_sub_m2086

Predicting case_0504_sub_r048s038:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0504_sub_r048s038

Predicting case_0508_sub_r001s039:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0508_sub_r001s039

Predicting case_0514_sub_081:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0514_sub_081

Predicting case_0522_sub_r005s077:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.34it/s]

sending off prediction to background worker for resampling and export
done with case_0522_sub_r005s077

Predicting case_0531_sub_r015s010:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.34it/s]

sending off prediction to background worker for resampling and export
done with case_0531_sub_r015s010

Predicting case_0532_sub_r028s012:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.35it/s]

sending off prediction to background worker for resampling and export
done with case_0532_sub_r028s012

Predicting case_0534_sub_r004s025:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0534_sub_r004s025

Predicting case_0540_sub_m2262:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0540_sub_m2262

Predicting case_0541_sub_004:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0541_sub_004

Predicting case_0546_sub_r038s061:
perform_everything_on_device: True

100%|██████████| 2/2 [00:00<00:00,  3.59it/s]

sending off prediction to background worker for resampling and export
done with case_0546_sub_r038s061

Predicting case_0550_sub_m2049:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0550_sub_m2049

Predicting case_0552_sub_m2101:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0552_sub_m2101

Predicting case_0554_sub_r028s004:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0554_sub_r028s004

Predicting case_0556_sub_m2129:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0556_sub_m2129

Predicting case_0558_sub_r052s023:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0558_sub_r052s023

Predicting case_0561_sub_r047s046:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0561_sub_r047s046

Predicting case_0567_sub_r003s002:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0567_sub_r003s002

Predicting case_0575_sub_m2105:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0575_sub_m2105

Predicting case_0586_sub_r038s067:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0586_sub_r038s067

Predicting case_0588_sub_r011s030:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0588_sub_r011s030

Predicting case_0592_sub_r040s047:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0592_sub_r040s047

Predicting case_0596_sub_r004s018:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0596_sub_r004s018

Predicting case_0598_sub_r019s012:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0598_sub_r019s012

Predicting case_0600_sub_r009s016:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0600_sub_r009s016

Predicting case_0601_sub_r050s008:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0601_sub_r050s008

Predicting case_0602_sub_m2120:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0602_sub_m2120

Predicting case_0607_sub_m2037:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0607_sub_m2037

Predicting case_0611_sub_r028s009:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0611_sub_r028s009

Predicting case_0621_sub_r010s016:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0621_sub_r010s016

Predicting case_0623_sub_076:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0623_sub_076

Predicting case_0633_sub_r024s012:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0633_sub_r024s012

Predicting case_0644_sub_m2142:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0644_sub_m2142

Predicting case_0655_sub_r009s009:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0655_sub_r009s009

Predicting case_0659_sub_r027s023:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0659_sub_r027s023

Predicting case_0664_sub_001:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0664_sub_001

Predicting case_0670_sub_r018s012:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0670_sub_r018s012

Predicting case_0682_sub_060:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0682_sub_060

Predicting case_0684_sub_006:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0684_sub_006

Predicting case_0689_sub_r040s072:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0689_sub_r040s072

Predicting case_0695_sub_r011s025:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0695_sub_r011s025

Predicting case_0706_sub_m2176:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0706_sub_m2176

Predicting case_0731_sub_r017s117:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0731_sub_r017s117

Predicting case_0733_sub_r001s015:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0733_sub_r001s015

Predicting case_0734_sub_r005s081:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.35it/s]

sending off prediction to background worker for resampling and export
done with case_0734_sub_r005s081

Predicting case_0737_sub_r001s014:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0737_sub_r001s014

Predicting case_0738_sub_m2118:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0738_sub_m2118

Predicting case_0754_sub_r004s009:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.35it/s]

sending off prediction to background worker for resampling and export
done with case_0754_sub_r004s009

Predicting case_0759_sub_r042s003:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0759_sub_r042s003

Predicting case_0765_sub_r038s026:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0765_sub_r038s026

Predicting case_0773_sub_m2259:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0773_sub_m2259

Predicting case_0775_sub_r052s027:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0775_sub_r052s027

Predicting case_0776_sub_r038s006:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0776_sub_r038s006

Predicting case_0782_sub_018:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0782_sub_018

Predicting case_0787_sub_r038s057:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0787_sub_r038s057

Predicting case_0788_sub_m2095:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0788_sub_m2095

Predicting case_0789_sub_m2122:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0789_sub_m2122

Predicting case_0790_sub_r040s044:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0790_sub_r040s044

Predicting case_0795_sub_r034s033:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0795_sub_r034s033

Predicting case_0799_sub_r028s007:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.35it/s]

sending off prediction to background worker for resampling and export
done with case_0799_sub_r028s007

Predicting case_0812_sub_r009s050:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0812_sub_r009s050

Predicting case_0816_sub_095:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0816_sub_095

Predicting case_0817_sub_r009s024:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0817_sub_r009s024

Predicting case_0819_sub_r001s018:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0819_sub_r001s018

Predicting case_0826_sub_r049s011:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0826_sub_r049s011

Predicting case_0833_sub_r010s032:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0833_sub_r010s032

Predicting case_0841_sub_r028s026:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0841_sub_r028s026

Predicting case_0842_sub_m2069:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0842_sub_m2069

Predicting case_0850_sub_r009s125:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0850_sub_r009s125

Predicting case_0851_sub_r031s025:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0851_sub_r031s025

Predicting case_0855_sub_r042s029:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0855_sub_r042s029

Predicting case_0859_sub_m2215:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0859_sub_m2215
/home/rbielski/miniconda3/envs/tf_310/bin/nnUNetv2_predict -i /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/nnunet_cv_predictions_native_split/fold_2_input -o /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/nnunet_cv_predictions_native_split/fold_2_pred -d 701 -c 3d_fullres -f 2 -p nnUNetPlans_24GB --save_probabilities

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

There are 173 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 173 cases that I would like to predict

Predicting case_0011_sub_037:
perform_everything_on_device: True

100%|██████████| 1/1 [00:01<00:00,  1.26s/it]
  0%|          | 0/1 [00:00<?, ?it/s]

sending off prediction to background worker for resampling and export
done with case_0011_sub_037

Predicting case_0015_sub_r038s020:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0015_sub_r038s020

Predicting case_0017_sub_r019s009:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0017_sub_r019s009

Predicting case_0021_sub_r009s100:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0021_sub_r009s100

Predicting case_0026_sub_m2228:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0026_sub_m2228

Predicting case_0036_sub_r010s010:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0036_sub_r010s010

Predicting case_0037_sub_r009s110:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0037_sub_r009s110

Predicting case_0053_sub_m2147:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0053_sub_m2147

Predicting case_0058_sub_r047s015:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0058_sub_r047s015

Predicting case_0059_sub_r046s007:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0059_sub_r046s007

Predicting case_0060_sub_m2200:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0060_sub_m2200

Predicting case_0067_sub_r009s008:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0067_sub_r009s008

Predicting case_0070_sub_r048s035:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0070_sub_r048s035

Predicting case_0072_sub_r047s039:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0072_sub_r047s039

Predicting case_0077_sub_r009s030:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0077_sub_r009s030

Predicting case_0078_sub_r038s058:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0078_sub_r038s058

Predicting case_0080_sub_m2223:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0080_sub_m2223

Predicting case_0085_sub_m2134:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0085_sub_m2134

Predicting case_0087_sub_r028s011:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0087_sub_r028s011

Predicting case_0111_sub_r024s019:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0111_sub_r024s019

Predicting case_0116_sub_m2047:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0116_sub_m2047

Predicting case_0117_sub_m2211:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0117_sub_m2211

Predicting case_0121_sub_m2055:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0121_sub_m2055

Predicting case_0123_sub_m2115:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0123_sub_m2115

Predicting case_0129_sub_r005s074:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0129_sub_r005s074

Predicting case_0132_sub_r031s021:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0132_sub_r031s021

Predicting case_0141_sub_m2077:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0141_sub_m2077

Predicting case_0145_sub_r040s078:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0145_sub_r040s078

Predicting case_0146_sub_r009s057:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0146_sub_r009s057

Predicting case_0147_sub_m2220:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0147_sub_m2220

Predicting case_0149_sub_r009s105:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0149_sub_r009s105

Predicting case_0151_sub_066:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0151_sub_066

Predicting case_0157_sub_r010s019:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0157_sub_r010s019

Predicting case_0160_sub_r040s037:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0160_sub_r040s037

Predicting case_0167_sub_r003s012:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0167_sub_r003s012

Predicting case_0173_sub_m2279:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.18it/s]

sending off prediction to background worker for resampling and export
done with case_0173_sub_m2279

Predicting case_0187_sub_r044s002:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0187_sub_r044s002

Predicting case_0188_sub_r047s026:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0188_sub_r047s026

Predicting case_0195_sub_m2087:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0195_sub_m2087

Predicting case_0199_sub_m2212:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0199_sub_m2212

Predicting case_0203_sub_r040s008:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0203_sub_r040s008

Predicting case_0208_sub_r048s015:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.17it/s]

sending off prediction to background worker for resampling and export
done with case_0208_sub_r048s015

Predicting case_0214_sub_098:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0214_sub_098

Predicting case_0219_sub_r009s052:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0219_sub_r009s052

Predicting case_0221_sub_r004s037:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0221_sub_r004s037

Predicting case_0233_sub_r048s012:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0233_sub_r048s012

Predicting case_0235_sub_068:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0235_sub_068

Predicting case_0240_sub_r052s032:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0240_sub_r052s032

Predicting case_0244_sub_r004s027:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0244_sub_r004s027

Predicting case_0249_sub_r005s055:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0249_sub_r005s055

Predicting case_0257_sub_r009s090:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0257_sub_r009s090

Predicting case_0268_sub_r034s025:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0268_sub_r034s025

Predicting case_0270_sub_045:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0270_sub_045

Predicting case_0279_sub_r027s052:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0279_sub_r027s052

Predicting case_0283_sub_r049s005:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0283_sub_r049s005

Predicting case_0286_sub_r004s013:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0286_sub_r004s013

Predicting case_0290_sub_r048s014:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0290_sub_r048s014

Predicting case_0294_sub_r034s012:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0294_sub_r034s012

Predicting case_0307_sub_r003s007:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0307_sub_r003s007

Predicting case_0308_sub_m2234:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0308_sub_m2234

Predicting case_0310_sub_m2114:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0310_sub_m2114

Predicting case_0315_sub_r009s018:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0315_sub_r009s018

Predicting case_0316_sub_r050s006:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0316_sub_r050s006

Predicting case_0322_sub_049:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0322_sub_049

Predicting case_0325_sub_r004s008:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0325_sub_r004s008

Predicting case_0327_sub_r003s014:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0327_sub_r003s014

Predicting case_0338_sub_r005s048:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0338_sub_r005s048

Predicting case_0341_sub_r009s091:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0341_sub_r009s091

Predicting case_0345_sub_r048s037:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0345_sub_r048s037

Predicting case_0350_sub_r015s018:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0350_sub_r015s018

Predicting case_0351_sub_r024s003:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0351_sub_r024s003

Predicting case_0352_sub_r040s051:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0352_sub_r040s051

Predicting case_0353_sub_m2048:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0353_sub_m2048

Predicting case_0354_sub_r040s056:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0354_sub_r040s056

Predicting case_0363_sub_r009s084:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0363_sub_r009s084

Predicting case_0366_sub_r048s039:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0366_sub_r048s039

Predicting case_0374_sub_r011s028:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0374_sub_r011s028

Predicting case_0377_sub_r042s028:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0377_sub_r042s028

Predicting case_0388_sub_m2300:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0388_sub_m2300

Predicting case_0396_sub_r009s060:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0396_sub_r009s060

Predicting case_0400_sub_r001s008:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0400_sub_r001s008

Predicting case_0401_sub_r011s022:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0401_sub_r011s022

Predicting case_0403_sub_r048s002:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0403_sub_r048s002

Predicting case_0409_sub_r010s021:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0409_sub_r010s021

Predicting case_0410_sub_m2145:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0410_sub_m2145

Predicting case_0412_sub_r009s098:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0412_sub_r009s098

Predicting case_0418_sub_r035s003:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0418_sub_r035s003

Predicting case_0419_sub_r038s056:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0419_sub_r038s056

Predicting case_0420_sub_m2165:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0420_sub_m2165

Predicting case_0429_sub_r010s007:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0429_sub_r010s007

Predicting case_0436_sub_r040s076:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0436_sub_r040s076

Predicting case_0442_sub_r009s020:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0442_sub_r009s020

Predicting case_0444_sub_m2094:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0444_sub_m2094

Predicting case_0447_sub_053:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0447_sub_053

Predicting case_0448_sub_m2102:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0448_sub_m2102

Predicting case_0461_sub_046:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0461_sub_046

Predicting case_0464_sub_r005s026:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0464_sub_r005s026

Predicting case_0475_sub_r009s038:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0475_sub_r009s038

Predicting case_0477_sub_r031s008:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0477_sub_r031s008

Predicting case_0478_sub_r018s011:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0478_sub_r018s011

Predicting case_0484_sub_r049s007:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0484_sub_r049s007

Predicting case_0488_sub_r011s014:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0488_sub_r011s014

Predicting case_0492_sub_r034s026:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0492_sub_r034s026

Predicting case_0503_sub_r031s013:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0503_sub_r031s013

Predicting case_0505_sub_r031s004:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0505_sub_r031s004

Predicting case_0507_sub_r009s103:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0507_sub_r009s103

Predicting case_0509_sub_r038s097:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0509_sub_r038s097

Predicting case_0510_sub_r040s071:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0510_sub_r040s071

Predicting case_0516_sub_r042s018:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0516_sub_r042s018

Predicting case_0521_sub_m2109:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0521_sub_m2109

Predicting case_0527_sub_r001s020:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0527_sub_r001s020

Predicting case_0536_sub_r040s054:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0536_sub_r040s054

Predicting case_0537_sub_r009s088:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0537_sub_r009s088

Predicting case_0538_sub_m2026:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0538_sub_m2026

Predicting case_0539_sub_r052s021:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0539_sub_r052s021

Predicting case_0542_sub_r050s003:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0542_sub_r050s003

Predicting case_0547_sub_m2266:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0547_sub_m2266

Predicting case_0557_sub_r003s003:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0557_sub_r003s003

Predicting case_0560_sub_m2291:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0560_sub_m2291

Predicting case_0572_sub_m2158:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0572_sub_m2158

Predicting case_0576_sub_r011s024:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0576_sub_r011s024

Predicting case_0579_sub_r009s044:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0579_sub_r009s044

Predicting case_0581_sub_r038s049:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0581_sub_r038s049

Predicting case_0584_sub_m2299:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0584_sub_m2299

Predicting case_0587_sub_r002s008:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0587_sub_r002s008

Predicting case_0590_sub_r031s005:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0590_sub_r031s005

Predicting case_0593_sub_r001s017:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0593_sub_r001s017

Predicting case_0604_sub_m2111:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0604_sub_m2111

Predicting case_0609_sub_r040s015:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0609_sub_r040s015

Predicting case_0610_sub_r001s033:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.19it/s]

sending off prediction to background worker for resampling and export
done with case_0610_sub_r001s033

Predicting case_0627_sub_r001s003:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0627_sub_r001s003

Predicting case_0628_sub_r040s013:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0628_sub_r040s013

Predicting case_0632_sub_r034s009:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0632_sub_r034s009

Predicting case_0638_sub_r038s054:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0638_sub_r038s054

Predicting case_0642_sub_m2121:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0642_sub_m2121

Predicting case_0648_sub_m2110:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0648_sub_m2110

Predicting case_0651_sub_r009s054:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0651_sub_r009s054

Predicting case_0652_sub_r047s007:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0652_sub_r047s007

Predicting case_0656_sub_r031s034:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0656_sub_r031s034

Predicting case_0661_sub_r009s066:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.17it/s]

sending off prediction to background worker for resampling and export
done with case_0661_sub_r009s066

Predicting case_0669_sub_m2170:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0669_sub_m2170

Predicting case_0674_sub_r040s070:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0674_sub_r040s070

Predicting case_0685_sub_r046s005:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0685_sub_r046s005

Predicting case_0687_sub_r039s002:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0687_sub_r039s002

Predicting case_0696_sub_r047s044:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0696_sub_r047s044

Predicting case_0698_sub_r009s083:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0698_sub_r009s083

Predicting case_0704_sub_r035s005:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0704_sub_r035s005

Predicting case_0710_sub_r015s027:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0710_sub_r015s027

Predicting case_0714_sub_031:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0714_sub_031

Predicting case_0716_sub_r031s018:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0716_sub_r031s018

Predicting case_0728_sub_r011s015:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0728_sub_r011s015

Predicting case_0730_sub_r009s094:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0730_sub_r009s094

Predicting case_0732_sub_r038s043:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0732_sub_r038s043

Predicting case_0739_sub_r004s007:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0739_sub_r004s007

Predicting case_0751_sub_r028s013:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0751_sub_r028s013

Predicting case_0752_sub_r040s010:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0752_sub_r040s010

Predicting case_0753_sub_r038s017:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0753_sub_r038s017

Predicting case_0757_sub_m2260:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0757_sub_m2260

Predicting case_0758_sub_099:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0758_sub_099

Predicting case_0763_sub_r034s011:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0763_sub_r034s011

Predicting case_0781_sub_083:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0781_sub_083

Predicting case_0798_sub_r004s033:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0798_sub_r004s033

Predicting case_0811_sub_010:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0811_sub_010

Predicting case_0815_sub_m2150:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0815_sub_m2150

Predicting case_0821_sub_069:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0821_sub_069

Predicting case_0824_sub_r040s030:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0824_sub_r040s030

Predicting case_0829_sub_033:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0829_sub_033

Predicting case_0832_sub_r031s024:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0832_sub_r031s024

Predicting case_0837_sub_r040s039:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0837_sub_r040s039

Predicting case_0840_sub_r001s001:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0840_sub_r001s001

Predicting case_0844_sub_r018s010:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0844_sub_r018s010

Predicting case_0848_sub_m2073:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0848_sub_m2073

Predicting case_0858_sub_r042s021:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0858_sub_r042s021
/home/rbielski/miniconda3/envs/tf_310/bin/nnUNetv2_predict -i /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/nnunet_cv_predictions_native_split/fold_3_input -o /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/nnunet_cv_predictions_native_split/fold_3_pred -d 701 -c 3d_fullres -f 3 -p nnUNetPlans_24GB --save_probabilities

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

There are 173 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 173 cases that I would like to predict

Predicting case_0001_sub_m2306:
perform_everything_on_device: True

100%|██████████| 1/1 [00:01<00:00,  1.25s/it]
  0%|          | 0/1 [00:00<?, ?it/s]

sending off prediction to background worker for resampling and export
done with case_0001_sub_m2306

Predicting case_0002_sub_r034s039:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0002_sub_r034s039

Predicting case_0004_sub_r011s017:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0004_sub_r011s017

Predicting case_0016_sub_r001s025:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0016_sub_r001s025

Predicting case_0018_sub_r015s006:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0018_sub_r015s006

Predicting case_0020_sub_r003s010:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0020_sub_r003s010

Predicting case_0023_sub_m2076:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0023_sub_m2076

Predicting case_0027_sub_r040s067:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.02it/s]

sending off prediction to background worker for resampling and export
done with case_0027_sub_r040s067

Predicting case_0043_sub_r009s043:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0043_sub_r009s043

Predicting case_0049_sub_r024s011:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0049_sub_r024s011

Predicting case_0052_sub_r047s018:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0052_sub_r047s018

Predicting case_0062_sub_r052s015:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0062_sub_r052s015

Predicting case_0063_sub_r040s043:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0063_sub_r040s043

Predicting case_0066_sub_r023s009:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0066_sub_r023s009

Predicting case_0076_sub_m2100:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0076_sub_m2100

Predicting case_0081_sub_r034s008:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0081_sub_r034s008

Predicting case_0099_sub_m2186:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0099_sub_m2186

Predicting case_0102_sub_r010s011:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0102_sub_r010s011

Predicting case_0109_sub_r004s005:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0109_sub_r004s005

Predicting case_0110_sub_100:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0110_sub_100

Predicting case_0113_sub_011:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0113_sub_011

Predicting case_0133_sub_r042s011:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0133_sub_r042s011

Predicting case_0134_sub_r017s110:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.02it/s]

sending off prediction to background worker for resampling and export
done with case_0134_sub_r017s110

Predicting case_0136_sub_m2117:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0136_sub_m2117

Predicting case_0139_sub_r004s020:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0139_sub_r004s020

Predicting case_0153_sub_r040s001:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0153_sub_r040s001

Predicting case_0164_sub_r004s034:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0164_sub_r004s034

Predicting case_0169_sub_r009s007:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0169_sub_r009s007

Predicting case_0176_sub_017:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0176_sub_017

Predicting case_0177_sub_m2044:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0177_sub_m2044

Predicting case_0178_sub_m2307:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0178_sub_m2307

Predicting case_0185_sub_r017s105:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0185_sub_r017s105

Predicting case_0186_sub_r027s009:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0186_sub_r027s009

Predicting case_0190_sub_m2131:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0190_sub_m2131

Predicting case_0197_sub_r047s050:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.04it/s]

sending off prediction to background worker for resampling and export
done with case_0197_sub_r047s050

Predicting case_0200_sub_r009s035:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0200_sub_r009s035

Predicting case_0201_sub_r038s089:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0201_sub_r038s089

Predicting case_0210_sub_m2204:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0210_sub_m2204

Predicting case_0212_sub_r009s093:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0212_sub_r009s093

Predicting case_0213_sub_r011s033:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0213_sub_r011s033

Predicting case_0218_sub_r005s058:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.01it/s]

sending off prediction to background worker for resampling and export
done with case_0218_sub_r005s058

Predicting case_0220_sub_m2246:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0220_sub_m2246

Predicting case_0222_sub_r004s019:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0222_sub_r004s019

Predicting case_0223_sub_r028s017:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0223_sub_r028s017

Predicting case_0224_sub_r009s004:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0224_sub_r009s004

Predicting case_0230_sub_102:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0230_sub_102

Predicting case_0234_sub_r048s006:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0234_sub_r048s006

Predicting case_0248_sub_m2082:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0248_sub_m2082

Predicting case_0250_sub_094:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0250_sub_094

Predicting case_0255_sub_m2159:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0255_sub_m2159

Predicting case_0258_sub_055:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0258_sub_055

Predicting case_0265_sub_r003s011:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0265_sub_r003s011

Predicting case_0269_sub_m2141:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.02it/s]

sending off prediction to background worker for resampling and export
done with case_0269_sub_m2141

Predicting case_0272_sub_r027s032:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0272_sub_r027s032

Predicting case_0285_sub_r009s115:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0285_sub_r009s115

Predicting case_0287_sub_r001s005:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0287_sub_r001s005

Predicting case_0289_sub_r047s031:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0289_sub_r047s031

Predicting case_0293_sub_r040s017:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0293_sub_r040s017

Predicting case_0297_sub_r046s011:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0297_sub_r046s011

Predicting case_0301_sub_r009s037:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0301_sub_r009s037

Predicting case_0303_sub_r052s025:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0303_sub_r052s025

Predicting case_0304_sub_r038s068:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0304_sub_r038s068

Predicting case_0313_sub_028:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0313_sub_028

Predicting case_0314_sub_r010s018:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0314_sub_r010s018

Predicting case_0318_sub_m2290:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0318_sub_m2290

Predicting case_0329_sub_r010s001:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0329_sub_r010s001

Predicting case_0340_sub_m2243:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0340_sub_m2243

Predicting case_0343_sub_m2275:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0343_sub_m2275

Predicting case_0355_sub_r050s002:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0355_sub_r050s002

Predicting case_0358_sub_r011s008:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.02it/s]

sending off prediction to background worker for resampling and export
done with case_0358_sub_r011s008

Predicting case_0364_sub_m2078:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.02it/s]

sending off prediction to background worker for resampling and export
done with case_0364_sub_m2078

Predicting case_0365_sub_r034s047:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0365_sub_r034s047

Predicting case_0382_sub_r029s007:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.02it/s]

sending off prediction to background worker for resampling and export
done with case_0382_sub_r029s007

Predicting case_0385_sub_r010s006:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0385_sub_r010s006

Predicting case_0386_sub_r042s008:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0386_sub_r042s008

Predicting case_0394_sub_040:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0394_sub_040

Predicting case_0397_sub_r017s116:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0397_sub_r017s116

Predicting case_0398_sub_r009s021:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0398_sub_r009s021

Predicting case_0408_sub_r001s009:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0408_sub_r001s009

Predicting case_0431_sub_r040s046:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0431_sub_r040s046

Predicting case_0432_sub_m2079:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0432_sub_m2079

Predicting case_0451_sub_082:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0451_sub_082

Predicting case_0457_sub_r004s011:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0457_sub_r004s011

Predicting case_0466_sub_r047s036:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0466_sub_r047s036

Predicting case_0469_sub_r040s032:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.02it/s]

sending off prediction to background worker for resampling and export
done with case_0469_sub_r040s032

Predicting case_0474_sub_r031s026:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0474_sub_r031s026

Predicting case_0480_sub_r027s015:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0480_sub_r027s015

Predicting case_0481_sub_m2126:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0481_sub_m2126

Predicting case_0482_sub_m2160:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.00it/s]

sending off prediction to background worker for resampling and export
done with case_0482_sub_m2160

Predicting case_0483_sub_r029s004:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0483_sub_r029s004

Predicting case_0489_sub_r005s031:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0489_sub_r005s031

Predicting case_0494_sub_r034s003:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0494_sub_r034s003

Predicting case_0496_sub_r003s015:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0496_sub_r003s015

Predicting case_0501_sub_m2138:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0501_sub_m2138

Predicting case_0511_sub_m2294:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.04it/s]

sending off prediction to background worker for resampling and export
done with case_0511_sub_m2294

Predicting case_0515_sub_r048s010:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0515_sub_r048s010

Predicting case_0518_sub_r011s034:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0518_sub_r011s034

Predicting case_0525_sub_r031s014:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0525_sub_r031s014

Predicting case_0526_sub_r040s085:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.02it/s]

sending off prediction to background worker for resampling and export
done with case_0526_sub_r040s085

Predicting case_0533_sub_r038s048:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0533_sub_r038s048

Predicting case_0551_sub_r027s031:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0551_sub_r027s031

Predicting case_0559_sub_r038s084:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0559_sub_r038s084

Predicting case_0563_sub_071:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0563_sub_071

Predicting case_0565_sub_r038s060:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0565_sub_r038s060

Predicting case_0570_sub_r009s102:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0570_sub_r009s102

Predicting case_0577_sub_r009s111:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0577_sub_r009s111

Predicting case_0580_sub_r010s008:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0580_sub_r010s008

Predicting case_0585_sub_r009s107:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0585_sub_r009s107

Predicting case_0589_sub_r031s011:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0589_sub_r031s011

Predicting case_0591_sub_m2208:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0591_sub_m2208

Predicting case_0595_sub_r038s069:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0595_sub_r038s069

Predicting case_0605_sub_r035s012:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0605_sub_r035s012

Predicting case_0606_sub_m2123:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0606_sub_m2123

Predicting case_0618_sub_m2192:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0618_sub_m2192

Predicting case_0619_sub_r011s003:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.02it/s]

sending off prediction to background worker for resampling and export
done with case_0619_sub_r011s003

Predicting case_0622_sub_r042s025:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.04it/s]

sending off prediction to background worker for resampling and export
done with case_0622_sub_r042s025

Predicting case_0624_sub_r038s074:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0624_sub_r038s074

Predicting case_0629_sub_096:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0629_sub_096

Predicting case_0634_sub_r048s043:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0634_sub_r048s043

Predicting case_0635_sub_m2265:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0635_sub_m2265

Predicting case_0639_sub_m2202:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0639_sub_m2202

Predicting case_0643_sub_r015s009:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0643_sub_r015s009

Predicting case_0645_sub_038:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0645_sub_038

Predicting case_0646_sub_r049s025:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0646_sub_r049s025

Predicting case_0667_sub_r005s015:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0667_sub_r005s015

Predicting case_0668_sub_r034s048:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0668_sub_r034s048

Predicting case_0672_sub_r017s118:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0672_sub_r017s118

Predicting case_0676_sub_m2029:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0676_sub_m2029

Predicting case_0677_sub_015:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.02it/s]

sending off prediction to background worker for resampling and export
done with case_0677_sub_015

Predicting case_0678_sub_m2245:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0678_sub_m2245

Predicting case_0679_sub_r010s012:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0679_sub_r010s012

Predicting case_0680_sub_036:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0680_sub_036

Predicting case_0681_sub_103:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.02it/s]

sending off prediction to background worker for resampling and export
done with case_0681_sub_103

Predicting case_0700_sub_r031s031:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0700_sub_r031s031

Predicting case_0701_sub_061:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.02it/s]

sending off prediction to background worker for resampling and export
done with case_0701_sub_061

Predicting case_0702_sub_r038s096:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0702_sub_r038s096

Predicting case_0705_sub_m2237:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0705_sub_m2237

Predicting case_0707_sub_m2097:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.02it/s]

sending off prediction to background worker for resampling and export
done with case_0707_sub_m2097

Predicting case_0709_sub_m2149:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0709_sub_m2149

Predicting case_0722_sub_079:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0722_sub_079

Predicting case_0724_sub_r002s012:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0724_sub_r002s012

Predicting case_0735_sub_r040s069:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0735_sub_r040s069

Predicting case_0741_sub_r009s001:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0741_sub_r009s001

Predicting case_0744_sub_r001s032:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0744_sub_r001s032

Predicting case_0748_sub_r009s010:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.02it/s]

sending off prediction to background worker for resampling and export
done with case_0748_sub_r009s010

Predicting case_0755_sub_r009s075:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.02it/s]

sending off prediction to background worker for resampling and export
done with case_0755_sub_r009s075

Predicting case_0756_sub_r011s019:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0756_sub_r011s019

Predicting case_0768_sub_r004s006:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0768_sub_r004s006

Predicting case_0772_sub_r009s063:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0772_sub_r009s063

Predicting case_0774_sub_r009s056:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0774_sub_r009s056

Predicting case_0779_sub_052:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0779_sub_052

Predicting case_0783_sub_m2136:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0783_sub_m2136

Predicting case_0786_sub_r001s031:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0786_sub_r001s031

Predicting case_0792_sub_r031s012:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0792_sub_r031s012

Predicting case_0793_sub_r009s053:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0793_sub_r009s053

Predicting case_0796_sub_r035s006:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0796_sub_r035s006

Predicting case_0797_sub_r052s019:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0797_sub_r052s019

Predicting case_0802_sub_m2198:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0802_sub_m2198

Predicting case_0810_sub_r009s032:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0810_sub_r009s032

Predicting case_0813_sub_m2156:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.02it/s]

sending off prediction to background worker for resampling and export
done with case_0813_sub_m2156

Predicting case_0822_sub_r009s028:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0822_sub_r009s028

Predicting case_0823_sub_088:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0823_sub_088

Predicting case_0825_sub_m2248:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.01it/s]

sending off prediction to background worker for resampling and export
done with case_0825_sub_m2248

Predicting case_0828_sub_m2036:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.02it/s]

sending off prediction to background worker for resampling and export
done with case_0828_sub_m2036

Predicting case_0831_sub_r004s017:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0831_sub_r004s017

Predicting case_0846_sub_r001s021:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.04it/s]

sending off prediction to background worker for resampling and export
done with case_0846_sub_r001s021

Predicting case_0847_sub_m2151:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0847_sub_m2151

Predicting case_0854_sub_056:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.02it/s]

sending off prediction to background worker for resampling and export
done with case_0854_sub_056

Predicting case_0856_sub_r038s085:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0856_sub_r038s085

Predicting case_0861_sub_r002s010:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0861_sub_r002s010

Predicting case_0863_sub_r042s030:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0863_sub_r042s030

Predicting case_0864_sub_m2061:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0864_sub_m2061

Predicting case_0865_sub_m2178:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.03it/s]

sending off prediction to background worker for resampling and export
done with case_0865_sub_m2178
/home/rbielski/miniconda3/envs/tf_310/bin/nnUNetv2_predict -i /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/nnunet_cv_predictions_native_split/fold_4_input -o /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/nnunet_cv_predictions_native_split/fold_4_pred -d 701 -c 3d_fullres -f 4 -p nnUNetPlans_24GB --save_probabilities

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

There are 173 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 173 cases that I would like to predict

Predicting case_0005_sub_m2283:
perform_everything_on_device: True

100%|██████████| 1/1 [00:01<00:00,  1.25s/it]
  0%|          | 0/1 [00:00<?, ?it/s]

sending off prediction to background worker for resampling and export
done with case_0005_sub_m2283

Predicting case_0007_sub_r047s006:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0007_sub_r047s006

Predicting case_0012_sub_m2060:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0012_sub_m2060

Predicting case_0014_sub_m2018:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0014_sub_m2018

Predicting case_0024_sub_r011s023:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0024_sub_r011s023

Predicting case_0032_sub_m2310:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0032_sub_m2310

Predicting case_0039_sub_r009s119:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0039_sub_r009s119

Predicting case_0041_sub_r031s028:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0041_sub_r031s028

Predicting case_0044_sub_m2293:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0044_sub_m2293

Predicting case_0051_sub_r009s123:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0051_sub_r009s123

Predicting case_0056_sub_r034s036:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0056_sub_r034s036

Predicting case_0064_sub_r002s007:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0064_sub_r002s007

Predicting case_0084_sub_080:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0084_sub_080

Predicting case_0086_sub_r004s023:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0086_sub_r004s023

Predicting case_0091_sub_r024s014:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0091_sub_r024s014

Predicting case_0097_sub_m2072:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0097_sub_m2072

Predicting case_0098_sub_r004s026:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0098_sub_r004s026

Predicting case_0101_sub_m2112:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0101_sub_m2112

Predicting case_0105_sub_r031s036:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0105_sub_r031s036

Predicting case_0107_sub_r040s004:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0107_sub_r040s004

Predicting case_0118_sub_m2295:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0118_sub_m2295

Predicting case_0122_sub_r001s011:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0122_sub_r001s011

Predicting case_0127_sub_027:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0127_sub_027

Predicting case_0137_sub_065:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0137_sub_065

Predicting case_0140_sub_r001s019:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0140_sub_r001s019

Predicting case_0148_sub_r010s029:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0148_sub_r010s029

Predicting case_0150_sub_r001s030:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0150_sub_r001s030

Predicting case_0152_sub_r042s013:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0152_sub_r042s013

Predicting case_0158_sub_r019s007:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0158_sub_r019s007

Predicting case_0161_sub_m2269:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0161_sub_m2269

Predicting case_0162_sub_r004s035:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0162_sub_r004s035

Predicting case_0168_sub_r002s009:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0168_sub_r002s009

Predicting case_0171_sub_r047s014:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0171_sub_r047s014

Predicting case_0175_sub_r031s009:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0175_sub_r031s009

Predicting case_0179_sub_r009s078:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0179_sub_r009s078

Predicting case_0180_sub_r018s007:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0180_sub_r018s007

Predicting case_0182_sub_r004s015:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0182_sub_r004s015

Predicting case_0183_sub_013:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0183_sub_013

Predicting case_0193_sub_r040s031:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0193_sub_r040s031

Predicting case_0194_sub_r034s015:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0194_sub_r034s015

Predicting case_0196_sub_035:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0196_sub_035

Predicting case_0204_sub_m2213:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0204_sub_m2213

Predicting case_0205_sub_r031s022:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0205_sub_r031s022

Predicting case_0209_sub_m2197:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0209_sub_m2197

Predicting case_0211_sub_r040s022:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0211_sub_r040s022

Predicting case_0216_sub_r048s036:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0216_sub_r048s036

Predicting case_0227_sub_047:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0227_sub_047

Predicting case_0232_sub_r003s013:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0232_sub_r003s013

Predicting case_0241_sub_r040s024:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0241_sub_r040s024

Predicting case_0245_sub_r049s020:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0245_sub_r049s020

Predicting case_0251_sub_m2196:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0251_sub_m2196

Predicting case_0254_sub_r031s015:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0254_sub_r031s015

Predicting case_0256_sub_m2179:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0256_sub_m2179

Predicting case_0261_sub_m2268:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0261_sub_m2268

Predicting case_0263_sub_r009s002:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0263_sub_r009s002

Predicting case_0266_sub_m2221:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0266_sub_m2221

Predicting case_0271_sub_r047s013:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0271_sub_r047s013

Predicting case_0274_sub_r048s018:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0274_sub_r048s018

Predicting case_0275_sub_r001s024:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0275_sub_r001s024

Predicting case_0288_sub_m2235:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0288_sub_m2235

Predicting case_0292_sub_r009s067:
perform_everything_on_device: True

100%|██████████| 2/2 [00:00<00:00,  3.55it/s]

sending off prediction to background worker for resampling and export
done with case_0292_sub_r009s067

Predicting case_0299_sub_r040s053:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0299_sub_r040s053

Predicting case_0300_sub_r019s010:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0300_sub_r019s010

Predicting case_0306_sub_r046s001:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0306_sub_r046s001

Predicting case_0311_sub_r009s017:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0311_sub_r009s017

Predicting case_0312_sub_r010s002:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0312_sub_r010s002

Predicting case_0317_sub_057:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0317_sub_057

Predicting case_0326_sub_005:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0326_sub_005

Predicting case_0333_sub_m2153:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0333_sub_m2153

Predicting case_0335_sub_m2305:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0335_sub_m2305

Predicting case_0346_sub_r038s064:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0346_sub_r038s064

Predicting case_0347_sub_r011s027:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0347_sub_r011s027

Predicting case_0349_sub_r004s030:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0349_sub_r004s030

Predicting case_0360_sub_r009s006:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0360_sub_r009s006

Predicting case_0361_sub_r017s106:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0361_sub_r017s106

Predicting case_0368_sub_r001s002:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0368_sub_r001s002

Predicting case_0369_sub_m2155:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0369_sub_m2155

Predicting case_0371_sub_r015s019:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0371_sub_r015s019

Predicting case_0372_sub_r023s007:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0372_sub_r023s007

Predicting case_0376_sub_r038s047:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0376_sub_r038s047

Predicting case_0381_sub_r009s109:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0381_sub_r009s109

Predicting case_0384_sub_070:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0384_sub_070

Predicting case_0402_sub_r009s089:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0402_sub_r009s089

Predicting case_0413_sub_r015s011:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0413_sub_r015s011

Predicting case_0425_sub_012:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0425_sub_012

Predicting case_0428_sub_m2201:
perform_everything_on_device: True

100%|██████████| 2/2 [00:00<00:00,  3.54it/s]

sending off prediction to background worker for resampling and export
done with case_0428_sub_m2201

Predicting case_0430_sub_m2230:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0430_sub_m2230

Predicting case_0437_sub_r010s004:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0437_sub_r010s004

Predicting case_0441_sub_m2205:
perform_everything_on_device: True

100%|██████████| 2/2 [00:00<00:00,  3.55it/s]

sending off prediction to background worker for resampling and export
done with case_0441_sub_m2205

Predicting case_0443_sub_r046s008:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0443_sub_r046s008

Predicting case_0446_sub_r034s021:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0446_sub_r034s021

Predicting case_0449_sub_r047s035:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0449_sub_r047s035

Predicting case_0452_sub_r038s005:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0452_sub_r038s005

Predicting case_0453_sub_r001s006:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0453_sub_r001s006

Predicting case_0454_sub_r009s031:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0454_sub_r009s031

Predicting case_0460_sub_m2183:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0460_sub_m2183

Predicting case_0465_sub_m2042:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0465_sub_m2042

Predicting case_0468_sub_r027s041:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0468_sub_r027s041

Predicting case_0470_sub_023:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0470_sub_023

Predicting case_0479_sub_r034s046:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0479_sub_r034s046

Predicting case_0486_sub_m2125:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0486_sub_m2125

Predicting case_0506_sub_m2191:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0506_sub_m2191

Predicting case_0512_sub_m2137:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0512_sub_m2137

Predicting case_0513_sub_r019s001:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0513_sub_r019s001

Predicting case_0517_sub_r018s001:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0517_sub_r018s001

Predicting case_0519_sub_r048s031:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0519_sub_r048s031

Predicting case_0520_sub_r035s013:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0520_sub_r035s013

Predicting case_0523_sub_r038s033:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0523_sub_r038s033

Predicting case_0524_sub_r027s035:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0524_sub_r027s035

Predicting case_0528_sub_r004s036:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0528_sub_r004s036

Predicting case_0530_sub_m2239:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0530_sub_m2239

Predicting case_0535_sub_r011s011:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0535_sub_r011s011

Predicting case_0544_sub_r014s010:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0544_sub_r014s010

Predicting case_0562_sub_m2216:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0562_sub_m2216

Predicting case_0569_sub_r009s027:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0569_sub_r009s027

Predicting case_0571_sub_m2113:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0571_sub_m2113

Predicting case_0574_sub_r038s040:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0574_sub_r038s040

Predicting case_0582_sub_051:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0582_sub_051

Predicting case_0599_sub_r052s010:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0599_sub_r052s010

Predicting case_0615_sub_r052s001:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0615_sub_r052s001

Predicting case_0620_sub_r023s003:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0620_sub_r023s003

Predicting case_0625_sub_r048s021:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0625_sub_r048s021

Predicting case_0626_sub_r005s075:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0626_sub_r005s075

Predicting case_0630_sub_r049s026:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.22it/s]

sending off prediction to background worker for resampling and export
done with case_0630_sub_r049s026

Predicting case_0631_sub_r009s126:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0631_sub_r009s126

Predicting case_0640_sub_m2199:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0640_sub_m2199

Predicting case_0641_sub_r024s021:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0641_sub_r024s021

Predicting case_0649_sub_r002s005:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0649_sub_r002s005

Predicting case_0653_sub_m2054:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0653_sub_m2054

Predicting case_0657_sub_m2012:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0657_sub_m2012

Predicting case_0658_sub_r024s018:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0658_sub_r024s018

Predicting case_0660_sub_m2254:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0660_sub_m2254

Predicting case_0665_sub_r045s002:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0665_sub_r045s002

Predicting case_0671_sub_m2282:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0671_sub_m2282

Predicting case_0673_sub_r048s034:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0673_sub_r048s034

Predicting case_0686_sub_041:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0686_sub_041

Predicting case_0688_sub_m2182:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0688_sub_m2182

Predicting case_0690_sub_r047s048:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0690_sub_r047s048

Predicting case_0692_sub_r028s008:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0692_sub_r028s008

Predicting case_0694_sub_r024s013:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0694_sub_r024s013

Predicting case_0711_sub_r019s004:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0711_sub_r019s004

Predicting case_0712_sub_m2214:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0712_sub_m2214

Predicting case_0713_sub_r052s011:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0713_sub_r052s011

Predicting case_0715_sub_r009s097:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0715_sub_r009s097

Predicting case_0719_sub_r044s003:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0719_sub_r044s003

Predicting case_0720_sub_r004s002:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0720_sub_r004s002

Predicting case_0723_sub_r042s035:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0723_sub_r042s035

Predicting case_0725_sub_097:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0725_sub_097

Predicting case_0729_sub_r038s021:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0729_sub_r038s021

Predicting case_0736_sub_r031s001:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0736_sub_r031s001

Predicting case_0740_sub_r009s099:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0740_sub_r009s099

Predicting case_0742_sub_r049s010:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0742_sub_r049s010

Predicting case_0746_sub_r047s043:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0746_sub_r047s043

Predicting case_0749_sub_r040s002:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0749_sub_r040s002

Predicting case_0750_sub_r001s022:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0750_sub_r001s022

Predicting case_0760_sub_r027s001:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0760_sub_r027s001

Predicting case_0761_sub_m2272:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0761_sub_m2272

Predicting case_0762_sub_014:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0762_sub_014

Predicting case_0764_sub_m2124:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0764_sub_m2124

Predicting case_0777_sub_r011s010:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0777_sub_r011s010

Predicting case_0794_sub_025:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0794_sub_025

Predicting case_0801_sub_r009s074:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0801_sub_r009s074

Predicting case_0804_sub_r011s016:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0804_sub_r011s016

Predicting case_0805_sub_r042s004:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0805_sub_r042s004

Predicting case_0808_sub_r004s003:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0808_sub_r004s003

Predicting case_0814_sub_r009s076:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.20it/s]

sending off prediction to background worker for resampling and export
done with case_0814_sub_r009s076

Predicting case_0818_sub_r047s016:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0818_sub_r047s016

Predicting case_0830_sub_r049s018:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0830_sub_r049s018

Predicting case_0836_sub_091:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0836_sub_091

Predicting case_0839_sub_r040s064:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0839_sub_r040s064

Predicting case_0845_sub_r001s037:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0845_sub_r001s037

Predicting case_0852_sub_m2144:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0852_sub_m2144

Predicting case_0857_sub_m2164:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

sending off prediction to background worker for resampling and export
done with case_0857_sub_m2164

In [28]:
RUN_CV_POSTPROCESS = True

if RUN_CV_POSTPROCESS:
    post_dirs = []
    for pred_dir in sorted(CV_ROOT.glob("fold_*_pred")):
        out_dir = pred_dir.with_name(pred_dir.name + "_postprocessed")
        pipe.postprocess_probabilities(pred_dir, out_dir, mapping_csv=layout.mapping_csv)
        post_dirs.append(out_dir)
    print("Postprocessed:", post_dirs)
else:
    print("Set RUN_CV_POSTPROCESS=True if CV predictions were saved with probabilities.")

Postprocessed: [PosixPath('/home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/nnunet_cv_predictions_native_split/fold_0_pred_postprocessed'), PosixPath('/home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/nnunet_cv_predictions_native_split/fold_1_pred_postprocessed'), PosixPath('/home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/nnunet_cv_predictions_native_split/fold_2_pred_postprocessed'), PosixPath('/home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/nnunet_cv_predictions_native_split/fold_3_pred_postprocessed'), PosixPath('/home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/nnunet_cv_predictions_native_split/fold_4_pred_postprocessed')]

In [29]:
def has_prediction_masks(path):
    return path.is_dir() and any(path.glob("*.nii.gz"))

raw_pred_dirs = [d for d in sorted(CV_ROOT.glob("fold_*_pred")) if has_prediction_masks(d)]
post_pred_dirs = [d for d in sorted(CV_ROOT.glob("fold_*_pred_postprocessed")) if has_prediction_masks(d)]
eval_dirs = post_pred_dirs or raw_pred_dirs

if eval_dirs:
    summary = pipe.evaluate_predictions(eval_dirs, layout.mapping_csv, CV_ROOT / "evaluation.csv")
    print(json.dumps(summary, indent=2))
else:
    print("No CV prediction masks found yet:", CV_ROOT)

{
  "n": 866,
  "dice_mean": 0.022912144699769054,
  "dice_median": 0.0,
  "dice_by_group": {
    "000001_000099": {
      "n": 26,
      "mean": 0.006423811153846154,
      "median": 0.0
    },
    "000100_000999": {
      "n": 176,
      "mean": 0.01221007318181818,
      "median": 0.0
    },
    "001000_009999": {
      "n": 234,
      "mean": 0.019669617863247866,
      "median": 0.0
    },
    "010000_plus": {
      "n": 430,
      "mean": 0.030054034325581395,
      "median": 0.0
    }
  },
  "output_csv": "/home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/nnunet_cv_predictions_native_split/evaluation.csv"
}

## 7. All-Fold Inference For External/Test Data

In [32]:
RUN_TEST_PREDICT = True
TEST_MANIFEST = PROJECT_ROOT / "data" / "splits" / "90_10_random" / "test" / "manifest.csv"
TEST_INPUT = PROJECT_ROOT / "runs" / "nnunet_test_input_native"
TEST_PRED = PROJECT_ROOT / "runs" / "nnunet_test_predictions_native"
TEST_POST = PROJECT_ROOT / "runs" / "nnunet_test_predictions_native_postprocessed"

if RUN_TEST_PREDICT:
    if not TEST_MANIFEST.exists():
        raise FileNotFoundError(f"No test manifest found: {TEST_MANIFEST}")
    pipe.prepare_prediction_input_from_manifest(TEST_MANIFEST, TEST_INPUT, project_root=PROJECT_ROOT, overwrite=True)
    pipe.predict(layout, TEST_INPUT, TEST_PRED, folds=(0, 1, 2, 3, 4), configuration="3d_fullres", plans=PLANS_NAME)
    pipe.postprocess_probabilities(TEST_PRED, TEST_POST, mapping_csv=TEST_INPUT / "case_mapping.csv")
    print("Postprocessed predictions:", TEST_POST)
else:
    print("Set RUN_TEST_PREDICT=True after all five folds are trained.")

/home/rbielski/miniconda3/envs/tf_310/bin/nnUNetv2_predict -i /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/nnunet_test_input_native -o /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/nnunet_test_predictions_native -d 701 -c 3d_fullres -f 0 1 2 3 4 -p nnUNetPlans_24GB --save_probabilities

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

There are 96 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 96 cases that I would like to predict

Predicting case_0001_sub_m2050:
perform_everything_on_device: True

100%|██████████| 1/1 [00:01<00:00,  1.23s/it]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0001_sub_m2050

Predicting case_0002_sub_r048s029:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0002_sub_r048s029

Predicting case_0003_sub_r031s006:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0003_sub_r031s006

Predicting case_0004_sub_r049s016:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0004_sub_r049s016

Predicting case_0005_sub_r040s048:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0005_sub_r040s048

Predicting case_0006_sub_r031s003:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0006_sub_r031s003

Predicting case_0007_sub_r048s011:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0007_sub_r048s011

Predicting case_0008_sub_r023s017:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0008_sub_r023s017

Predicting case_0009_sub_r015s025:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0009_sub_r015s025

Predicting case_0010_sub_r001s038:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0010_sub_r001s038

Predicting case_0011_sub_r038s091:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0011_sub_r038s091

Predicting case_0012_sub_r040s045:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0012_sub_r040s045

Predicting case_0013_sub_r023s001:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0013_sub_r023s001

Predicting case_0014_sub_r005s049:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0014_sub_r005s049

Predicting case_0015_sub_m2238:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0015_sub_m2238

Predicting case_0016_sub_r023s008:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0016_sub_r023s008

Predicting case_0017_sub_r011s013:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0017_sub_r011s013

Predicting case_0018_sub_r009s005:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0018_sub_r009s005

Predicting case_0019_sub_r005s070:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0019_sub_r005s070

Predicting case_0020_sub_m2106:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0020_sub_m2106

Predicting case_0021_sub_m2099:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0021_sub_m2099

Predicting case_0022_sub_r009s003:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0022_sub_r009s003

Predicting case_0023_sub_020:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0023_sub_020

Predicting case_0024_sub_r009s012:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0024_sub_r009s012

Predicting case_0025_sub_r040s075:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0025_sub_r040s075

Predicting case_0026_sub_r002s001:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0026_sub_r002s001

Predicting case_0027_sub_m2140:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0027_sub_m2140

Predicting case_0028_sub_048:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0028_sub_048

Predicting case_0029_sub_r009s086:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0029_sub_r009s086

Predicting case_0030_sub_074:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0030_sub_074

Predicting case_0031_sub_093:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0031_sub_093

Predicting case_0032_sub_r003s004:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0032_sub_r003s004

Predicting case_0033_sub_r052s014:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0033_sub_r052s014

Predicting case_0034_sub_r031s027:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0034_sub_r031s027

Predicting case_0035_sub_r015s026:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0035_sub_r015s026

Predicting case_0036_sub_m2103:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0036_sub_m2103

Predicting case_0037_sub_039:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0037_sub_039

Predicting case_0038_sub_r052s031:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0038_sub_r052s031

Predicting case_0039_sub_r009s079:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0039_sub_r009s079

Predicting case_0040_sub_r014s008:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0040_sub_r014s008

Predicting case_0041_sub_r040s042:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0041_sub_r040s042

Predicting case_0042_sub_054:
perform_everything_on_device: True

100%|██████████| 2/2 [00:00<00:00,  3.59it/s]
100%|██████████| 2/2 [00:00<00:00,  3.59it/s]
100%|██████████| 2/2 [00:00<00:00,  3.59it/s]
100%|██████████| 2/2 [00:00<00:00,  3.59it/s]
100%|██████████| 2/2 [00:00<00:00,  3.59it/s]

sending off prediction to background worker for resampling and export
done with case_0042_sub_054

Predicting case_0043_sub_m2271:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0043_sub_m2271

Predicting case_0044_sub_r027s050:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0044_sub_r027s050

Predicting case_0045_sub_002:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0045_sub_002

Predicting case_0046_sub_r009s011:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0046_sub_r009s011

Predicting case_0047_sub_r009s064:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0047_sub_r009s064

Predicting case_0048_sub_r034s014:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0048_sub_r034s014

Predicting case_0049_sub_r035s007:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]

sending off prediction to background worker for resampling and export
done with case_0049_sub_r035s007

Predicting case_0050_sub_r052s016:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0050_sub_r052s016

Predicting case_0051_sub_r009s034:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0051_sub_r009s034

Predicting case_0052_sub_r009s039:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0052_sub_r009s039

Predicting case_0053_sub_r040s086:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0053_sub_r040s086

Predicting case_0054_sub_m2276:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0054_sub_m2276

Predicting case_0055_sub_m2052:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0055_sub_m2052

Predicting case_0056_sub_m2083:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0056_sub_m2083

Predicting case_0057_sub_r009s120:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0057_sub_r009s120

Predicting case_0058_sub_r048s008:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0058_sub_r048s008

Predicting case_0059_sub_r010s026:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0059_sub_r010s026

Predicting case_0060_sub_r031s010:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0060_sub_r031s010

Predicting case_0061_sub_r011s018:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.38it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0061_sub_r011s018

Predicting case_0062_sub_r038s093:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0062_sub_r038s093

Predicting case_0063_sub_r042s001:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0063_sub_r042s001

Predicting case_0064_sub_r048s016:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0064_sub_r048s016

Predicting case_0065_sub_101:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0065_sub_101

Predicting case_0066_sub_r004s032:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0066_sub_r004s032

Predicting case_0067_sub_r010s028:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0067_sub_r010s028

Predicting case_0068_sub_r042s032:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0068_sub_r042s032

Predicting case_0069_sub_030:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0069_sub_030

Predicting case_0070_sub_r035s011:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0070_sub_r035s011

Predicting case_0071_sub_r045s003:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0071_sub_r045s003

Predicting case_0072_sub_r011s029:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0072_sub_r011s029

Predicting case_0073_sub_r049s024:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0073_sub_r049s024

Predicting case_0074_sub_r001s034:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0074_sub_r001s034

Predicting case_0075_sub_r031s030:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0075_sub_r031s030

Predicting case_0076_sub_r031s020:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0076_sub_r031s020

Predicting case_0077_sub_r038s025:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0077_sub_r038s025

Predicting case_0078_sub_r005s045:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0078_sub_r005s045

Predicting case_0079_sub_r040s059:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0079_sub_r040s059

Predicting case_0080_sub_044:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0080_sub_044

Predicting case_0081_sub_r049s028:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.34it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0081_sub_r049s028

Predicting case_0082_sub_r004s022:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0082_sub_r004s022

Predicting case_0083_sub_r027s006:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0083_sub_r027s006

Predicting case_0084_sub_r009s036:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

sending off prediction to background worker for resampling and export
done with case_0084_sub_r009s036

Predicting case_0085_sub_r031s002:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0085_sub_r031s002

Predicting case_0086_sub_m2139:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0086_sub_m2139

Predicting case_0087_sub_r009s058:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0087_sub_r009s058

Predicting case_0088_sub_r009s071:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0088_sub_r009s071

Predicting case_0089_sub_m2308:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0089_sub_m2308

Predicting case_0090_sub_m2071:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0090_sub_m2071

Predicting case_0091_sub_r014s004:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0091_sub_r014s004

Predicting case_0092_sub_r052s002:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0092_sub_r052s002

Predicting case_0093_sub_r052s007:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0093_sub_r052s007

Predicting case_0094_sub_r034s032:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.36it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0094_sub_r034s032

Predicting case_0095_sub_r028s020:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0095_sub_r028s020

Predicting case_0096_sub_r047s001:
perform_everything_on_device: True

100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.23it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]
100%|██████████| 1/1 [00:00<00:00,  5.37it/s]

sending off prediction to background worker for resampling and export
done with case_0096_sub_r047s001
Postprocessed predictions: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/nnunet_test_predictions_native_postprocessed