# ARC_ATLAS v4 ATLAS-Heavy Replay Resume v2

This notebook replaces the prior pure ATLAS-only fine-tune.

Purpose:

- start from the best tri-planar `goal08` checkpoints
- fine-tune with **ATLAS-heavy mixed replay** instead of pure ATLAS-only training
- freeze only the earliest encoder blocks while keeping BatchNorm frozen
- evaluate on the **same mixed validation split** plus its ATLAS subset so the comparisons stay clean
- loosen the fine-tune enough that the branches can still move

In [1]:
from pathlib import Path
import sys
import time
import json

candidates = [
    Path.cwd(),
    Path.cwd() / "ARC_ATLAS_Combined" / "ARC_ATLAS_Train_v4",
    Path("/home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4"),
]
PROJECT_ROOT = next(
    (p for p in candidates if (p / "src" / "training_v2_slice_blocks.py").exists()),
    None,
)
if PROJECT_ROOT is None:
    raise FileNotFoundError("Could not locate ARC_ATLAS_Train_v4/src/training_v2_slice_blocks.py")

SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

import training_v2_slice_blocks as seg

TRAIN_DIR = PROJECT_ROOT / "data" / "splits" / "90_10_random" / "train"
FULL_MANIFEST = TRAIN_DIR / "manifest.csv"
SOURCE_RUN = PROJECT_ROOT / "runs" / "20260422_171449_slice_blocks_triplanar_goal08"
RUN_DIR = PROJECT_ROOT / "runs" / f"{time.strftime('%Y%m%d_%H%M%S')}_slice_blocks_resume_atlas_replay_looserfreeze"
RUN_DIR.mkdir(parents=True, exist_ok=True)

ATLAS_SLUG = "ATLAS-Images-f0d7431e"
ARC_SLUG = "ARC-combined-t1-raw-ab0d1794"
APPROX_SLUG = "Approx-Numeracy-Processed"
SOURCE_WEIGHT_MAP = {
    ATLAS_SLUG: 3.5,
    ARC_SLUG: 1.5,
    APPROX_SLUG: 1.0,
}

AXIS_NAMES = {0: "sagittal", 1: "coronal", 2: "axial"}
AXES_TO_TRAIN = (2, 0, 1)

COMMON_CFG = dict(
    DATA_DIR=TRAIN_DIR,
    IMAGES_DIR=TRAIN_DIR / "t1",
    MASKS_DIR=TRAIN_DIR / "masks",
    MANIFEST_PATH=FULL_MANIFEST,
    TARGET_SHAPE=(192, 224, 192),
    RESAMPLE_TO_TARGET=False,
    VALIDATION_SPLIT=0.15,
    BLOCK_DEPTH=7,
    SLICE_STRIDE=1,
    TOTAL_EPOCHS=18,
    INITIAL_LR=6e-6,
    MIN_LR=1e-6,
    WEIGHT_DECAY=5e-6,
    MAX_GRAD_NORM=0.75,
    MIXED_PRECISION=False,
    JIT_COMPILE=False,
    BASE_FILTERS=12,
    UNET_DEPTH=4,
    DROPOUT_RATE=0.06,
    L2_REG=1e-4,
    BALANCED_CASE_SAMPLING=True,
    SOURCE_BALANCED_SAMPLING=True,
    SOURCE_SAMPLING_WEIGHTS=tuple(SOURCE_WEIGHT_MAP.items()),
    SIZE_AWARE_SAMPLING=True,
    SIZE_BUCKET_EDGES=(100, 1000, 10000),
    SIZE_BUCKET_PROBS=(0.42, 0.28, 0.18, 0.12),
    STEPS_PER_EPOCH=420,
    VALIDATION_STEPS=18,
    POSITIVE_WEIGHT=28.0,
    BCE_WEIGHT=0.38,
    DICE_WEIGHT=0.46,
    FOCAL_TVERSKY_WEIGHT=0.16,
    TVERSKY_ALPHA=0.58,
    TVERSKY_BETA=0.42,
    FOCAL_TVERSKY_GAMMA=1.33,
    LESION_SLICE_WEIGHT=1.35,
    EMPTY_SLICE_WEIGHT=0.95,
    DICE_ON_LESION_SLICES_ONLY=False,
    POSITIVE_TOPK_WEIGHT=0.04,
    POSITIVE_TOPK_FRACTION=0.20,
    SMALL_LESION_BOOST_REFERENCE=10000.0,
    SMALL_LESION_BOOST_MAX=1.90,
    AUGMENT=True,
    AUG_FLIP_PROB=0.5,
    AUG_INTENSITY_SCALE=0.04,
    AUG_INTENSITY_SHIFT=0.02,
    AUG_NOISE_STD=0.004,
    DECISION_THRESHOLD=0.50,
    VAL_THRESHOLD_SWEEP=(0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50, 0.55, 0.60, 0.65, 0.70, 0.80),
    WHOLE_BRAIN_VAL_EVERY_N_EPOCHS=1,
    WHOLE_BRAIN_VAL_MAX_CASES=None,
    SAVE_VAL_PREDICTIONS=True,
    NUM_VAL_PREDICTIONS=4,
    EARLY_STOPPING_PATIENCE=6,
    EARLY_STOPPING_MIN_DELTA=0.0003,
    RESTORE_BEST_WEIGHTS=True,
    TARGET_WHOLE_DICE=None,
    FROZEN_LAYER_PREFIXES=("enc1_", "enc2_"),
    FREEZE_BATCHNORM=True,
    FIT_VERBOSE=2,
)

def make_axis_cfg(axis: int):
    name = AXIS_NAMES[axis]
    axis_dir = RUN_DIR / f"axis{axis}_{name}"
    initial_weights = SOURCE_RUN / f"axis{axis}_{name}" / "callbacks" / "best_slice_block.weights.h5"
    if not initial_weights.exists():
        raise FileNotFoundError(initial_weights)
    return seg.SliceBlockTrainingConfig(
        **COMMON_CFG,
        SLICE_AXIS=axis,
        INITIAL_WEIGHTS_PATH=initial_weights,
        MODEL_DIR=axis_dir / "models",
        CALLBACKS_DIR=axis_dir / "callbacks",
    )

axis_cfgs = {axis: make_axis_cfg(axis) for axis in AXES_TO_TRAIN}

print(f"Project root: {PROJECT_ROOT}")
print(f"Source tri-planar run: {SOURCE_RUN}")
print(f"Resume run dir: {RUN_DIR}")
print(f"Training manifest: {FULL_MANIFEST}")
print(f"Source replay weights: {SOURCE_WEIGHT_MAP}")
for axis, cfg in axis_cfgs.items():
    print(f"axis {axis} ({AXIS_NAMES[axis]}): init={cfg.INITIAL_WEIGHTS_PATH}")
    print(f"  frozen prefixes: {cfg.FROZEN_LAYER_PREFIXES} | freeze_batchnorm={cfg.FREEZE_BATCHNORM}")
    print(f"  input per brain: (num_slices, {cfg.input_shape[0]}, {cfg.input_shape[1]}, {cfg.input_shape[2]})")
    print(f"  checkpoints: {cfg.checkpoint_path}")

2026-04-30 14:14:19.769789: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

Project root: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4
Source tri-planar run: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260422_171449_slice_blocks_triplanar_goal08
Resume run dir: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze
Training manifest: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train/manifest.csv
Source replay weights: {'ATLAS-Images-f0d7431e': 3.5, 'ARC-combined-t1-raw-ab0d1794': 1.5, 'Approx-Numeracy-Processed': 1.0}
axis 2 (axial): init=/home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260422_171449_slice_blocks_triplanar_goal08/axis2_axial/callbacks/best_slice_block.weights.h5
  frozen prefixes: ('enc1_', 'enc2_') | freeze_batchnorm=True
  input per brain: (num_slices, 192, 224, 7)
  checkpoints: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis2_axial/callbacks/best_slice_block.weights.h5
axis 0 (sagittal): init=/home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260422_171449_slice_blocks_triplanar_goal08/axis0_sagittal/callbacks/best_slice_block.weights.h5
  frozen prefixes: ('enc1_', 'enc2_') | freeze_batchnorm=True
  input per brain: (num_slices, 224, 192, 7)
  checkpoints: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis0_sagittal/callbacks/best_slice_block.weights.h5
axis 1 (coronal): init=/home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260422_171449_slice_blocks_triplanar_goal08/axis1_coronal/callbacks/best_slice_block.weights.h5
  frozen prefixes: ('enc1_', 'enc2_') | freeze_batchnorm=True
  input per brain: (num_slices, 192, 192, 7)
  checkpoints: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis1_coronal/callbacks/best_slice_block.weights.h5

In [2]:
# Verify checkpoints and inspect the mixed split that will be reused for training + evaluation.
import pandas as pd

reference_cfg = axis_cfgs[2 if 2 in axis_cfgs else AXES_TO_TRAIN[0]]

for axis, cfg in axis_cfgs.items():
    model = seg.build_slice_block_model(cfg)
    model.load_weights(str(cfg.INITIAL_WEIGHTS_PATH))
    seg.apply_trainable_policy(model, cfg)
    trainable_params = int(sum(seg.np.prod(w.shape) for w in model.trainable_weights))
    frozen_params = int(sum(seg.np.prod(w.shape) for w in model.non_trainable_weights))
    print(f"Loaded axis {axis} checkpoint: {cfg.INITIAL_WEIGHTS_PATH}")
    print(f"  total params: {model.count_params():,}")
    print(f"  trainable params after freeze policy: {trainable_params:,}")
    print(f"  non-trainable params after freeze policy: {frozen_params:,}")
    del model
    seg.tf.keras.backend.clear_session()

mixed_cases = seg.load_cases(reference_cfg)
mixed_train_cases, mixed_val_cases, mixed_lesion_sizes = seg.split_cases(mixed_cases, reference_cfg)
size_by_id = {case.case_id: size for case, size in zip(mixed_cases, mixed_lesion_sizes)}
mixed_val_atlas_cases = [case for case in mixed_val_cases if case.source == ATLAS_SLUG]
mixed_val_arc_cases = [case for case in mixed_val_cases if case.source == ARC_SLUG]
mixed_val_approx_cases = [case for case in mixed_val_cases if case.source == APPROX_SLUG]

def split_frame(split_name, split_cases):
    return pd.DataFrame([
        {
            "split": split_name,
            "source": case.source,
            "case_id": case.case_id,
            "lesion_voxels": int(size_by_id[case.case_id]),
            "lesion_group": seg.lesion_size_group(int(size_by_id[case.case_id])),
        }
        for case in split_cases
    ])

split_df = pd.concat([
    split_frame("train", mixed_train_cases),
    split_frame("val", mixed_val_cases),
], ignore_index=True)

print(f"Mixed cases: {len(mixed_cases)}")
print(f"Mixed train/val: {len(mixed_train_cases)} / {len(mixed_val_cases)}")
print(f"Mixed val by source: ATLAS={len(mixed_val_atlas_cases)} ARC={len(mixed_val_arc_cases)} Approx={len(mixed_val_approx_cases)}")
display(split_df.groupby(["split", "source", "lesion_group"]).size().unstack(fill_value=0))

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1777580061.850298  142886 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 22148 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4090, pci bus id: 0000:41:00.0, compute capability: 8.9
I0000 00:00:1777580061.851666  142886 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 22122 MB memory:  -> device: 1, name: NVIDIA GeForce RTX 4090, pci bus id: 0000:61:00.0, compute capability: 8.9
2026-04-30 14:14:22,756 - SliceBlockTrainer - INFO - Applied fine-tune freezing: prefixes=('enc1_', 'enc2_') freeze_batchnorm=True frozen_layers=28/77

Loaded axis 2 checkpoint: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260422_171449_slice_blocks_triplanar_goal08/axis2_axial/callbacks/best_slice_block.weights.h5
  total params: 1,108,081
  trainable params after freeze policy: 1,093,837
  non-trainable params after freeze policy: 14,244

2026-04-30 14:14:23,121 - SliceBlockTrainer - INFO - Applied fine-tune freezing: prefixes=('enc1_', 'enc2_') freeze_batchnorm=True frozen_layers=28/77

Loaded axis 0 checkpoint: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260422_171449_slice_blocks_triplanar_goal08/axis0_sagittal/callbacks/best_slice_block.weights.h5
  total params: 1,108,081
  trainable params after freeze policy: 1,093,837
  non-trainable params after freeze policy: 14,244

2026-04-30 14:14:23,483 - SliceBlockTrainer - INFO - Applied fine-tune freezing: prefixes=('enc1_', 'enc2_') freeze_batchnorm=True frozen_layers=28/77
2026-04-30 14:14:23,599 - SliceBlockTrainer - INFO - Using manifest: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train/manifest.csv
2026-04-30 14:14:23,618 - SliceBlockTrainer - INFO - Loaded 866 cases from manifest

Loaded axis 1 checkpoint: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260422_171449_slice_blocks_triplanar_goal08/axis1_coronal/callbacks/best_slice_block.weights.h5
  total params: 1,108,081
  trainable params after freeze policy: 1,093,837
  non-trainable params after freeze policy: 14,244

2026-04-30 14:16:38,401 - SliceBlockTrainer - INFO - Split cases: train=737 val=129

Mixed cases: 866
Mixed train/val: 737 / 129
Mixed val by source: ATLAS=88 ARC=28 Approx=13

lesion_group                        10000_plus  1000_9999  100_999  1_99  none
split source
train ARC-combined-t1-raw-ab0d1794         144         13        4     0     1
      ATLAS-Images-f0d7431e                186        167      126    14     1
      Approx-Numeracy-Processed             36         19       20     5     1
val   ARC-combined-t1-raw-ab0d1794          25          2        1     0     0
      ATLAS-Images-f0d7431e                 33         30       22     3     0
      Approx-Numeracy-Processed              6          3        3     1     0

In [3]:
# Sanity check one ATLAS validation case under the replay fine-tune config.
sanity_case = mixed_val_atlas_cases[0] if mixed_val_atlas_cases else mixed_val_cases[0]
reference_cfg = axis_cfgs[2 if 2 in axis_cfgs else AXES_TO_TRAIN[0]]
image, mask, _ = seg.load_case_arrays(sanity_case, reference_cfg)
x, y = seg.make_slice_blocks(image, mask, reference_cfg)
model = seg.build_slice_block_model(reference_cfg)
seg.apply_trainable_policy(model, reference_cfg)

print(f"Sanity case: {sanity_case.case_id}")
print(f"Prepared brain: image={image.shape}, mask={mask.shape}")
print(f"One-brain batch: x={x.shape}, y={y.shape}")
print(f"Lesion voxels in sanity case: {int(y.sum())}")
print(f"Model params: {model.count_params():,}")
print(f"Trainable tensors after freeze policy: {len(model.trainable_weights)}")

model.load_weights(str(reference_cfg.INITIAL_WEIGHTS_PATH))
pred = model.predict(x[:4], verbose=0)
print(f"Loaded checkpoint prediction range: min={float(pred.min()):.6f}, max={float(pred.max()):.6f}")

del model
seg.tf.keras.backend.clear_session()

2026-04-30 14:16:39,085 - SliceBlockTrainer - INFO - Applied fine-tune freezing: prefixes=('enc1_', 'enc2_') freeze_batchnorm=True frozen_layers=28/77

Sanity case: ATLAS-Images-f0d7431e__ATLAS-Images-f0d7431e__sub-r011s017_ses-1_space-MNI152NLin2009aSym_T1w_MNI_norm
Prepared brain: image=(192, 224, 192), mask=(192, 224, 192)
One-brain batch: x=(192, 192, 224, 7), y=(192, 192, 224, 1)
Lesion voxels in sanity case: 823
Model params: 1,108,081
Trainable tensors after freeze policy: 16

2026-04-30 14:16:39.449048: I external/local_xla/xla/service/service.cc:163] XLA service 0x7d8ff80481c0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2026-04-30 14:16:39.449075: I external/local_xla/xla/service/service.cc:171]   StreamExecutor device (0): NVIDIA GeForce RTX 4090, Compute Capability 8.9
2026-04-30 14:16:39.449082: I external/local_xla/xla/service/service.cc:171]   StreamExecutor device (1): NVIDIA GeForce RTX 4090, Compute Capability 8.9
2026-04-30 14:16:39.476331: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2026-04-30 14:16:39.604007: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:473] Loaded cuDNN version 91001

Loaded checkpoint prediction range: min=0.000210, max=0.001093

I0000 00:00:1777580201.153297  143191 device_compiler.h:196] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

In [4]:
# Launch ATLAS-heavy replay fine-tune for each axis.
# This keeps replay, but loosens the freeze policy so enc3 and deeper layers can adapt.
histories = {}
for axis, cfg in axis_cfgs.items():
    print("=" * 100)
    print(f"ATLAS-heavy replay fine-tune v2: axis {axis} ({AXIS_NAMES[axis]})")
    print(f"Callbacks dir: {cfg.CALLBACKS_DIR}")
    histories[axis] = seg.train_slice_block_model(cfg)
    seg.tf.keras.backend.clear_session()
    print(f"Finished axis {axis}. Best checkpoint: {cfg.checkpoint_path}")

2026-04-30 14:16:41,305 - SliceBlockTrainer - WARNING - Could not set memory growth on PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'): Physical devices cannot be modified after being initialized
2026-04-30 14:16:41,306 - SliceBlockTrainer - WARNING - Could not set memory growth on PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU'): Physical devices cannot be modified after being initialized
2026-04-30 14:16:41,306 - SliceBlockTrainer - INFO - Using manifest: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train/manifest.csv
2026-04-30 14:16:41,324 - SliceBlockTrainer - INFO - Loaded 866 cases from manifest

====================================================================================================
ATLAS-heavy replay fine-tune v2: axis 2 (axial)
Callbacks dir: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis2_axial/callbacks

2026-04-30 14:18:37,943 - SliceBlockTrainer - INFO - Split cases: train=737 val=129
2026-04-30 14:18:37,958 - SliceBlockTrainer - INFO - Balanced case sampling enabled: source_balanced=True source_weights={'ATLAS-Images-f0d7431e': 3.5, 'ARC-combined-t1-raw-ab0d1794': 1.5, 'Approx-Numeracy-Processed': 1.0} size_aware=True size_edges=(100, 1000, 10000) size_probs=(0.42, 0.28, 0.18, 0.12)
2026-04-30 14:18:38,152 - SliceBlockTrainer - INFO - Loading initial weights from /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260422_171449_slice_blocks_triplanar_goal08/axis2_axial/callbacks/best_slice_block.weights.h5
2026-04-30 14:18:38,251 - SliceBlockTrainer - INFO - Copied initial weights to /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis2_axial/callbacks/baseline_initial.weights.h5
2026-04-30 14:18:38,252 - SliceBlockTrainer - INFO - Applied fine-tune freezing: prefixes=('enc1_', 'enc2_') freeze_batchnorm=True frozen_layers=28/77
2026-04-30 14:18:38,256 - SliceBlockTrainer - INFO - Model built: SliceBlock2p5D_UNet params=1108081 input=(192, 224, 7)
2026-04-30 14:18:38,256 - SliceBlockTrainer - INFO - Slice-block design: one brain per step, block_depth=7 slice_axis=2 stride=1 train_steps=420 val_steps=18
2026-04-30 14:18:38,257 - SliceBlockTrainer - INFO - Loss focus: lesion_slice_weight=1.350 empty_slice_weight=0.950 small_lesion_boost=(ref=10000.0 max=1.90) dice_lesion_only=False positive_topk_weight=0.040 topk_fraction=0.200 tversky=(alpha=0.580 beta=0.420) threshold=0.500

Epoch 1/18

E0000 00:00:1777580320.729455  142886 meta_optimizer.cc:967] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape inStatefulPartitionedCall/SliceBlock2p5D_UNet_1/enc1_dropout_1/stateless_dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer
2026-04-30 14:32:05,752 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 14:32:35,822 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 14:33:05,850 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 14:33:35,966 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 14:34:05,947 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 14:34:35,912 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 14:35:05,991 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 14:35:36,101 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 14:35:38,008 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 14:35:38,012 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 0: soft=0.22176 hard@0.50=0.25894 best_thr_med=0.80 best_thr_score=0.29705 pred_max_p90=0.9953

Epoch 1: val_whole_dice_hard_best_thr_score improved from None to 0.29705, saving model to /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis2_axial/callbacks/best_slice_block.weights.h5
420/420 - 1029s - 2s/step - dice_coefficient: 0.0518 - foreground_fraction: 0.0075 - hard_dice_metric: 0.5783 - loss: 0.6292 - val_dice_coefficient: 0.0843 - val_foreground_fraction: 0.0084 - val_hard_dice_metric: 0.5344 - val_loss: 0.6642 - val_whole_dice_soft_macro: 0.2218 - val_whole_dice_hard: 0.2589 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.2971
Epoch 2/18

2026-04-30 14:49:00,192 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 14:49:28,410 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 14:49:57,127 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 14:50:25,811 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 14:50:54,621 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 14:51:23,598 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 14:51:52,350 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 14:52:21,427 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 14:52:23,233 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 14:52:23,236 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 1: soft=0.21222 hard@0.50=0.24762 best_thr_med=0.80 best_thr_score=0.28720 pred_max_p90=0.9947

Epoch 2: val_whole_dice_hard_best_thr_score did not improve from 0.29705
420/420 - 996s - 2s/step - dice_coefficient: 0.0463 - foreground_fraction: 0.0074 - hard_dice_metric: 0.5343 - loss: 0.6411 - val_dice_coefficient: 0.0831 - val_foreground_fraction: 0.0092 - val_hard_dice_metric: 0.5041 - val_loss: 0.6603 - val_whole_dice_soft_macro: 0.2122 - val_whole_dice_hard: 0.2476 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.2872
Epoch 3/18

2026-04-30 15:05:34,692 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 15:06:04,085 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 15:06:33,488 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 15:07:02,799 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 15:07:32,069 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 15:08:01,496 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 15:08:30,805 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 15:09:00,014 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 15:09:01,843 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 15:09:01,847 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 2: soft=0.21948 hard@0.50=0.26848 best_thr_med=0.80 best_thr_score=0.31341 pred_max_p90=0.9932

Epoch 3: val_whole_dice_hard_best_thr_score improved from 0.29705 to 0.31341, saving model to /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis2_axial/callbacks/best_slice_block.weights.h5
420/420 - 1007s - 2s/step - dice_coefficient: 0.0415 - foreground_fraction: 0.0077 - hard_dice_metric: 0.5308 - loss: 0.6515 - val_dice_coefficient: 0.0836 - val_foreground_fraction: 0.0078 - val_hard_dice_metric: 0.5493 - val_loss: 0.6621 - val_whole_dice_soft_macro: 0.2195 - val_whole_dice_hard: 0.2685 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3134
Epoch 4/18

2026-04-30 15:22:23,792 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 15:22:52,844 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 15:23:21,983 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 15:23:51,102 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 15:24:20,218 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 15:24:49,478 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 15:25:18,664 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 15:25:47,917 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 15:25:49,754 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 15:25:49,758 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 3: soft=0.20659 hard@0.50=0.24709 best_thr_med=0.80 best_thr_score=0.29131 pred_max_p90=0.9929

Epoch 4: val_whole_dice_hard_best_thr_score did not improve from 0.31341
420/420 - 999s - 2s/step - dice_coefficient: 0.0466 - foreground_fraction: 0.0073 - hard_dice_metric: 0.5293 - loss: 0.6385 - val_dice_coefficient: 0.0812 - val_foreground_fraction: 0.0093 - val_hard_dice_metric: 0.5010 - val_loss: 0.6580 - val_whole_dice_soft_macro: 0.2066 - val_whole_dice_hard: 0.2471 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.2913
Epoch 5/18

2026-04-30 15:39:02,462 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 15:39:32,052 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 15:40:01,787 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 15:40:31,516 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 15:41:01,173 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 15:41:30,894 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 15:42:00,485 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 15:42:30,195 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 15:42:32,053 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 15:42:32,057 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 4: soft=0.20082 hard@0.50=0.24281 best_thr_med=0.80 best_thr_score=0.28853 pred_max_p90=0.9923

Epoch 5: val_whole_dice_hard_best_thr_score did not improve from 0.31341
420/420 - 1002s - 2s/step - dice_coefficient: 0.0448 - foreground_fraction: 0.0079 - hard_dice_metric: 0.5396 - loss: 0.6513 - val_dice_coefficient: 0.0806 - val_foreground_fraction: 0.0097 - val_hard_dice_metric: 0.5057 - val_loss: 0.6555 - val_whole_dice_soft_macro: 0.2008 - val_whole_dice_hard: 0.2428 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.2885
Epoch 6/18

2026-04-30 15:55:42,401 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 15:56:11,465 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 15:56:40,483 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 15:57:09,503 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 15:57:38,588 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 15:58:07,678 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 15:58:36,658 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 15:59:05,781 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 15:59:07,600 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 15:59:07,604 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 5: soft=0.22166 hard@0.50=0.26545 best_thr_med=0.80 best_thr_score=0.30942 pred_max_p90=0.9915

Epoch 6: val_whole_dice_hard_best_thr_score did not improve from 0.31341
420/420 - 996s - 2s/step - dice_coefficient: 0.0478 - foreground_fraction: 0.0080 - hard_dice_metric: 0.5366 - loss: 0.6425 - val_dice_coefficient: 0.0839 - val_foreground_fraction: 0.0082 - val_hard_dice_metric: 0.5436 - val_loss: 0.6585 - val_whole_dice_soft_macro: 0.2217 - val_whole_dice_hard: 0.2655 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3094
Epoch 7/18

2026-04-30 16:12:15,451 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 16:12:44,802 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 16:13:14,242 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 16:13:43,565 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 16:14:12,939 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 16:14:42,397 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 16:15:11,816 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 16:15:41,224 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 16:15:43,048 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 16:15:43,052 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 6: soft=0.22899 hard@0.50=0.26893 best_thr_med=0.80 best_thr_score=0.31280 pred_max_p90=0.9913

Epoch 7: val_whole_dice_hard_best_thr_score did not improve from 0.31341
420/420 - 995s - 2s/step - dice_coefficient: 0.0456 - foreground_fraction: 0.0074 - hard_dice_metric: 0.5480 - loss: 0.6410 - val_dice_coefficient: 0.0859 - val_foreground_fraction: 0.0081 - val_hard_dice_metric: 0.5546 - val_loss: 0.6603 - val_whole_dice_soft_macro: 0.2290 - val_whole_dice_hard: 0.2689 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3128
Epoch 8/18

2026-04-30 16:28:57,311 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 16:29:26,471 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 16:29:55,609 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 16:30:24,881 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 16:30:54,134 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 16:31:23,510 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 16:31:52,829 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 16:32:22,096 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 16:32:23,949 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 16:32:23,953 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 7: soft=0.23050 hard@0.50=0.26937 best_thr_med=0.80 best_thr_score=0.31265 pred_max_p90=0.9912

Epoch 8: val_whole_dice_hard_best_thr_score did not improve from 0.31341
420/420 - 1001s - 2s/step - dice_coefficient: 0.0542 - foreground_fraction: 0.0084 - hard_dice_metric: 0.5578 - loss: 0.6410 - val_dice_coefficient: 0.0857 - val_foreground_fraction: 0.0082 - val_hard_dice_metric: 0.5616 - val_loss: 0.6593 - val_whole_dice_soft_macro: 0.2305 - val_whole_dice_hard: 0.2694 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3127
Epoch 9/18

2026-04-30 16:45:34,738 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 16:46:04,021 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 16:46:33,398 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 16:47:02,710 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 16:47:32,049 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 16:48:01,434 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 16:48:30,696 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 16:48:59,827 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 16:49:01,652 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 16:49:01,656 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 8: soft=0.22716 hard@0.50=0.27263 best_thr_med=0.80 best_thr_score=0.31781 pred_max_p90=0.9908

Epoch 9: val_whole_dice_hard_best_thr_score improved from 0.31341 to 0.31781, saving model to /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis2_axial/callbacks/best_slice_block.weights.h5
420/420 - 1006s - 2s/step - dice_coefficient: 0.0500 - foreground_fraction: 0.0083 - hard_dice_metric: 0.5412 - loss: 0.6502 - val_dice_coefficient: 0.0844 - val_foreground_fraction: 0.0079 - val_hard_dice_metric: 0.5653 - val_loss: 0.6578 - val_whole_dice_soft_macro: 0.2272 - val_whole_dice_hard: 0.2726 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3178
Epoch 10/18

2026-04-30 17:02:20,296 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 17:02:49,449 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 17:03:18,693 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 17:03:47,976 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 17:04:17,236 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 17:04:46,613 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 17:05:15,979 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 17:05:45,178 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 17:05:47,004 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 17:05:47,009 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 9: soft=0.21868 hard@0.50=0.26166 best_thr_med=0.80 best_thr_score=0.30698 pred_max_p90=0.9910

Epoch 10: val_whole_dice_hard_best_thr_score did not improve from 0.31781
420/420 - 997s - 2s/step - dice_coefficient: 0.0561 - foreground_fraction: 0.0083 - hard_dice_metric: 0.5467 - loss: 0.6418 - val_dice_coefficient: 0.0829 - val_foreground_fraction: 0.0086 - val_hard_dice_metric: 0.5497 - val_loss: 0.6541 - val_whole_dice_soft_macro: 0.2187 - val_whole_dice_hard: 0.2617 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3070
Epoch 11/18

2026-04-30 17:18:56,908 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 17:19:26,016 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 17:19:55,166 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 17:20:24,439 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 17:20:53,585 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 17:21:22,836 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 17:21:52,080 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 17:22:21,175 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 17:22:22,979 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 17:22:22,983 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 10: soft=0.22224 hard@0.50=0.26586 best_thr_med=0.80 best_thr_score=0.31131 pred_max_p90=0.9904

Epoch 11: val_whole_dice_hard_best_thr_score did not improve from 0.31781
420/420 - 996s - 2s/step - dice_coefficient: 0.0423 - foreground_fraction: 0.0077 - hard_dice_metric: 0.5495 - loss: 0.6468 - val_dice_coefficient: 0.0839 - val_foreground_fraction: 0.0083 - val_hard_dice_metric: 0.5508 - val_loss: 0.6553 - val_whole_dice_soft_macro: 0.2222 - val_whole_dice_hard: 0.2659 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3113
Epoch 12/18

2026-04-30 17:35:34,037 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 17:36:03,250 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 17:36:32,505 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 17:37:01,795 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 17:37:31,041 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 17:38:00,345 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 17:38:29,522 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 17:38:58,738 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 17:39:00,549 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 17:39:00,553 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 11: soft=0.22598 hard@0.50=0.26614 best_thr_med=0.80 best_thr_score=0.31087 pred_max_p90=0.9903

Epoch 12: val_whole_dice_hard_best_thr_score did not improve from 0.31781
420/420 - 998s - 2s/step - dice_coefficient: 0.0480 - foreground_fraction: 0.0080 - hard_dice_metric: 0.5566 - loss: 0.6356 - val_dice_coefficient: 0.0849 - val_foreground_fraction: 0.0084 - val_hard_dice_metric: 0.5624 - val_loss: 0.6556 - val_whole_dice_soft_macro: 0.2260 - val_whole_dice_hard: 0.2661 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3109
Epoch 13/18

2026-04-30 17:52:13,997 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 17:52:43,532 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 17:53:13,039 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 17:53:42,575 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 17:54:12,103 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 17:54:41,708 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 17:55:11,292 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 17:55:40,888 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 17:55:42,718 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 17:55:42,722 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 12: soft=0.21695 hard@0.50=0.25567 best_thr_med=0.80 best_thr_score=0.30148 pred_max_p90=0.9899

Epoch 13: val_whole_dice_hard_best_thr_score did not improve from 0.31781
420/420 - 1002s - 2s/step - dice_coefficient: 0.0433 - foreground_fraction: 0.0086 - hard_dice_metric: 0.5432 - loss: 0.6419 - val_dice_coefficient: 0.0831 - val_foreground_fraction: 0.0089 - val_hard_dice_metric: 0.5233 - val_loss: 0.6545 - val_whole_dice_soft_macro: 0.2169 - val_whole_dice_hard: 0.2557 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3015
Epoch 14/18

2026-04-30 18:08:52,650 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 18:09:22,375 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 18:09:52,309 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 18:10:22,500 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 18:10:52,656 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 18:11:23,051 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 18:11:53,279 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 18:12:23,508 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 18:12:25,383 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 18:12:25,387 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 13: soft=0.22333 hard@0.50=0.26272 best_thr_med=0.80 best_thr_score=0.30824 pred_max_p90=0.9898

Epoch 14: val_whole_dice_hard_best_thr_score did not improve from 0.31781
420/420 - 1003s - 2s/step - dice_coefficient: 0.0490 - foreground_fraction: 0.0078 - hard_dice_metric: 0.5362 - loss: 0.6308 - val_dice_coefficient: 0.0844 - val_foreground_fraction: 0.0085 - val_hard_dice_metric: 0.5484 - val_loss: 0.6559 - val_whole_dice_soft_macro: 0.2233 - val_whole_dice_hard: 0.2627 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3082
Epoch 15/18

2026-04-30 18:25:33,559 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 18:26:03,125 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 18:26:32,988 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 18:27:02,891 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 18:27:32,694 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 18:28:02,520 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 18:28:32,354 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 18:29:02,784 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 18:29:04,702 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 18:29:04,706 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 14: soft=0.22473 hard@0.50=0.26451 best_thr_med=0.80 best_thr_score=0.31039 pred_max_p90=0.9897

Epoch 15: val_whole_dice_hard_best_thr_score did not improve from 0.31781
420/420 - 999s - 2s/step - dice_coefficient: 0.0567 - foreground_fraction: 0.0085 - hard_dice_metric: 0.5603 - loss: 0.6324 - val_dice_coefficient: 0.0849 - val_foreground_fraction: 0.0085 - val_hard_dice_metric: 0.5557 - val_loss: 0.6560 - val_whole_dice_soft_macro: 0.2247 - val_whole_dice_hard: 0.2645 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3104
Epoch 15: early stopping
Restoring model weights from the end of the best epoch: 9.

2026-04-30 18:29:05,084 - SliceBlockTrainer - WARNING - Could not set memory growth on PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'): Physical devices cannot be modified after being initialized
2026-04-30 18:29:05,085 - SliceBlockTrainer - WARNING - Could not set memory growth on PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU'): Physical devices cannot be modified after being initialized
2026-04-30 18:29:05,087 - SliceBlockTrainer - INFO - Using manifest: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train/manifest.csv
2026-04-30 18:29:05,105 - SliceBlockTrainer - INFO - Loaded 866 cases from manifest

Finished axis 2. Best checkpoint: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis2_axial/callbacks/best_slice_block.weights.h5
====================================================================================================
ATLAS-heavy replay fine-tune v2: axis 0 (sagittal)
Callbacks dir: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis0_sagittal/callbacks

2026-04-30 18:30:03,976 - SliceBlockTrainer - INFO - Split cases: train=737 val=129
2026-04-30 18:30:03,990 - SliceBlockTrainer - INFO - Balanced case sampling enabled: source_balanced=True source_weights={'ATLAS-Images-f0d7431e': 3.5, 'ARC-combined-t1-raw-ab0d1794': 1.5, 'Approx-Numeracy-Processed': 1.0} size_aware=True size_edges=(100, 1000, 10000) size_probs=(0.42, 0.28, 0.18, 0.12)
2026-04-30 18:30:04,183 - SliceBlockTrainer - INFO - Loading initial weights from /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260422_171449_slice_blocks_triplanar_goal08/axis0_sagittal/callbacks/best_slice_block.weights.h5
2026-04-30 18:30:04,280 - SliceBlockTrainer - INFO - Copied initial weights to /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis0_sagittal/callbacks/baseline_initial.weights.h5
2026-04-30 18:30:04,281 - SliceBlockTrainer - INFO - Applied fine-tune freezing: prefixes=('enc1_', 'enc2_') freeze_batchnorm=True frozen_layers=28/77
2026-04-30 18:30:04,285 - SliceBlockTrainer - INFO - Model built: SliceBlock2p5D_UNet params=1108081 input=(224, 192, 7)
2026-04-30 18:30:04,285 - SliceBlockTrainer - INFO - Slice-block design: one brain per step, block_depth=7 slice_axis=0 stride=1 train_steps=420 val_steps=18
2026-04-30 18:30:04,285 - SliceBlockTrainer - INFO - Loss focus: lesion_slice_weight=1.350 empty_slice_weight=0.950 small_lesion_boost=(ref=10000.0 max=1.90) dice_lesion_only=False positive_topk_weight=0.040 topk_fraction=0.200 tversky=(alpha=0.580 beta=0.420) threshold=0.500

Epoch 1/18

E0000 00:00:1777595406.766564  142886 meta_optimizer.cc:967] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape inStatefulPartitionedCall/SliceBlock2p5D_UNet_1/enc1_dropout_1/stateless_dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer
2026-04-30 18:43:23,340 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 18:43:44,988 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 18:44:06,712 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 18:44:28,498 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 18:44:50,609 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 18:45:13,127 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 18:45:35,553 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 18:45:57,820 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 18:45:59,222 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 18:45:59,227 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 0: soft=0.23652 hard@0.50=0.27686 best_thr_med=0.80 best_thr_score=0.31730 pred_max_p90=0.9991

Epoch 1: val_whole_dice_hard_best_thr_score improved from None to 0.31730, saving model to /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis0_sagittal/callbacks/best_slice_block.weights.h5
420/420 - 963s - 2s/step - dice_coefficient: 0.0368 - foreground_fraction: 0.0070 - hard_dice_metric: 0.6092 - loss: 0.6325 - val_dice_coefficient: 0.0576 - val_foreground_fraction: 0.0077 - val_hard_dice_metric: 0.5980 - val_loss: 0.6884 - val_whole_dice_soft_macro: 0.2365 - val_whole_dice_hard: 0.2769 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3173
Epoch 2/18

2026-04-30 18:59:10,598 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 18:59:31,569 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 18:59:52,491 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 19:00:13,562 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 19:00:34,646 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 19:00:55,670 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 19:01:16,763 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 19:01:37,889 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 19:01:39,199 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 19:01:39,203 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 1: soft=0.23509 hard@0.50=0.28085 best_thr_med=0.80 best_thr_score=0.32089 pred_max_p90=0.9992

Epoch 2: val_whole_dice_hard_best_thr_score improved from 0.31730 to 0.32089, saving model to /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis0_sagittal/callbacks/best_slice_block.weights.h5
420/420 - 940s - 2s/step - dice_coefficient: 0.0342 - foreground_fraction: 0.0073 - hard_dice_metric: 0.5412 - loss: 0.6427 - val_dice_coefficient: 0.0575 - val_foreground_fraction: 0.0074 - val_hard_dice_metric: 0.5720 - val_loss: 0.6901 - val_whole_dice_soft_macro: 0.2351 - val_whole_dice_hard: 0.2808 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3209
Epoch 3/18

2026-04-30 19:14:52,794 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 19:15:13,917 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 19:15:35,136 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 19:15:56,296 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 19:16:17,344 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 19:16:38,468 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 19:16:59,598 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 19:17:20,772 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 19:17:22,108 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 19:17:22,112 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 2: soft=0.21994 hard@0.50=0.27068 best_thr_med=0.70 best_thr_score=0.31383 pred_max_p90=0.9993

Epoch 3: val_whole_dice_hard_best_thr_score did not improve from 0.32089
420/420 - 936s - 2s/step - dice_coefficient: 0.0301 - foreground_fraction: 0.0069 - hard_dice_metric: 0.5327 - loss: 0.6565 - val_dice_coefficient: 0.0558 - val_foreground_fraction: 0.0076 - val_hard_dice_metric: 0.5384 - val_loss: 0.6900 - val_whole_dice_soft_macro: 0.2199 - val_whole_dice_hard: 0.2707 - val_whole_dice_hard_best_thr: 0.7000 - val_whole_dice_hard_best_thr_score: 0.3138
Epoch 4/18

2026-04-30 19:30:25,905 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 19:30:46,997 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 19:31:08,165 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 19:31:29,280 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 19:31:50,347 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 19:32:11,540 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 19:32:32,645 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 19:32:53,789 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 19:32:55,107 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 19:32:55,111 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 3: soft=0.20868 hard@0.50=0.24883 best_thr_med=0.80 best_thr_score=0.29574 pred_max_p90=0.9995

Epoch 4: val_whole_dice_hard_best_thr_score did not improve from 0.32089
420/420 - 933s - 2s/step - dice_coefficient: 0.0338 - foreground_fraction: 0.0071 - hard_dice_metric: 0.5311 - loss: 0.6463 - val_dice_coefficient: 0.0549 - val_foreground_fraction: 0.0088 - val_hard_dice_metric: 0.4944 - val_loss: 0.6846 - val_whole_dice_soft_macro: 0.2087 - val_whole_dice_hard: 0.2488 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.2957
Epoch 5/18

2026-04-30 19:45:59,610 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 19:46:20,735 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 19:46:41,635 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 19:47:02,553 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 19:47:23,556 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 19:47:44,678 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 19:48:05,799 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 19:48:26,965 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 19:48:28,247 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 19:48:28,252 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 4: soft=0.20802 hard@0.50=0.25643 best_thr_med=0.80 best_thr_score=0.30271 pred_max_p90=0.9996

Epoch 5: val_whole_dice_hard_best_thr_score did not improve from 0.32089
420/420 - 933s - 2s/step - dice_coefficient: 0.0311 - foreground_fraction: 0.0070 - hard_dice_metric: 0.5187 - loss: 0.6657 - val_dice_coefficient: 0.0554 - val_foreground_fraction: 0.0082 - val_hard_dice_metric: 0.4942 - val_loss: 0.6833 - val_whole_dice_soft_macro: 0.2080 - val_whole_dice_hard: 0.2564 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3027
Epoch 6/18

2026-04-30 20:01:36,618 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 20:01:58,319 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 20:02:20,201 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 20:02:41,931 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 20:03:03,614 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 20:03:25,422 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 20:03:47,096 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 20:04:08,926 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 20:04:10,270 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 20:04:10,275 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 5: soft=0.23758 hard@0.50=0.28779 best_thr_med=0.70 best_thr_score=0.32195 pred_max_p90=0.9994

Epoch 6: val_whole_dice_hard_best_thr_score improved from 0.32089 to 0.32195, saving model to /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis0_sagittal/callbacks/best_slice_block.weights.h5
420/420 - 949s - 2s/step - dice_coefficient: 0.0350 - foreground_fraction: 0.0072 - hard_dice_metric: 0.5238 - loss: 0.6535 - val_dice_coefficient: 0.0577 - val_foreground_fraction: 0.0061 - val_hard_dice_metric: 0.5977 - val_loss: 0.6991 - val_whole_dice_soft_macro: 0.2376 - val_whole_dice_hard: 0.2878 - val_whole_dice_hard_best_thr: 0.7000 - val_whole_dice_hard_best_thr_score: 0.3219
Epoch 7/18

2026-04-30 20:17:21,218 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 20:17:42,273 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 20:18:03,217 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 20:18:24,119 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 20:18:45,024 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 20:19:05,915 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 20:19:26,788 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 20:19:47,663 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 20:19:48,953 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 20:19:48,957 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 6: soft=0.23862 hard@0.50=0.28402 best_thr_med=0.70 best_thr_score=0.31925 pred_max_p90=0.9995

Epoch 7: val_whole_dice_hard_best_thr_score did not improve from 0.32195
420/420 - 931s - 2s/step - dice_coefficient: 0.0314 - foreground_fraction: 0.0062 - hard_dice_metric: 0.5201 - loss: 0.6608 - val_dice_coefficient: 0.0584 - val_foreground_fraction: 0.0063 - val_hard_dice_metric: 0.5707 - val_loss: 0.6998 - val_whole_dice_soft_macro: 0.2386 - val_whole_dice_hard: 0.2840 - val_whole_dice_hard_best_thr: 0.7000 - val_whole_dice_hard_best_thr_score: 0.3193
Epoch 8/18

2026-04-30 20:32:54,572 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 20:33:15,371 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 20:33:36,286 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 20:33:57,099 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 20:34:17,996 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 20:34:38,859 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 20:34:59,764 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 20:35:20,657 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 20:35:21,976 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 20:35:21,981 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 7: soft=0.22209 hard@0.50=0.26686 best_thr_med=0.80 best_thr_score=0.30358 pred_max_p90=0.9996

Epoch 8: val_whole_dice_hard_best_thr_score did not improve from 0.32195
420/420 - 933s - 2s/step - dice_coefficient: 0.0365 - foreground_fraction: 0.0080 - hard_dice_metric: 0.4975 - loss: 0.6619 - val_dice_coefficient: 0.0565 - val_foreground_fraction: 0.0069 - val_hard_dice_metric: 0.4842 - val_loss: 0.6940 - val_whole_dice_soft_macro: 0.2221 - val_whole_dice_hard: 0.2669 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3036
Epoch 9/18

2026-04-30 20:48:28,197 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 20:48:49,050 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 20:49:09,892 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 20:49:30,788 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 20:49:51,668 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 20:50:12,567 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 20:50:33,541 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 20:50:54,407 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 20:50:55,694 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 20:50:55,698 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 8: soft=0.23099 hard@0.50=0.27810 best_thr_med=0.65 best_thr_score=0.31198 pred_max_p90=0.9995

Epoch 9: val_whole_dice_hard_best_thr_score did not improve from 0.32195
420/420 - 934s - 2s/step - dice_coefficient: 0.0338 - foreground_fraction: 0.0077 - hard_dice_metric: 0.4735 - loss: 0.6718 - val_dice_coefficient: 0.0568 - val_foreground_fraction: 0.0057 - val_hard_dice_metric: 0.5342 - val_loss: 0.7072 - val_whole_dice_soft_macro: 0.2310 - val_whole_dice_hard: 0.2781 - val_whole_dice_hard_best_thr: 0.6500 - val_whole_dice_hard_best_thr_score: 0.3120
Epoch 10/18

2026-04-30 21:04:03,279 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 21:04:24,243 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 21:04:45,164 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 21:05:06,326 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 21:05:27,451 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 21:05:48,572 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 21:06:09,658 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 21:06:30,805 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 21:06:32,134 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 21:06:32,138 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 9: soft=0.22520 hard@0.50=0.26847 best_thr_med=0.80 best_thr_score=0.30535 pred_max_p90=0.9995

Epoch 10: val_whole_dice_hard_best_thr_score did not improve from 0.32195
420/420 - 936s - 2s/step - dice_coefficient: 0.0372 - foreground_fraction: 0.0089 - hard_dice_metric: 0.4559 - loss: 0.6659 - val_dice_coefficient: 0.0562 - val_foreground_fraction: 0.0067 - val_hard_dice_metric: 0.5182 - val_loss: 0.6987 - val_whole_dice_soft_macro: 0.2252 - val_whole_dice_hard: 0.2685 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3054
Epoch 11/18

2026-04-30 21:19:39,554 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 21:20:01,399 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 21:20:23,461 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 21:20:45,393 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 21:21:07,281 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 21:21:29,086 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 21:21:50,946 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 21:22:12,901 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 21:22:14,265 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 21:22:14,269 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 10: soft=0.20579 hard@0.50=0.24807 best_thr_med=0.80 best_thr_score=0.28851 pred_max_p90=0.9994

Epoch 11: val_whole_dice_hard_best_thr_score did not improve from 0.32195
420/420 - 942s - 2s/step - dice_coefficient: 0.0287 - foreground_fraction: 0.0071 - hard_dice_metric: 0.4963 - loss: 0.6630 - val_dice_coefficient: 0.0546 - val_foreground_fraction: 0.0080 - val_hard_dice_metric: 0.4416 - val_loss: 0.6923 - val_whole_dice_soft_macro: 0.2058 - val_whole_dice_hard: 0.2481 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.2885
Epoch 12/18

2026-04-30 21:35:22,927 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 21:35:44,641 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 21:36:06,879 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 21:36:29,097 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 21:36:51,337 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 21:37:13,513 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 21:37:35,893 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 21:37:58,222 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 21:37:59,632 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 21:37:59,637 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 11: soft=0.23404 hard@0.50=0.27817 best_thr_med=0.70 best_thr_score=0.30953 pred_max_p90=0.9994

Epoch 12: val_whole_dice_hard_best_thr_score did not improve from 0.32195
420/420 - 945s - 2s/step - dice_coefficient: 0.0332 - foreground_fraction: 0.0085 - hard_dice_metric: 0.4819 - loss: 0.6537 - val_dice_coefficient: 0.0553 - val_foreground_fraction: 0.0064 - val_hard_dice_metric: 0.5726 - val_loss: 0.7096 - val_whole_dice_soft_macro: 0.2340 - val_whole_dice_hard: 0.2782 - val_whole_dice_hard_best_thr: 0.7000 - val_whole_dice_hard_best_thr_score: 0.3095
Epoch 12: early stopping
Restoring model weights from the end of the best epoch: 6.

2026-04-30 21:38:00,043 - SliceBlockTrainer - WARNING - Could not set memory growth on PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'): Physical devices cannot be modified after being initialized
2026-04-30 21:38:00,046 - SliceBlockTrainer - WARNING - Could not set memory growth on PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU'): Physical devices cannot be modified after being initialized
2026-04-30 21:38:00,048 - SliceBlockTrainer - INFO - Using manifest: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/data/splits/90_10_random/train/manifest.csv
2026-04-30 21:38:00,067 - SliceBlockTrainer - INFO - Loaded 866 cases from manifest

Finished axis 0. Best checkpoint: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis0_sagittal/callbacks/best_slice_block.weights.h5
====================================================================================================
ATLAS-heavy replay fine-tune v2: axis 1 (coronal)
Callbacks dir: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis1_coronal/callbacks

2026-04-30 21:38:59,784 - SliceBlockTrainer - INFO - Split cases: train=737 val=129
2026-04-30 21:38:59,799 - SliceBlockTrainer - INFO - Balanced case sampling enabled: source_balanced=True source_weights={'ATLAS-Images-f0d7431e': 3.5, 'ARC-combined-t1-raw-ab0d1794': 1.5, 'Approx-Numeracy-Processed': 1.0} size_aware=True size_edges=(100, 1000, 10000) size_probs=(0.42, 0.28, 0.18, 0.12)
2026-04-30 21:39:00,000 - SliceBlockTrainer - INFO - Loading initial weights from /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260422_171449_slice_blocks_triplanar_goal08/axis1_coronal/callbacks/best_slice_block.weights.h5
2026-04-30 21:39:00,103 - SliceBlockTrainer - INFO - Copied initial weights to /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis1_coronal/callbacks/baseline_initial.weights.h5
2026-04-30 21:39:00,104 - SliceBlockTrainer - INFO - Applied fine-tune freezing: prefixes=('enc1_', 'enc2_') freeze_batchnorm=True frozen_layers=28/77
2026-04-30 21:39:00,109 - SliceBlockTrainer - INFO - Model built: SliceBlock2p5D_UNet params=1108081 input=(192, 192, 7)
2026-04-30 21:39:00,109 - SliceBlockTrainer - INFO - Slice-block design: one brain per step, block_depth=7 slice_axis=1 stride=1 train_steps=420 val_steps=18
2026-04-30 21:39:00,110 - SliceBlockTrainer - INFO - Loss focus: lesion_slice_weight=1.350 empty_slice_weight=0.950 small_lesion_boost=(ref=10000.0 max=1.90) dice_lesion_only=False positive_topk_weight=0.040 topk_fraction=0.200 tversky=(alpha=0.580 beta=0.420) threshold=0.500

Epoch 1/18

E0000 00:00:1777606742.585138  142886 meta_optimizer.cc:967] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape inStatefulPartitionedCall/SliceBlock2p5D_UNet_1/enc1_dropout_1/stateless_dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer
2026-04-30 21:52:18,536 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 21:52:42,716 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 21:53:06,766 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 21:53:31,032 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 21:53:55,162 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 21:54:19,557 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 21:54:43,962 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 21:55:08,471 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 21:55:09,978 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 21:55:09,982 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 0: soft=0.28023 hard@0.50=0.31455 best_thr_med=0.80 best_thr_score=0.34880 pred_max_p90=0.9941

Epoch 1: val_whole_dice_hard_best_thr_score improved from None to 0.34880, saving model to /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis1_coronal/callbacks/best_slice_block.weights.h5
420/420 - 978s - 2s/step - dice_coefficient: 0.0587 - foreground_fraction: 0.0061 - hard_dice_metric: 0.6635 - loss: 0.6098 - val_dice_coefficient: 0.0817 - val_foreground_fraction: 0.0067 - val_hard_dice_metric: 0.6281 - val_loss: 0.6735 - val_whole_dice_soft_macro: 0.2802 - val_whole_dice_hard: 0.3146 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3488
Epoch 2/18

2026-04-30 22:08:28,726 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 22:08:53,179 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 22:09:17,703 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 22:09:42,312 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 22:10:06,831 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 22:10:31,450 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 22:10:56,045 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 22:11:20,758 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 22:11:22,275 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 22:11:22,279 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 1: soft=0.28177 hard@0.50=0.31787 best_thr_med=0.80 best_thr_score=0.35358 pred_max_p90=0.9939

Epoch 2: val_whole_dice_hard_best_thr_score improved from 0.34880 to 0.35358, saving model to /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis1_coronal/callbacks/best_slice_block.weights.h5
420/420 - 972s - 2s/step - dice_coefficient: 0.0525 - foreground_fraction: 0.0053 - hard_dice_metric: 0.6397 - loss: 0.6239 - val_dice_coefficient: 0.0821 - val_foreground_fraction: 0.0071 - val_hard_dice_metric: 0.6384 - val_loss: 0.6652 - val_whole_dice_soft_macro: 0.2818 - val_whole_dice_hard: 0.3179 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3536
Epoch 3/18

2026-04-30 22:24:40,019 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 22:25:05,226 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 22:25:30,377 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 22:25:55,522 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 22:26:20,771 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 22:26:46,012 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 22:27:11,074 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 22:27:36,159 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 22:27:37,716 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 22:27:37,720 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 2: soft=0.26780 hard@0.50=0.31280 best_thr_med=0.80 best_thr_score=0.35085 pred_max_p90=0.9932

Epoch 3: val_whole_dice_hard_best_thr_score did not improve from 0.35358
420/420 - 967s - 2s/step - dice_coefficient: 0.0487 - foreground_fraction: 0.0055 - hard_dice_metric: 0.6209 - loss: 0.6345 - val_dice_coefficient: 0.0829 - val_foreground_fraction: 0.0071 - val_hard_dice_metric: 0.6020 - val_loss: 0.6582 - val_whole_dice_soft_macro: 0.2678 - val_whole_dice_hard: 0.3128 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3508
Epoch 4/18

2026-04-30 22:40:46,573 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 22:41:11,404 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 22:41:36,366 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 22:42:01,316 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 22:42:26,276 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 22:42:51,281 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 22:43:16,282 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 22:43:41,214 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 22:43:42,763 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 22:43:42,767 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 3: soft=0.26164 hard@0.50=0.30180 best_thr_med=0.80 best_thr_score=0.34150 pred_max_p90=0.9944

Epoch 4: val_whole_dice_hard_best_thr_score did not improve from 0.35358
420/420 - 965s - 2s/step - dice_coefficient: 0.0547 - foreground_fraction: 0.0054 - hard_dice_metric: 0.6447 - loss: 0.6230 - val_dice_coefficient: 0.0823 - val_foreground_fraction: 0.0077 - val_hard_dice_metric: 0.5791 - val_loss: 0.6514 - val_whole_dice_soft_macro: 0.2616 - val_whole_dice_hard: 0.3018 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3415
Epoch 5/18

2026-04-30 22:56:51,443 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 22:57:16,387 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 22:57:41,415 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 22:58:06,409 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 22:58:31,490 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 22:58:56,450 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 22:59:21,617 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 22:59:46,755 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 22:59:48,306 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 22:59:48,311 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 4: soft=0.24946 hard@0.50=0.30111 best_thr_med=0.80 best_thr_score=0.34412 pred_max_p90=0.9940

Epoch 5: val_whole_dice_hard_best_thr_score did not improve from 0.35358
420/420 - 966s - 2s/step - dice_coefficient: 0.0527 - foreground_fraction: 0.0058 - hard_dice_metric: 0.6312 - loss: 0.6344 - val_dice_coefficient: 0.0828 - val_foreground_fraction: 0.0079 - val_hard_dice_metric: 0.5898 - val_loss: 0.6422 - val_whole_dice_soft_macro: 0.2495 - val_whole_dice_hard: 0.3011 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3441
Epoch 6/18

2026-04-30 23:12:57,791 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 23:13:23,160 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 23:13:48,603 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 23:14:13,987 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 23:14:39,365 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 23:15:04,976 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 23:15:30,535 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 23:15:56,127 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 23:15:57,722 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 23:15:57,726 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 5: soft=0.28234 hard@0.50=0.32179 best_thr_med=0.80 best_thr_score=0.35771 pred_max_p90=0.9943

Epoch 6: val_whole_dice_hard_best_thr_score improved from 0.35358 to 0.35771, saving model to /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis1_coronal/callbacks/best_slice_block.weights.h5
420/420 - 978s - 2s/step - dice_coefficient: 0.0554 - foreground_fraction: 0.0059 - hard_dice_metric: 0.6608 - loss: 0.6263 - val_dice_coefficient: 0.0830 - val_foreground_fraction: 0.0068 - val_hard_dice_metric: 0.6337 - val_loss: 0.6605 - val_whole_dice_soft_macro: 0.2823 - val_whole_dice_hard: 0.3218 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3577
Epoch 7/18

2026-04-30 23:29:14,141 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 23:29:39,120 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 23:30:04,135 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 23:30:29,289 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 23:30:54,384 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 23:31:19,677 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 23:31:44,403 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 23:32:08,943 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 23:32:10,506 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 23:32:10,510 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 6: soft=0.27608 hard@0.50=0.31471 best_thr_med=0.80 best_thr_score=0.35179 pred_max_p90=0.9943

Epoch 7: val_whole_dice_hard_best_thr_score did not improve from 0.35771
420/420 - 964s - 2s/step - dice_coefficient: 0.0533 - foreground_fraction: 0.0053 - hard_dice_metric: 0.6520 - loss: 0.6257 - val_dice_coefficient: 0.0845 - val_foreground_fraction: 0.0072 - val_hard_dice_metric: 0.6194 - val_loss: 0.6555 - val_whole_dice_soft_macro: 0.2761 - val_whole_dice_hard: 0.3147 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3518
Epoch 8/18

2026-04-30 23:45:20,090 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-04-30 23:45:45,504 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-04-30 23:46:10,894 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-04-30 23:46:36,242 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-04-30 23:47:01,644 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-04-30 23:47:26,775 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-04-30 23:47:51,989 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-04-30 23:48:17,100 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-04-30 23:48:18,641 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-04-30 23:48:18,646 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 7: soft=0.27711 hard@0.50=0.31912 best_thr_med=0.80 best_thr_score=0.35635 pred_max_p90=0.9949

Epoch 8: val_whole_dice_hard_best_thr_score did not improve from 0.35771
420/420 - 968s - 2s/step - dice_coefficient: 0.0613 - foreground_fraction: 0.0067 - hard_dice_metric: 0.6445 - loss: 0.6260 - val_dice_coefficient: 0.0828 - val_foreground_fraction: 0.0072 - val_hard_dice_metric: 0.6290 - val_loss: 0.6529 - val_whole_dice_soft_macro: 0.2771 - val_whole_dice_hard: 0.3191 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3563
Epoch 9/18

2026-05-01 00:01:31,446 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-05-01 00:01:56,810 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-05-01 00:02:21,972 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-05-01 00:02:47,316 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-05-01 00:03:12,648 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-05-01 00:03:37,992 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-05-01 00:04:03,230 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-05-01 00:04:28,560 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-05-01 00:04:30,141 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-05-01 00:04:30,145 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 8: soft=0.27525 hard@0.50=0.32145 best_thr_med=0.80 best_thr_score=0.35950 pred_max_p90=0.9945

Epoch 9: val_whole_dice_hard_best_thr_score improved from 0.35771 to 0.35950, saving model to /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis1_coronal/callbacks/best_slice_block.weights.h5
420/420 - 980s - 2s/step - dice_coefficient: 0.0560 - foreground_fraction: 0.0065 - hard_dice_metric: 0.6434 - loss: 0.6374 - val_dice_coefficient: 0.0816 - val_foreground_fraction: 0.0068 - val_hard_dice_metric: 0.6136 - val_loss: 0.6549 - val_whole_dice_soft_macro: 0.2752 - val_whole_dice_hard: 0.3214 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3595
Epoch 10/18

2026-05-01 00:17:49,043 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-05-01 00:18:14,391 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-05-01 00:18:39,940 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-05-01 00:19:05,319 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-05-01 00:19:30,611 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-05-01 00:19:55,979 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-05-01 00:20:21,318 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-05-01 00:20:46,641 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-05-01 00:20:48,207 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-05-01 00:20:48,211 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 9: soft=0.28027 hard@0.50=0.33248 best_thr_med=0.80 best_thr_score=0.37012 pred_max_p90=0.9945

Epoch 10: val_whole_dice_hard_best_thr_score improved from 0.35950 to 0.37012, saving model to /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis1_coronal/callbacks/best_slice_block.weights.h5
420/420 - 978s - 2s/step - dice_coefficient: 0.0631 - foreground_fraction: 0.0065 - hard_dice_metric: 0.6213 - loss: 0.6276 - val_dice_coefficient: 0.0815 - val_foreground_fraction: 0.0066 - val_hard_dice_metric: 0.6574 - val_loss: 0.6561 - val_whole_dice_soft_macro: 0.2803 - val_whole_dice_hard: 0.3325 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3701
Epoch 11/18

2026-05-01 00:34:05,419 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-05-01 00:34:30,632 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-05-01 00:34:55,726 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-05-01 00:35:20,723 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-05-01 00:35:45,698 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-05-01 00:36:10,727 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-05-01 00:36:35,828 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-05-01 00:37:01,205 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-05-01 00:37:02,797 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-05-01 00:37:02,802 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 10: soft=0.25818 hard@0.50=0.31266 best_thr_med=0.80 best_thr_score=0.35448 pred_max_p90=0.9945

Epoch 11: val_whole_dice_hard_best_thr_score did not improve from 0.37012
420/420 - 966s - 2s/step - dice_coefficient: 0.0473 - foreground_fraction: 0.0055 - hard_dice_metric: 0.6521 - loss: 0.6360 - val_dice_coefficient: 0.0824 - val_foreground_fraction: 0.0073 - val_hard_dice_metric: 0.5990 - val_loss: 0.6427 - val_whole_dice_soft_macro: 0.2582 - val_whole_dice_hard: 0.3127 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3545
Epoch 12/18

2026-05-01 00:50:15,507 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-05-01 00:50:40,563 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-05-01 00:51:05,565 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-05-01 00:51:30,644 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-05-01 00:51:55,679 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-05-01 00:52:20,829 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-05-01 00:52:45,932 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-05-01 00:53:10,991 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-05-01 00:53:12,564 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-05-01 00:53:12,568 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 11: soft=0.27890 hard@0.50=0.32119 best_thr_med=0.80 best_thr_score=0.36000 pred_max_p90=0.9948

Epoch 12: val_whole_dice_hard_best_thr_score did not improve from 0.37012
420/420 - 970s - 2s/step - dice_coefficient: 0.0554 - foreground_fraction: 0.0062 - hard_dice_metric: 0.6349 - loss: 0.6178 - val_dice_coefficient: 0.0829 - val_foreground_fraction: 0.0073 - val_hard_dice_metric: 0.6356 - val_loss: 0.6526 - val_whole_dice_soft_macro: 0.2789 - val_whole_dice_hard: 0.3212 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3600
Epoch 13/18

2026-05-01 01:06:19,968 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-05-01 01:06:45,042 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-05-01 01:07:10,126 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-05-01 01:07:35,336 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-05-01 01:08:00,366 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-05-01 01:08:25,454 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-05-01 01:08:50,566 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-05-01 01:09:15,701 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-05-01 01:09:17,282 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-05-01 01:09:17,287 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 12: soft=0.27881 hard@0.50=0.32028 best_thr_med=0.80 best_thr_score=0.35987 pred_max_p90=0.9947

Epoch 13: val_whole_dice_hard_best_thr_score did not improve from 0.37012
420/420 - 965s - 2s/step - dice_coefficient: 0.0523 - foreground_fraction: 0.0062 - hard_dice_metric: 0.6426 - loss: 0.6216 - val_dice_coefficient: 0.0818 - val_foreground_fraction: 0.0071 - val_hard_dice_metric: 0.6256 - val_loss: 0.6562 - val_whole_dice_soft_macro: 0.2788 - val_whole_dice_hard: 0.3203 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3599
Epoch 14/18

2026-05-01 01:22:25,383 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-05-01 01:22:50,480 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-05-01 01:23:15,615 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-05-01 01:23:40,794 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-05-01 01:24:05,849 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-05-01 01:24:30,787 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-05-01 01:24:55,790 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-05-01 01:25:21,103 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-05-01 01:25:22,687 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-05-01 01:25:22,691 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 13: soft=0.27911 hard@0.50=0.32248 best_thr_med=0.80 best_thr_score=0.36177 pred_max_p90=0.9947

Epoch 14: val_whole_dice_hard_best_thr_score did not improve from 0.37012
420/420 - 965s - 2s/step - dice_coefficient: 0.0566 - foreground_fraction: 0.0059 - hard_dice_metric: 0.6224 - loss: 0.6154 - val_dice_coefficient: 0.0812 - val_foreground_fraction: 0.0069 - val_hard_dice_metric: 0.6298 - val_loss: 0.6589 - val_whole_dice_soft_macro: 0.2791 - val_whole_dice_hard: 0.3225 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3618
Epoch 15/18

2026-05-01 01:38:30,794 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-05-01 01:38:55,855 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-05-01 01:39:21,024 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-05-01 01:39:46,038 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-05-01 01:40:11,087 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-05-01 01:40:36,011 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-05-01 01:41:01,106 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-05-01 01:41:26,220 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-05-01 01:41:27,796 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-05-01 01:41:27,800 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 14: soft=0.27926 hard@0.50=0.32236 best_thr_med=0.80 best_thr_score=0.36128 pred_max_p90=0.9948

Epoch 15: val_whole_dice_hard_best_thr_score did not improve from 0.37012
420/420 - 965s - 2s/step - dice_coefficient: 0.0634 - foreground_fraction: 0.0066 - hard_dice_metric: 0.6460 - loss: 0.6188 - val_dice_coefficient: 0.0823 - val_foreground_fraction: 0.0071 - val_hard_dice_metric: 0.6320 - val_loss: 0.6567 - val_whole_dice_soft_macro: 0.2793 - val_whole_dice_hard: 0.3224 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3613
Epoch 16/18

2026-05-01 01:54:37,123 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 16/129
2026-05-01 01:55:02,221 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 32/129
2026-05-01 01:55:27,530 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 48/129
2026-05-01 01:55:52,623 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 64/129
2026-05-01 01:56:17,742 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 80/129
2026-05-01 01:56:43,037 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 96/129
2026-05-01 01:57:08,280 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 112/129
2026-05-01 01:57:33,380 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 128/129
2026-05-01 01:57:34,950 - SliceBlockTrainer - INFO - Whole-brain slice-block val progress: 129/129
2026-05-01 01:57:34,954 - SliceBlockTrainer - INFO - Whole-brain slice-block val @epoch 15: soft=0.27810 hard@0.50=0.32334 best_thr_med=0.80 best_thr_score=0.36195 pred_max_p90=0.9948

Epoch 16: val_whole_dice_hard_best_thr_score did not improve from 0.37012
420/420 - 967s - 2s/step - dice_coefficient: 0.0624 - foreground_fraction: 0.0061 - hard_dice_metric: 0.6628 - loss: 0.6185 - val_dice_coefficient: 0.0817 - val_foreground_fraction: 0.0069 - val_hard_dice_metric: 0.6267 - val_loss: 0.6586 - val_whole_dice_soft_macro: 0.2781 - val_whole_dice_hard: 0.3233 - val_whole_dice_hard_best_thr: 0.8000 - val_whole_dice_hard_best_thr_score: 0.3619
Epoch 16: early stopping
Restoring model weights from the end of the best epoch: 10.
Finished axis 1. Best checkpoint: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis1_coronal/callbacks/best_slice_block.weights.h5

In [5]:
# Review the per-axis fine-tune logs.
import pandas as pd

for axis, cfg in axis_cfgs.items():
    print("=" * 100)
    print(f"axis {axis} ({AXIS_NAMES[axis]})")
    train_log = cfg.CALLBACKS_DIR / "training_log.csv"
    whole_val_log = cfg.CALLBACKS_DIR / "whole_val_summary.jsonl"
    if train_log.exists():
        display(pd.read_csv(train_log).tail(8))
    else:
        print(f"No training log yet: {train_log}")
    if whole_val_log.exists():
        rows = [json.loads(line) for line in whole_val_log.read_text().splitlines() if line.strip()]
        display(pd.DataFrame(rows).tail(8))
    else:
        print(f"No whole-brain validation log yet: {whole_val_log}")

====================================================================================================
axis 2 (axial)

,epoch,dice_coefficient,foreground_fraction,hard_dice_metric,loss,val_dice_coefficient,val_foreground_fraction,val_hard_dice_metric,val_loss,val_whole_dice_hard,val_whole_dice_hard_best_thr,val_whole_dice_hard_best_thr_score,val_whole_dice_soft_macro
7,7,0.054197,0.008414,0.557751,0.641001,0.085699,0.008212,0.561632,0.659318,0.269375,0.8,0.312650,0.230496
8,8,0.050005,0.008289,0.541200,0.650162,0.084385,0.007930,0.565251,0.657844,0.272626,0.8,0.317812,0.227163
9,9,0.056126,0.008325,0.546668,0.641765,0.082890,0.008641,0.549658,0.654107,0.261656,0.8,0.306976,0.218684
10,10,0.042288,0.007663,0.549497,0.646770,0.083861,0.008320,0.550764,0.655266,0.265863,0.8,0.311313,0.222243
11,11,0.048045,0.008025,0.556634,0.635584,0.084879,0.008441,0.562420,0.655647,0.266140,0.8,0.310874,0.225977
12,12,0.043298,0.008635,0.543218,0.641935,0.083129,0.008910,0.523289,0.654508,0.255673,0.8,0.301475,0.216947
13,13,0.048979,0.007833,0.536163,0.630775,0.084415,0.008544,0.548378,0.655909,0.262724,0.8,0.308237,0.223327
14,14,0.056717,0.008486,0.560300,0.632438,0.084916,0.008491,0.555746,0.655951,0.264507,0.8,0.310388,0.224729

,epoch,elapsed_sec,n_cases,val_whole_dice_soft_macro,val_whole_dice_hard,val_whole_dice_hard_best_thr,val_whole_dice_hard_best_thr_score,pred_max_p90,pred_hard_voxels_median
7,7,236.224189,129,0.230496,0.269375,0.8,0.312650,0.991173,39668.0
8,8,236.704535,129,0.227163,0.272626,0.8,0.317812,0.990756,39538.0
9,9,236.315620,129,0.218684,0.261656,0.8,0.306976,0.990962,44947.0
10,10,235.694467,129,0.222243,0.265863,0.8,0.311313,0.990401,42616.0
11,11,236.186471,129,0.225977,0.266140,0.8,0.310874,0.990281,42352.0
12,12,238.442055,129,0.216947,0.255673,0.8,0.301475,0.989887,47525.0
13,13,242.867774,129,0.223327,0.262724,0.8,0.308237,0.989817,44406.0
14,14,241.060751,129,0.224729,0.264507,0.8,0.310388,0.989738,43362.0

====================================================================================================
axis 0 (sagittal)

,epoch,dice_coefficient,foreground_fraction,hard_dice_metric,loss,val_dice_coefficient,val_foreground_fraction,val_hard_dice_metric,val_loss,val_whole_dice_hard,val_whole_dice_hard_best_thr,val_whole_dice_hard_best_thr_score,val_whole_dice_soft_macro
4,4,0.031072,0.007032,0.518659,0.665690,0.055416,0.008175,0.494192,0.683311,0.256425,0.80,0.302713,0.208019
5,5,0.035024,0.007203,0.523839,0.653504,0.057690,0.006144,0.597708,0.699136,0.287787,0.70,0.321950,0.237583
6,6,0.031405,0.006242,0.520141,0.660759,0.058384,0.006314,0.570672,0.699815,0.284024,0.70,0.319251,0.238618
7,7,0.036495,0.007978,0.497547,0.661883,0.056535,0.006890,0.484155,0.693981,0.266865,0.80,0.303584,0.222088
8,8,0.033795,0.007681,0.473536,0.671835,0.056849,0.005745,0.534242,0.707223,0.278102,0.65,0.311983,0.230989
9,9,0.037166,0.008860,0.455907,0.665881,0.056221,0.006677,0.518185,0.698737,0.268469,0.80,0.305354,0.225202
10,10,0.028721,0.007138,0.496315,0.662991,0.054609,0.007962,0.441559,0.692258,0.248074,0.80,0.288509,0.205786
11,11,0.033164,0.008512,0.481866,0.653678,0.055273,0.006440,0.572622,0.709648,0.278168,0.70,0.309525,0.234043

,epoch,elapsed_sec,n_cases,val_whole_dice_soft_macro,val_whole_dice_hard,val_whole_dice_hard_best_thr,val_whole_dice_hard_best_thr_score,pred_max_p90,pred_hard_voxels_median
4,4,170.080105,129,0.208019,0.256425,0.80,0.302713,0.999601,42534.0
5,5,175.603923,129,0.237583,0.287787,0.70,0.321950,0.999426,22672.0
6,6,168.963327,129,0.238618,0.284024,0.70,0.319251,0.999456,22784.0
7,7,168.639539,129,0.222088,0.266865,0.80,0.303584,0.999615,30167.0
8,8,168.722354,129,0.230989,0.278102,0.65,0.311983,0.999530,24648.0
9,9,170.152300,129,0.225202,0.268469,0.80,0.305354,0.999474,30610.0
10,10,176.851672,129,0.205786,0.248074,0.80,0.288509,0.999416,45826.0
11,11,178.515188,129,0.234043,0.278168,0.70,0.309525,0.999430,23927.0

====================================================================================================
axis 1 (coronal)

,epoch,dice_coefficient,foreground_fraction,hard_dice_metric,loss,val_dice_coefficient,val_foreground_fraction,val_hard_dice_metric,val_loss,val_whole_dice_hard,val_whole_dice_hard_best_thr,val_whole_dice_hard_best_thr_score,val_whole_dice_soft_macro
8,8,0.055977,0.006535,0.643365,0.637362,0.081619,0.006794,0.613629,0.654887,0.321447,0.8,0.359497,0.275248
9,9,0.063057,0.006547,0.621287,0.627631,0.081507,0.006631,0.657382,0.656056,0.332477,0.8,0.370119,0.280268
10,10,0.047284,0.005489,0.652135,0.636002,0.082417,0.007328,0.599015,0.642700,0.312656,0.8,0.354479,0.258177
11,11,0.055414,0.006192,0.634851,0.617836,0.082894,0.007330,0.635644,0.652624,0.321186,0.8,0.360000,0.278901
12,12,0.052328,0.006188,0.642616,0.621564,0.081774,0.007059,0.625561,0.656236,0.320279,0.8,0.359869,0.278812
13,13,0.056584,0.005934,0.622427,0.615411,0.081243,0.006891,0.629758,0.658908,0.322484,0.8,0.361766,0.279108
14,14,0.063361,0.006576,0.645951,0.618752,0.082279,0.007105,0.631962,0.656710,0.322357,0.8,0.361279,0.279259
15,15,0.062412,0.006092,0.662750,0.618492,0.081725,0.006873,0.626683,0.658568,0.323336,0.8,0.361945,0.278102

,epoch,elapsed_sec,n_cases,val_whole_dice_soft_macro,val_whole_dice_hard,val_whole_dice_hard_best_thr,val_whole_dice_hard_best_thr_score,pred_max_p90,pred_hard_voxels_median
8,8,204.179630,129,0.275248,0.321447,0.8,0.359497,0.994537,23194.0
9,9,204.780721,129,0.280268,0.332477,0.8,0.370119,0.994468,22537.0
10,10,202.934186,129,0.258177,0.312656,0.8,0.354479,0.994491,27334.0
11,11,202.404045,129,0.278901,0.321186,0.8,0.360000,0.994810,24060.0
12,12,202.683977,129,0.278812,0.320279,0.8,0.359869,0.994679,23979.0
13,13,202.821404,129,0.279108,0.322484,0.8,0.361766,0.994722,23928.0
14,14,202.347828,129,0.279259,0.322357,0.8,0.361279,0.994802,24628.0
15,15,203.419683,129,0.278102,0.323336,0.8,0.361945,0.994831,23560.0

In [6]:
# Evaluate the fine-tuned ensemble on the mixed validation split and its ATLAS subset.
trained_axes = [axis for axis, cfg in axis_cfgs.items() if cfg.checkpoint_path.exists()]
if not trained_axes:
    raise FileNotFoundError("No fine-tuned checkpoints exist yet. Run the training cell first.")

trained_cfgs = [axis_cfgs[axis] for axis in trained_axes]
weights_paths = [axis_cfgs[axis].checkpoint_path for axis in trained_axes]

atlas_subset_summary = seg.evaluate_slice_block_ensemble(
    configs=trained_cfgs,
    weights_paths=weights_paths,
    cases=mixed_val_atlas_cases,
    out_dir=RUN_DIR / "atlas_subset_eval",
    thresholds=COMMON_CFG["VAL_THRESHOLD_SWEEP"],
    decision_threshold=COMMON_CFG["DECISION_THRESHOLD"],
    save_predictions=6,
)

mixed_summary = seg.evaluate_slice_block_ensemble(
    configs=trained_cfgs,
    weights_paths=weights_paths,
    cases=mixed_val_cases,
    out_dir=RUN_DIR / "mixed_ensemble_eval",
    thresholds=COMMON_CFG["VAL_THRESHOLD_SWEEP"],
    decision_threshold=COMMON_CFG["DECISION_THRESHOLD"],
    save_predictions=6,
)

print("ATLAS subset of mixed validation summary")
print(json.dumps(atlas_subset_summary, indent=2))
print()
print("Full mixed-domain validation summary")
print(json.dumps(mixed_summary, indent=2))

2026-05-01 01:59:01,975 - SliceBlockTrainer - INFO - Slice-block ensemble val progress: 16/88
2026-05-01 02:00:08,078 - SliceBlockTrainer - INFO - Slice-block ensemble val progress: 32/88
2026-05-01 02:01:14,359 - SliceBlockTrainer - INFO - Slice-block ensemble val progress: 48/88
2026-05-01 02:02:20,640 - SliceBlockTrainer - INFO - Slice-block ensemble val progress: 64/88
2026-05-01 02:03:26,880 - SliceBlockTrainer - INFO - Slice-block ensemble val progress: 80/88
2026-05-01 02:04:00,065 - SliceBlockTrainer - INFO - Slice-block ensemble val progress: 88/88
2026-05-01 02:04:00,068 - SliceBlockTrainer - INFO - Slice-block ensemble val: soft=0.15133 hard@0.50=0.26685 best_thr_med=0.62 best_thr_score=0.32445
2026-05-01 02:05:16,479 - SliceBlockTrainer - INFO - Slice-block ensemble val progress: 16/129
2026-05-01 02:06:22,775 - SliceBlockTrainer - INFO - Slice-block ensemble val progress: 32/129
2026-05-01 02:07:28,949 - SliceBlockTrainer - INFO - Slice-block ensemble val progress: 48/129
2026-05-01 02:08:35,157 - SliceBlockTrainer - INFO - Slice-block ensemble val progress: 64/129
2026-05-01 02:09:41,302 - SliceBlockTrainer - INFO - Slice-block ensemble val progress: 80/129
2026-05-01 02:10:47,591 - SliceBlockTrainer - INFO - Slice-block ensemble val progress: 96/129
2026-05-01 02:11:53,848 - SliceBlockTrainer - INFO - Slice-block ensemble val progress: 112/129
2026-05-01 02:13:00,154 - SliceBlockTrainer - INFO - Slice-block ensemble val progress: 128/129
2026-05-01 02:13:04,300 - SliceBlockTrainer - INFO - Slice-block ensemble val progress: 129/129
2026-05-01 02:13:04,305 - SliceBlockTrainer - INFO - Slice-block ensemble val: soft=0.24390 hard@0.50=0.35681 best_thr_med=0.60 best_thr_score=0.40735

ATLAS subset of mixed validation summary
{
  "elapsed_sec": 383.96516489982605,
  "n_cases": 88,
  "weights_paths": [
    "/home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis2_axial/callbacks/best_slice_block.weights.h5",
    "/home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis0_sagittal/callbacks/best_slice_block.weights.h5",
    "/home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis1_coronal/callbacks/best_slice_block.weights.h5"
  ],
  "axes": [
    2,
    0,
    1
  ],
  "block_depths": [
    7,
    7,
    7
  ],
  "decision_threshold": 0.5,
  "val_whole_dice_soft_macro": 0.1513317962056714,
  "val_whole_dice_hard": 0.2668513456046168,
  "val_whole_dice_hard_best_thr": 0.625,
  "val_whole_dice_hard_best_thr_score": 0.324446354840576,
  "source_best_threshold_dice": {
    "ATLAS-Images-f0d7431e": 0.324446354840576
  },
  "lesion_group_best_threshold_dice": {
    "10000_plus": 0.4185929827755458,
    "1000_9999": 0.3160949563183311,
    "100_999": 0.228012250923942,
    "1_99": 0.07953086150034021
  }
}

Full mixed-domain validation summary
{
  "elapsed_sec": 543.6590340137482,
  "n_cases": 129,
  "weights_paths": [
    "/home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis2_axial/callbacks/best_slice_block.weights.h5",
    "/home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis0_sagittal/callbacks/best_slice_block.weights.h5",
    "/home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/axis1_coronal/callbacks/best_slice_block.weights.h5"
  ],
  "axes": [
    2,
    0,
    1
  ],
  "block_depths": [
    7,
    7,
    7
  ],
  "decision_threshold": 0.5,
  "val_whole_dice_soft_macro": 0.243895434916819,
  "val_whole_dice_hard": 0.3568105867585164,
  "val_whole_dice_hard_best_thr": 0.6,
  "val_whole_dice_hard_best_thr_score": 0.4073517477455883,
  "source_best_threshold_dice": {
    "ARC-combined-t1-raw-ab0d1794": 0.6678741105965206,
    "ATLAS-Images-f0d7431e": 0.324446354840576,
    "Approx-Numeracy-Processed": 0.4074323951159711
  },
  "lesion_group_best_threshold_dice": {
    "10000_plus": 0.5475016108894124,
    "1000_9999": 0.31178643984542775,
    "100_999": 0.22269193078863617,
    "1_99": 0.20143919179099612
  }
}

In [ ]:
# Export one manual probability map and segmentation from the fine-tuned ensemble.
trained_axes = [axis for axis, cfg in axis_cfgs.items() if cfg.checkpoint_path.exists()]
if not trained_axes:
    raise FileNotFoundError("No fine-tuned checkpoints exist yet. Run the training cell first.")

models = [seg.load_slice_block_model(axis_cfgs[axis], axis_cfgs[axis].checkpoint_path) for axis in trained_axes]
trained_cfgs = [axis_cfgs[axis] for axis in trained_axes]
case = mixed_val_atlas_cases[0] if mixed_val_atlas_cases else mixed_val_cases[0]
prob, mask, ref_img = seg.predict_ensemble_probability_map(models, trained_cfgs, case)
out_dir = RUN_DIR / "manual_atlas_ensemble_prediction"
seg.save_case_outputs(out_dir, case, prob, COMMON_CFG["DECISION_THRESHOLD"], ref_img)

print(f"Saved probability map and threshold segmentation to: {out_dir}")
print(f"Case: {case.case_id}")
print(f"Probability range: min={float(prob.min()):.6f}, max={float(prob.max()):.6f}")
print(f"Threshold voxels @ {COMMON_CFG['DECISION_THRESHOLD']:.2f}: {int((prob >= COMMON_CFG['DECISION_THRESHOLD']).sum())}")
seg.tf.keras.backend.clear_session()

Saved probability map and threshold segmentation to: /home/rbielski/stroke_cleaned/ARC_ATLAS_Combined/ARC_ATLAS_Train_v4/runs/20260430_141421_slice_blocks_resume_atlas_replay_looserfreeze/manual_atlas_ensemble_prediction
Case: ATLAS-Images-f0d7431e__ATLAS-Images-f0d7431e__sub-r011s017_ses-1_space-MNI152NLin2009aSym_T1w_MNI_norm
Probability range: min=0.000002, max=0.992528
Threshold voxels @ 0.50: 2615

: